### ISSUE TITLE
SVG: Update high priority API pages [2/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#100]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern MDN API layout pages.

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGClipPathElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGGElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMaskElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGPatternElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTextContentElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTextElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTextPathElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTextPositioningElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTSpanElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGUseElement
