### ISSUE TITLE
SVG: Add example on top of high priority API pages [2/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#101]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGClipPathElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGGElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMaskElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGPatternElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTextContentElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTextElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTextPathElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTextPositioningElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTSpanElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGUseElement
