### ISSUE TITLE
SVG: Update medium priority element pages [1/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#102]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, adding a better attributes overview)

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/stop
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/style
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tspan
