### ISSUE TITLE
SVG: Add example on top of medium priority element pages [1/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#103]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/script
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/stop
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/style
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tspan
