### ISSUE TITLE
Prototype MDN Web DNA CTA

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1037]
# User story

After talking with @atopal, we decided to turn https://github.com/mdn/sprints/issues/946 into an Epic, and split out related work into separate user stories of which this is the first.

# Acceptance criteria

A couple of points that have been clarified:

- [ ] On load, load CTA minimised
- [ ] CTA should be able to handle something as simple as some HTML content with a button/link up to a complex item such as the current payments banner
- [ ] When a CTA is dismissed(using the close button) it is not shown to the user again for 30 days
- [ ] If a CTA is dismissed, the next CTA in the queue should be shown on next page load
- [ ] Never show more than one CTA at a time
- [ ] Should be able to update CTAs or add new items without needing a Kuma production push
- [ ] Discussing building a service similar to Firefox snippets but for MDN from which content(CTA) can be dynamically loaded at runtime 
- [ ] Would be ideal to have an admin UI to manage CTAs

# Tasks

1. - [ ] Define MVP
2. - [ ] Implement prototype based on MVP decision

**Comment by jwhitlock** [comment]
Replaced by #1092 or #1130
