### ISSUE TITLE
SVG: Add example on top of medium priority element pages [2/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#105]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/filter
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feBlend
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feColorMatrix
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComponentTransfer
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feConvolveMatrix
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDisplacementMap
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDropShadow
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFlood
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncA
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncB
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncG
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feFuncR
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feGaussianBlur
