### ISSUE TITLE
SVG: Update medium priority element pages [3/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#106]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, adding a better attributes overview)

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDistantLight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDiffuseLighting
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feImage
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMerge
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMergeNode
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMorphology
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feOffset
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpecularLighting
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpotLight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTile
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTurbulence
