### ISSUE TITLE
SVG: Add example on top of medium priority element pages [3/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#107]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDistantLight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDiffuseLighting
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feImage
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMerge
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMergeNode
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMorphology
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feOffset
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/fePointLight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpecularLighting
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feSpotLight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTile
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feTurbulence
