### ISSUE TITLE
SVG: Update medium priority element pages [4/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#108]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, adding a better attributes overview)

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateColor
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mpath
