### ISSUE TITLE
Conditionally load IEx and related assets based on viewport

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1089]
# User story

In https://github.com/mdn/sprints/issues/921 a couple of initial tests and experiments was done to see if there is a quick fix to the performance issues on mobile with regards to the interactive examples.

We have come to the conclusion that the only way we will gain the needed performance improvements for mobile users is to conditionally load IEx based on viewport dimensions.

To do this the following changes needs to be made to the existing code:

### KumaScript

The [EmbedInteractiveExample](https://github.com/mdn/kumascript/blob/master/macros/EmbedInteractiveExample.ejs) needs to have the following changes:

1. Set the `src` url of the `iframe` as a data attribute(`data-iframe-src`) instead of directly on the `src` attribute
2. Set the `src` attribute value to `about:blank`
3. Add the class `hidden` to the `iframe`
4. To more uniquely identify the IEx iframe, give it an id of `iex-interactive`

### Kuma

Add a new script called `iex-init.js` that:

1. Test whether the viewport size is equal to mobile using [matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia)
2. If we are on mobile, do nothing further
3. If the above is not true, check for the presence of an `iframe` with the id `iex-interactive`

If the `iframe` is not found.

1. Do nothing

If the iframe is found.

1. Load and inject the following scripts async using `fetch` or `XHR`
1.1 perf-post-message-handler.js
1.2 post-message-handler.js
1.3 interactive.js
2. Once the above is complete, get the source url for the `iframe` from the above-mentioned data attribute, set the `iframe` `src` attribute, remove the `hidden` class.

There are some minor changes needed to `interactive.js` to ensure it executes correctly in the new context but, from here on everything should work as it currently does.

### Tests

There is no easy way to test this alongside the current implementation so, I suggest the following approach:

1. Test existing implementation locally using auditing tools in DevTools and record the stats on desktop and mobile
2. Make changes as detailed
3. Test new implementation locally using auditing tools in DevTools and compare stats
4. If the stats indicate a positive result
5. Open pull request for review
6. Push to production
7. Watch high traffic pages for a period of 5 days?
8. Based on the results, back out the changes or, leave in place if successful.

# Acceptance criteria

- [ ] IEx works on the desktop as it does currently
- [ ] IEx is not loaded at mobile viewport sizes, the iframe is not loaded, and no unnecessary assets and scripts are loaded/executed.
- [ ] We see a significant performance improvement on mobile
- [ ] No, or limited performance degradation on desktop

# Tasks

Tasks are described in the above user story section.

**Comment by atopal** [comment]
I'm generally okay with this, even though I'd really prefer testing the changes side by side. 

Can you add another acceptance criteria for performance on desktop? That one should not be negatively impacted by this.

> Watch high traffic pages for a period of 5 days?
Can you specific what we'd be watching for?
