### ISSUE TITLE
SVG: Add example on top of medium priority element pages [4/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#109]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateColor
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mpath
