### ISSUE TITLE
Experiment: Choose 10 high-traffic pages and add descriptive titles

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#1091]
Select 10 pages in the CSS reference and add descriptive titles.

**Time estimate:** 2 ideal days; this is because not only do the titles need to be written and replaced, but we need to decide what form they should take. Munging all the non-contiguous time involved together, I estimate 2 days of work.

## Title requirements

* The titles shouldn't be longer than 68 or so characters.
* They should include the name of the object and member (of course) and indicate in some manner what type of item the page is describing (method, property, etc).
* There should be some short descriptive text that includes useful keywords.
* Title should start with JavaScript, CSS HTML, etc

## Page requirements
* Pages that are not ranked in first position
* Pages that had more than 10k clicks in the last month
* Test and control pages should be thematically clustered

## Tasks

- [x] Discuss and decide upon a format for the titles
- [x] Select 10 popular pages to re-title
- [x] Update the 10 pages' titles
- [x] set up testing in sanitycheck
- [ ] Wait <however long>, then compare analytic data

## Acceptance criteria

- [x] Pages have been retitled appropriately
- [ ] Enough time has elapsed to obtain valid results
- [ ] Data is collected and analyzed and a conclusion reached as to whether the change was worthwhile

**Comment by a2sheppy** [comment]
The goal is to do this in the next sprint (Q1 S3 / Grace Jones).
