### ISSUE TITLE
Implement user login / profile link in browser

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#1098]
# User story
As a developer, I want to implement the user login (anonymous) / profile image (logged in) selection in the browser, so I can explore per-user, in-browser customization of content.

# Acceptance criteria
* [ ] In demo pages on staging, the login / profile section is implemented in the browser

# Tasks
* [ ] Research suitability of Django REST Framework for first version
* [ ] Implement read-only API of current user JSON, with anonymous fallback
* [ ] Apply the profile image client-side
* [ ] Stretch - store current user data in local storage, synced with server

**Comment by davidflanagan** [comment]
I didn't keep this issue up to date with the frontend work, but the React Login component has been updated to be able to display the user's avatar and a dropdown menu with the view profile/edit profile/sign out options.  A new CurrentUser React component uses fetch() to use the whoami API and makes user data available through React's context mechanism.

We've satisfied the acceptance criteria, so closing this issue now.
