### ISSUE TITLE
Remove App Center, Round #2

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#1099]
# User story
As a MDN reader, I want to complete the removal of the App Center, so that I don't see stale documentation.

This is follow-on work from task #977.

# Acceptance criteria
* Documents under ``Web/Apps`` are deleted in all translations

# Tasks
Delete the following:

* [x] https://developer.mozilla.org/en-US/docs/Web/Apps
* [x] https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals
* [x] https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals
* [x] https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Modern_web_app_architecture
* [x] https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Games
* [x] https://developer.mozilla.org/ja/docs/Web/Apps/Tutorials
* [x] https://developer.mozilla.org/en-US/docs/Web/Apps/Tutorials
* [x] https://developer.mozilla.org/en-US/docs/Web/Apps/App_layout

# References
* [bug 1529021](https://bugzilla.mozilla.org/show_bug.cgi?id=1529021)

**Comment by jwhitlock** [comment]
Django 1.11 added some checks for foreign key relations, and is preventing deleting Documents if:

* There are related child Documents (reverse of ``parent_topic`` relation). A redirect counts as a child document.
* There are related translation Documents (reverse of ``parent`` relation).

Because Django doesn't know about soft-deletion, a purge is needed to remove soft-deleted documents. It is a bit like disassembling a block tower from the the top down, one at a time.

**Comment by jwhitlock** [comment]
Here's a deeper dive into one, for future reference.

https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals shows no children at ``$children``, but it actually had four children and one grandchild:

* https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals/Quickstart (redirect)
    * https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals/Quickstart/Design (not redirect)
        * https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals/Quickstart/Design/Concept_A_great_app (not redirect)
    * https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals/Quickstart/%E6%9C%80%E5%88%9D%E3%81%AE%E3%82%A2%E3%83%97%E3%83%AA%E3%82%92%E4%BD%9C%E3%82%8B (redirect)
    * https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals/Quickstart/%E3%83%86%E3%82%B9%E3%83%88%E3%81%A8%E3%83%87%E3%83%90%E3%83%83%E3%82%B0 (redirect)
    * https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals/Quickstart/Building_simple_functionality (redirect)

I used "View in Admin" to find the Document ID (``61379``), and then the Django shell to generate the list (``Document.objects.get(id=61379).get_descendents()``).

For each page, I loaded the delete page by adding "``$delete``" to the end of the URL, being careful not to load the redirects.

Django wouldn't allow me to delete https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals/Quickstart until I purged the document Quickstart/Design and Quickstart/Design/Concept_A_great_app. It is possible that just the grandchild page needed to be purged.

With those pages deleted, I was able to soft-delete https://developer.mozilla.org/ja/docs/Web/Apps/Fundamentals. My new theory is that the problem is un-purged descendants that are not redirects.

**Comment by jwhitlock** [comment]
All the pages are deleted, with the exception of https://developer.mozilla.org/en-US/docs/Web/Apps, which I changed to a redirect to https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

**Comment by chrisdavidmills** [comment]
Thanks so much @jwhitlock. I really appreciate you figuring this stuff out and helping me to finish cleaning this up. I think redirecting Apps to the PWA page is fine.
