### ISSUE TITLE
SVG: Update medium priority attribute pages [1/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#110]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/type
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/lengthAdjust
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/path
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/side
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fr
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fx
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fy
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientTransform
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-color
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-opacity
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space

**Comment by SebastianZ** [comment]
Those attributes are now all updated. Note that for [`type`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/type) you don't see the current page at the moment, but Peter is already working on a fix for that in [bug 1551999](https://bugzilla.mozilla.org/show_bug.cgi?id=1551999).

Sebastian

**Comment by jmswisher** [comment]
Hooray! Thanks @SebastianZ ! And the version bug is now fixed, too.
