### ISSUE TITLE
Sort of Firefox 66 rel notes / other content

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1109]
# User story
As a developer, I want to read release notes on the new features available in Firefox 66, so I can find out what I can use in my work.

# Acceptance criteria
- [x] Firefox 66 release notes are updated per DDNs and DDCs.
- [x] Experimental Features page is updated per above.
- [x] platform-status is updated accordingly.
- [x] Fx 66 Tweets are drafted.

# Tasks
1. - [x] Run bugzilla query to bring up added Firefox 66 features marked with dev-doc-needed and dev-doc-complete keywords.
2. - [x] Make sure all these features are recorded on the Firefox 66 release notes.
3. - [x] Update Experimental Features page accordingly
4. - [x] Give Fx 66 rel notes a final copy edit
4. - [x] Update platform-status accordingly
5. - [x] Write Fx 66 tweets for Danielle

See also the relevant roadmap entry: https://trello.com/c/H4Ci5VQz/200-firefox-67-release-notes

**Comment by chrisdavidmills** [comment]
Tweets for Danielle:

* The `x-moz-errormessage` attribute has been removed from Firefox starting with version 66. You should use https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation instead to create custom validation messages.
* CSS scroll anchoring is implemented in Firefox 66! (https://drafts.csswg.org/css-scroll-anchoring/)
* The `i` modifier has been introduced for attribute selectors in Firefox 66, meaning you can specify case insensitive matches (e.g. `a[href*="insensitive" i]`) . Find out more at https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors.
* Firefox 66 sees several new logical property block and inline shorthands introduced, as well as flow-relative border radius properties. For more, visit https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties
* The `overflow-block` and `overflow-inline` media features have been introduced in Firefox 66 (see https://developer.mozilla.org/en-US/docs/Web/CSS/@media).
* In Firefox 66, the `grid-template-columns` and `grid-template-rows` properties are now animatable.
* Hot on the tail of Firefox 66, we've unprefixed the `min-content` and `max-content` keywords, used to specify intrinsic width settings for properties like `width`.
* Autoplaying audio will be blocked by default in Firefox 66; this feature will be rolled out gradually until everyone has it. 
* Web components have some useful new features in Firefox 66, such as `Element.nodesFromPoint()` and `slot.assignedElements()` (see https://developer.mozilla.org/en-US/docs/Web/Web_Components)
* The `InputEvent.inputType` property has bene implemented in Firefox 66 (https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/inputType)
* Firefox 66 sees AV1 video codec support enabled by default on Windows.
