### ISSUE TITLE
SVG: Add example on top of medium priority attribute pages [1/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#111]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/type
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/lengthAdjust
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/path
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/side
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fr
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fx
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fy
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientTransform
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-color
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-opacity
