### ISSUE TITLE
Add governance document to BCD

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#1112]
# User story
As a the mdn-browser-compat-data repo owner, I want to have clear governance in place so I can work effectively with contributors, collaborators, and co-maintainers.

# Acceptance criteria
A document describing roles and repo governance is reviewed, agreed on, and merged to mdn/browser-compat-data.

# Tasks
- [ ] Review Florian's proposed governance doc from October 2018
- [ ] Convert it to markdown file(s)
- [ ] Open PR, review and land it.

**Comment by Elchi3** [comment]
See https://github.com/mdn/browser-compat-data/pull/3668 for progress
