### ISSUE TITLE
SVG: Update medium priority attribute pages [2/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#112]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseline-shift
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-rule
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/flood-color
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/flood-opacity
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-size-adjust
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/image-rendering
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/lighting-color
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/kerning
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-overflow
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-rendering

**Comment by SebastianZ** [comment]
All done. Note that [`clip-rule`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-rule) and [`font-size-adjust`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-size-adjust) are affected by [bug 1551999](https://bugzilla.mozilla.org/show_bug.cgi?id=1551999), so you won't see the current versions until that's fixed.

Sebastian

**Comment by jmswisher** [comment]
Thanks @SebastianZ !
