### ISSUE TITLE
SVG: Add example on top of medium priority attribute pages [2/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#113]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseline-shift
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-rule
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/flood-color
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/flood-opacity
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-size-adjust
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/image-rendering
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/lighting-color
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/kerning
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-overflow
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-rendering
