### ISSUE TITLE
Grizzly Django Admin App v0.5

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1130]
# User story

Develop a Django admin app to manage all banners displayed across MDN Web Docs. The app will consist of two parts.

1. An admin area inside the existing Django admin
2. Either a context processor, template tag or API to display banners in the UI (needs decision)

## List view

![grizzly-list](https://user-images.githubusercontent.com/10350960/53641433-9314ea00-3c37-11e9-8ae2-c5ce85496ff6.png)

The above is the iniital list view of all banners that has been created. From here the user can then easily toggle the state of the banner between active and inactive.

There is also a button, that will take the user to the new banner screen.

## Create banner view

![add-new](https://user-images.githubusercontent.com/10350960/53641909-0703c200-3c39-11e9-8915-7f21b610d959.png)

As can be seen from the screen shot above, the create new banner UI will allow a user to:

1. Name the banner
2. Provide a title
3. Add main copy
4. Provide button copy
5. Choose a theme from a list of predefined themes
6. Mark the banner as active

### Front end functionality

The functionality on the front end will match that of https://github.com/mdn/sprints/issues/1129

# Acceptance criteria

<img width="1678" alt="screenshot 2019-02-28 at 14 31 48" src="https://user-images.githubusercontent.com/10350960/53566701-a2c3fe00-3b65-11e9-90e4-2ac30beae4bb.png">

- [ ] All banners will follow the content and layout as in the image above
- [ ] Three basic themes are available to choose from
- [ ] Ability to see all banners in a simple list
- [ ] Ability to activate and deactivate individual banners from the above list
- [ ] Ability to create a new banner, and define the theme, heading, main copy and button copy
- [ ] The content of the banners are localizable

# Tasks

1. - [ ] TBD

**Comment by schalkneethling** [comment]
@atopal @jwhitlock @escattone @davidflanagan here is the user story with regards to the initial work towards a unified banner system. This is most likely not complete yet, as I need input and guidance from everyone here.

Thanks!

**Comment by jwhitlock** [comment]
I think this is a good framework for getting started on the task. On the backend side, the tasks would be:

* Create ``/kuma/banners`` (sorry to be boring, but I think ``/kuma/grizzly`` will raise too many WTFs in a few years)
* Add a Banner model with the fields specified in editing
* Add an admin for the fields

There will be an edit view that is a lot like the create view, which I think we can leave unspecified. I'm assuming the themes are keywords into banner styles defined in CSS, not a relation to a different database table. If my assumption is correct, I think this is an effective way to build this feature.

My suggestion is to include a preview in the create/edit view to show what the banner looks like. If the viewer can change their screen width to see tablet and mobile, that works, otherwise I'd want current / tablet / mobile variants (or however you are marking width transitions). If you need a preview page rather than an in-admin widget, we can ``iframe`` it.

I think there are some missing targeting options:

* Locale - All / English-Only seems like the first two options, but I imagine there will be more in the future. Still, [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it), so this could just be a checkmark for v1. To support translations, we can add an export option to get strings from the database into Pontoon, similar to the search topic exporter.
* Targeting - I'd like to optionally associate a banner with a waffle flag. This gets us user / group / percent targeting with little code duplication.

**Comment by schalkneethling** [comment]
Thanks for all of the info @jwhitlock 👍

**Comment by davidflanagan** [comment]
How are you planning to develop the front end? Are the admin pages an interesting use case for trying React? Or would it be simpler to stick with jinja templates for this? (The screenshots are cool looking... How did you create those?)

Consider checkboxes for the active/inactive state. It is not clear to me that green/red Activate/Deactivate buttons make UX sense. Is "Deactivate" somehow a more dangerous action than "Activate"?

I thought I heard you say that when there are multiple banners there needs to be some kind of priority system so Kuma knows which ones to display to users and doesn't just try to display them all at the same time. I assume that you don't want to implement a drag-and-drop interface for reordering banners... Do you need an way to specify an integer priority when creating a new banner?

**Comment by jwhitlock** [comment]
The Django admin is written in Django templates. The easiest thing is to use the existing admin designs, so the resulting pages will look like a more boring version of these screenshots, but with the same fields. I think we should focus the React work on existing, user-facing pages.

I think a priority makes sense. I suggest 1 - 100, with a higher number meaning that the banner is shown before banners with a lower number. Again, this will be a staff-facing interface, so I think a simple number field will be sufficient.

**Comment by schalkneethling** [comment]
> I'm assuming the themes are keywords into banner styles defined in CSS

@jwhitlock correct

> My suggestion is to include a preview in the create/edit view to show what the banner looks like.

Great idea

> All / English-Only seems like the first two options

Agreed

> I'd like to optionally associate a banner with a waffle flag. This gets us user / group / percent targeting with little code duplication.

👍 

> How are you planning to develop the front end? Are the admin pages an interesting use case for trying React? Or would it be simpler to stick with jinja templates for this?

@davidflanagan - As John mentions, I believe it is best to stick with what Django provides here.

> The screenshots are cool looking... How did you create those?

I quickly drew these up in Photoshop ;p

> Consider checkboxes for the active/inactive state. It is not clear to me that green/red Activate/Deactivate buttons make UX sense. Is "Deactivate" somehow a more dangerous action than "Activate"?

Agree

> I thought I heard you say that when there are multiple banners there needs to be some kind of priority system

I reckon John's suggestions works for this.

Thank you for your feedback and info everyone!

**Comment by schalkneethling** [comment]
## Feature request

<Topal> Ability to show banners for just a part of MDN say /learn/

**Comment by schalkneethling** [comment]
For reference: https://github.com/mdn/sprints/issues/1092
