### ISSUE TITLE
SVG: Update medium priority attribute pages [3/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#114]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filterRes
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filterUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/primitiveUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/in
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/result
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/in2
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/mode
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/operator
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k1
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k2
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k3
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k4

**Comment by SebastianZ** [comment]
All updated.

Sebastian

**Comment by jmswisher** [comment]
Thanks @SebastianZ !
