### ISSUE TITLE
SVG: Add example on top of medium priority attribute pages [3/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#115]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filterRes
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filterUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/primitiveUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/in
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/result
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/in2
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/mode
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/operator
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k1
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k2
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k3
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/k4
