### ISSUE TITLE
SVG: Update medium priority attribute pages [4/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#116]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/kernelUnitLength
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/bias
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/divisor
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/edgeMode
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/kernelMatrix
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/order
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAlpha
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/targetX
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/targetY

**Comment by SebastianZ** [comment]
All updated.

Sebastian

**Comment by jmswisher** [comment]
Thanks @SebastianZ !
