### ISSUE TITLE
SVG: Add example on top of medium priority attribute pages [4/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#117]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/kernelUnitLength
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/bias
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/divisor
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/edgeMode
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/kernelMatrix
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/order
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAlpha
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/targetX
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/targetY
