### ISSUE TITLE
SVG: Update medium priority attribute pages [5/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#118]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/surfaceScale
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/diffuseConstant
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/z
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/specularExponent
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/specularConstant
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/limitingConeAngle
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointsAtX
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointsAtY
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointsAtZ
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/azimuth
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/elevation
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseFrequency
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/numOctaves
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/seed
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stitchTiles
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/scale
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xChannelSelector
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/yChannelSelector
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stdDeviation

**Comment by SebastianZ** [comment]
All updated.

Sebastian

**Comment by jmswisher** [comment]
Thanks @SebastianZ !
