### ISSUE TITLE
SVG: Add example on top of medium priority attribute pages [5/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#119]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/surfaceScale
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/diffuseConstant
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/z
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/specularExponent
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/specularConstant
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/limitingConeAngle
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointsAtX
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointsAtY
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointsAtZ
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/azimuth
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/elevation
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseFrequency
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/numOctaves
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/seed
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stitchTiles
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/scale
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xChannelSelector
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/yChannelSelector
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stdDeviation
