### ISSUE TITLE
SVG: Update medium priority attribute pages [6/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#120]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/values
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/accumulate
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/additive
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/attributeName
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/attributeType
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/begin
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/calcMode
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dur
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/end
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/from
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/keySplines
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/keyTimes
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/max
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/min
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/repeatCount
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/repeatDur
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/restart
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/to

**Comment by SebastianZ** [comment]
All updated.

Sebastian

**Comment by jmswisher** [comment]
Thanks @SebastianZ !
