### ISSUE TITLE
SVG: Add example on top of medium priority attribute pages [6/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#121]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/values
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/accumulate
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/additive
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/attributeName
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/attributeType
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/begin
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/calcMode
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dur
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/end
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/from
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/keySplines
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/keyTimes
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/max
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/min
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/repeatCount
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/repeatDur
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/restart
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/to
