### ISSUE TITLE
SVG: Update medium priority attribute pages [7/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#122]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/contentScriptType
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/contentStyleType
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:lang
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-interpolation
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-interpolation-filters
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-profile
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-rendering

**Comment by SebastianZ** [comment]
All updated.

Sebastian

**Comment by jmswisher** [comment]
Thanks @SebastianZ !
