### ISSUE TITLE
Remove some endpoints from among the disallowed within robots.txt

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#1220]
# User story
As a developer, I want to ensure that MDN documents appear high in the Google search results, so that I have access to the best documentation.

We want to remove some URL's, like the `/*$edit` and `/*$translate` endpoints, from among the disallowed within `robots.txt`, so that they no longer appear as warnings in the [`Coverage > Indexed, though blocked by robots.txt` dashboard](https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fdeveloper.mozilla.org%2F&item_key=CAMYBCAD&hl=en).

See https://bugzilla.mozilla.org/show_bug.cgi?id=1518482 for reference

For example, the following endpoints should be removed from among the disallowed within `robots.txt`:
- `/*$edit`
- `/*$translate`
- `/*docs/tag*`
- `/*$history`
- `/<locale>/payments/recurring/management` (but needs robots `meta` tag of `<meta name="robots" content="noindex, nofollow">` first!)

# Acceptance criteria
The number of warnings within the [`Coverage > Indexed, though blocked by robots.txt` dashboard](https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fdeveloper.mozilla.org%2F&item_key=CAMYBCAD&hl=en) either drops to zero or to a minimal level.

# Tasks
- [ ] create list of unique Kuma endpoints contained within [`Coverage > Indexed, though blocked by robots.txt` dashboard](https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fdeveloper.mozilla.org%2F&item_key=CAMYBCAD&hl=en)
- [ ] ensure that each of the endpoints returns a robots `meta` tag of `<meta name="robots" content="noindex, nofollow">`
- [ ] remove each of the endpoints from among the disallowed in `robots.txt`

**Comment by escattone** [comment]
I downloaded the URL's that Google provided at the [`Coverage > Indexed, though blocked by robots.txt` dashboard](https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fdeveloper.mozilla.org%2F&item_key=CAMYBCAD&hl=en) (1000 of them, a sample of the total), and found the following unique Kuma endpoints:

- `/*$edit` -- already returns a robots `meta` tag of `<meta name="robots" content="noindex, nofollow">`
- `/*$translate` -- already returns a robots `meta` tag of `<meta name="robots" content="noindex, nofollow">`
- `/*docs/tag*` -- already returns a robots `meta` tag of `<meta name="robots" content="noindex, nofollow">`
- `/*$history` -- already returns a robots `meta` tag of `<meta name="robots" content="noindex, nofollow">`
- `/*$json` -- already returns `X-Robots-Tag: noindex` header
- `<locale>/docs/feeds/atom/revisions` -- does NOT currently return a `X-Robots-Tag: noindex` header
- `<locale>/docs/feeds/atom/l10n-updates` -- does NOT currently return a `X-Robots-Tag: noindex` header
- `/<locale>/payments/recurring/management` -- does NOT currently return a robots `meta` tag of `<meta name="robots" content="noindex, nofollow">`!

Some of these endpoints are costly to very costly, like `/*docs/tag*`, `/*$history`, `<locale>/docs/feeds/atom/revisions`, and `<locale>/docs/feeds/atom/l10n-updates`, so I'm uncomfortable about allowing them to be crawled (removing them from among the disallowed paths in `robots.txt`). Is there no alternative?

**Comment by escattone** [comment]
@atopal, @Elchi3, and I discussed this further in a video meeting, and decided to limit our first step down this path to the least costly but most frequently indexed endpoints:
- `/*$edit`
- `/*$translate`
and open a bug to consider removing the `<locale>/docs/feeds` family of endpoints.

**Comment by escattone** [comment]
Yesterday, I opened [bug 1538032 (Consider removing one or more of the "feeds" family of endpoints)](https://bugzilla.mozilla.org/show_bug.cgi?id=1538032).

**Comment by atopal** [comment]
Looking at a sample, that should take care of about 80% of the errors.
<img width="758" alt="https___developer_mozilla_org__Index_Coverage_Drilldown_2019-03-23_-_Google_Sheets" src="https://user-images.githubusercontent.com/557852/54869966-72583400-4da0-11e9-88bd-af8f9f359a3f.png">

Looks like we should still do something about the tag pages though.

**Comment by atopal** [comment]
That said, I have no idea how Search Console selects the 1000 URLs that are presented as examples. Could be that the proportions of the sample are wildly different from the actual numbers. I'll take another look after these changes have landed.

**Comment by atopal** [comment]
<img width="705" alt="https___developer_mozilla_org__Index_Coverage_Drilldown_2019-04-03_-_Google_Sheets" src="https://user-images.githubusercontent.com/557852/55498589-dbd60f00-55f8-11e9-9c66-d7f674e212fe.png">

This is the latest sample. EDIT wasn't actually as uniform as it seemed. It looks like a good chunk are to /users/github/login/ and /users/signin

Can we remove /users/ from robots.txt?
