### ISSUE TITLE
SVG: Add example on top of medium priority attribute pages [7/7]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#123]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/contentScriptType
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/contentStyleType
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:lang
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-interpolation
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-interpolation-filters
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-profile
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-rendering
