### ISSUE TITLE
Grizzly: Add Django model and register with admin

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1240]
# User story

Blocks EPIC - https://github.com/mdn/sprints/issues/1130

As a product owner I want to be able to add, remove, and update CTA banners used across MDN Web Docs from the current Django admin UI.

# Tasks

- [x] Create model with fields as described [here](https://github.com/mdn/sprints/issues/1130#issue-416109816) as well as the additional field detailed [here](https://github.com/mdn/sprints/issues/1130#issuecomment-469325659)
- [x] Register new model with Django admin
- [x] Ensure fields are displayed using the appropriate types - [see here for example](https://github.com/mdn/sprints/issues/1130#issue-416109816)

# Acceptance criteria

- [x] Django model exists for all fields
- [x] Base Django admin views are available for the above model fields

Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1538723
