### ISSUE TITLE
SVG: Add example on top of medium priority API pages [1/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#125]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateColorElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateMotionElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateTransformElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGCursorElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGDefsElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGForeignObjectElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGGradientElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGLinearGradientElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGRadialGradientElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMarkerElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGScriptElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSetElement
