### ISSUE TITLE
SVG: Update medium priority API pages [2/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#126]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAngle
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGLength
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGLengthList
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMatrix
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGNumber
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGNumberList
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGPoint
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGPointList
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGPreserveAspectRatio
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGStringList
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTransform
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTransformList
