### ISSUE TITLE
SVG: Update low priority element pages [1/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#128]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, adding a better attributes overview)

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/cursor
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hatch
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hatchpath
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mesh
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/meshgradient
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/meshpatch
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/meshrow
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/metadata
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/set
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/view

**Comment by SebastianZ** [comment]
The hatch and mesh related elements got removed from the SVG 2 spec. (and deferred to a future specification). So, I guess, they should be removed from the list.

Sebastian
