### ISSUE TITLE
SVG: Add example on top of low priority element pages [1/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#129]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/cursor
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hatch
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hatchpath
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mesh
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/meshgradient
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/meshpatch
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/meshrow
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/metadata
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/set
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/view
