### ISSUE TITLE
Grizzly: Add support for waffle and url based segmentation 

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1296]
# User story

As a product owner, I need to be able to control the visibility of a banner by either associating it with a waffle flag, a specific section of MDN Web Docs(via a URL pattern), or both.

# Acceptance criteria

- [ ] Banner can be associated with a Waffle flag
- [ ] Banner can be associated with a URL pattern (section of MDN Web Docs)
- [ ] Banner can be associated with both of the above

# Tasks

1. - [ ] Add waffle flag as an optional field on the `Banner` model and admin
2. - [ ] Add optional URL pattern field to `Banner` model and admin (see https://github.com/ubernostrum/django-soapbox/blob/master/soapbox/models.py#L63 for an example of possible implementation)
3. - [ ] Add optional `is_global` option to `Banner` model and admin (see https://github.com/ubernostrum/django-soapbox/blob/master/soapbox/models.py#L55 for an example of possible implementation)
3. - [ ] Update front-end code to only include banners if its associated waffle flag is active (context processor)
4. - [ ] Update front end code to only include banners that are global or which has a URL pattern that matches the current URL
