### ISSUE TITLE
SVG: Add example on top of low priority element pages [2/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#131]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/altGlyphDef
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/altGlyphItem
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/color-profile
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/discard
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font-face
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font-face-format
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font-face-name
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font-face-src
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/font-face-uri
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/glyph
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/glyphRef
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/hkern
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/missing-glyph
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/tref
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/vkern
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/solidcolor
