### ISSUE TITLE
WebRTC: Write article "Commonly useful WebRTC statisitics"

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#1317]
Write up a guide article covering the "mandatory to implement" statistics for WebRTC. Since these are mandatory because of their general usefulness, let's document them that way.

These stats are listed here: https://w3c.github.io/webrtc-pc/#mandatory-to-implement-stats

This should be either included in or linked from https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_Statistics_API

## Tasks
- [ ] Introduction; briefly explain what makes these stats important/useful
- [ ] List of the stats, broken down by `RTCStatsType`
- [ ] Example?
- [ ] Specifications: https://w3c.github.io/webrtc-pc/#mandatory-to-implement-stats
- [ ] Browser compatibility - can we create a list for each of the properties in one table?

## Acceptance criteria
- [ ] Article is written
- [ ] List of stats is complete and matches the spec
- [ ] Submitted to jib for review
