### ISSUE TITLE
SVG: Update low priority attributes pages [1/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#132]
**Task**
Update or create content to reflect SVG2 changes
Update or create page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/lang
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseProfile
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/version
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewTarget
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/zoomAndPan
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/target
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/media

**Comment by SebastianZ** [comment]
`baseProfile` already got documented by me.

Sebastian
