### ISSUE TITLE
SVG: Add example on top of low priority attribute pages [1/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#133]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/lang
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/baseProfile
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/version
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewTarget
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/zoomAndPan
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/target
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/media
