### ISSUE TITLE
[P1] Sort out Firefox 67 rel notes / other release content (CHRIS)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#1339]
# User story
As a developer, I want to read release notes on the new features available in Firefox 67, so I can find out what I can use in my work.

# Acceptance criteria
- [x] Firefox 67 release notes are updated per DDNs and DDCs.
- [x] Experimental Features page is updated per above.
- [x] platform-status is updated accordingly.
- [x] Fx 67 Tweets are drafted for Danielle.

# Tasks
1. - [x] Run bugzilla query to bring up added Firefox 67 features marked with dev-doc-needed and dev-doc-complete keywords.
2. - [x] Make sure all these features are recorded on the Firefox 67 release notes.
3. - [x] Update Experimental Features page accordingly
4. - [x] Give Fx 67 rel notes a final copy edit
4. - [x] Update platform-status accordingly
5. - [x] Write Fx 67 tweets for Danielle

See also the relevant roadmap entry: https://trello.com/c/H4Ci5VQz/200-firefox-67-release-notes

**Comment by chrisdavidmills** [comment]
Tweets for Danielle:

CSS

* The revert keyword has been implemented in Firefox 67: https://developer.mozilla.org/en-US/docs/Web/CSS/revert
* In Firefox 67, The break-word value of the word-break property is now supported: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
* The prefers-color-scheme media feature has bee implemented in Firefox 67 — https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
    In Firefox 67, custom cursors of greater than 32px in size are now disallowed, to mitigate potential malware uses of large cursors. See https://bugzilla.mozilla.org/show_bug.cgi?id=1445844 for more details.

JS

* String.prototype.matchAll is enabled by default in Firefox 67 — https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll
* Firefox 67 sees support for the dynamic module import() proposal available by default — https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports
* The hashbang grammar proposal is now implemented in Firefox 67 — https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#The_Hashbang_Grammar

APIs

* InputEvent.data and InputEvent.dataTransfer have been implemented in Firefox 67 — https://developer.mozilla.org/en-US/docs/Web/API/InputEvent#Properties
* Firefox 67 includes the The insertFromPasteAsQuotation InputEvent.inputType value — https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/inputType
* The MediaDeviceInfo.groupId property is now available in Firefox 67 — https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/groupId 
* Firefox 67 includes the RTCIceCandidate.usernameFragment property — https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate/usernameFragment
* On Firefox 67, the EXT_float_blend WebGL extension has been enabled by default; see https://developer.mozilla.org/en-US/docs/Web/API/EXT_float_blend
* In Firefox 67, a number of touch event-related features have been disabled on desktop to improve web compatibility on touch screen laptops; see https://bugzilla.mozilla.org/show_bug.cgi?id=1412485 for more.

Security

* The Notifications API (https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) is only available in a secure context from Firefox 67 onwards.

**Comment by chrisdavidmills** [comment]
I have left this in review/test as a reminder to me to look at the rel notes again once we are near the end to see if anythign else has been added that needs looking at.
