### ISSUE TITLE
SVG: Update low priority attribute pages [2/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#134]
**Task**
Update or create content to reflect SVG2 changes
Update or create page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/externalResourcesRequired
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/requiredExtensions
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/requiredFeatures
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/systemLanguage
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/solid-color
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/solid-opacity
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/white-space
