### ISSUE TITLE
SVG: Add example on top of low priority attribute pages [2/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#135]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/externalResourcesRequired
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/requiredExtensions
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/requiredFeatures
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/systemLanguage
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/solid-color
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/solid-opacity
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/white-space
