### ISSUE TITLE
Upgrade to Elasticsearch 6.x

### ISSUE THREAD

**Issue by peterbe** [mdn/sprints#1353]
# User story
As a developer I don't want to have to worry about the impending doom of Elasticsearch 5.x going away. 

# References

[bug 1498931](https://bugzilla.mozilla.org/show_bug.cgi?id=1498931)

# Acceptance criteria

* That the `docker-compose` you use for local dev uses Elasticsearch 6.x
* That we have plan to migrate our instance of elastic.co SAAS (ready to switch env var values and run the reindex command)
* That we run Elasticsearch 6.x in production

# Tasks

- [x] [Change our code to use Elasticsearch 6.x in docker-compose (including CI) and elasticsearch-dsl](https://bugzilla.mozilla.org/show_bug.cgi?id=1544482)
- [x] [Deploy, created instance on Elastic.co, change ES_URLS secrets, run reindex on **Stage**](https://bugzilla.mozilla.org/show_bug.cgi?id=1545211)
- [x] [Deploy, created instance on Elastic.co, change ES_URLS secrets, run reindex on **Prod**](https://bugzilla.mozilla.org/show_bug.cgi?id=1545211)
- [x] Close the [tracker bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1498931)

**Comment by escattone** [comment]
With the production push and re-creation of the search index on prod today, this is complete. I have also closed the bug tracker.
