### ISSUE TITLE
SVG: Update low priority attribute pages [3/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#136]
**Task**
Update or create content to reflect SVG2 changes
Update or create page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/amplitude
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/exponent
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/intercept
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/offset
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/tableValues
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/by
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/keyPoints
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/origin
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/method
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/spacing
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/startOffset
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/orient
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/spreadMethod
