### ISSUE TITLE
SVG: Update low priority attribute pages [4/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#137]
**Task**
Update or create content to reflect SVG2 changes
Update or create page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/accent-height
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/ascent
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overline-position
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overline-thickness
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/strikethrough-position
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/strikethrough-thickness
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/underline-position
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/underline-thickness
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/local
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:show
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:title
