### ISSUE TITLE
SVG: Add example on top of low priority attribute pages [3/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#138]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/amplitude
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/exponent
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/intercept
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/offset
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/tableValues
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/by
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/keyPoints
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/origin
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/method
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/spacing
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/startOffset
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/orient
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/spreadMethod
