### ISSUE TITLE
SVG: Add example on top of low priority attribute pages [4/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#139]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/accent-height
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/ascent
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overline-position
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overline-thickness
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/strikethrough-position
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/strikethrough-thickness
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/underline-position
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/underline-thickness
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/local
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:show
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:title
