### ISSUE TITLE
SVG: Update low priority API pages [1/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#140]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern MDN API layout pages.

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedAngle
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedBoolean
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedEnumeration
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedInteger
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedLength
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedLengthList
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedNumber
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedNumberList
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedRect
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGExternalResourcesRequired
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGRenderingIntent
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGStylable
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTests
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTransformable
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGUnitTypes
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGURIReference
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGZoomAndPan
