### ISSUE TITLE
KR: Roll out free membership accounts

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#1417]
# Key Result 
Roll out free membership accounts

# Acceptance Criteria 
- [ ] Streamlined user first-experience shipped
- [ ] Automated account managment
- [ ] Google Auth integration shipped
- [ ] User flow instrumented
