### ISSUE TITLE
Prepare prod for beta.developer.mozilla.org

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#1448]
# User story
As a developer, I want to prepare production to handle the separate `beta.developer.mozilla.org` and `wiki.developer.mozilla.org` domains so we're ready when we make those domains public.

# Acceptance criteria
- [x] Site test checklist (as defined in https://github.com/mdn/sprints/issues/1205) passes for all of the domains: `developer.mozilla..org`, `beta.developer.mozilla.org`, and `wiki.developer.mozilla.org`.

# Tasks
- [x] New SSL cert for production CDN
- [x] (Maybe) New SSL cert for production ELB
- [x] (Maybe) New SSL cert for stage ELB
- [x] Create a new behavior for the production CDN to handle requests to `/api/v1/doc/*`
- [x] Create a new behavior for the production CDN to handle requests to `/api/v1/whoami/*`
- [x] Add the prod S3 bucket as an origin on the prod CDN
- [x] Populate the prod S3 bucket with the document API JSON files derived from the prod DB (it's not currently populated)
- [x] Create DNS CNAMES for `beta.developer.mozilla.org` and `wiki.developer.mozilla.org` (pointing to the prod CDN and the prod ELB respectively)
- [x] Create DNS CNAMES for `beta.developer.allizom.org` and `wiki.developer.allizom.org` (pointing to the stage CDN and the stage ELB respectively)
- [x] Run through the test checklist (as defined in https://github.com/mdn/sprints/issues/1205) for all of the domains: `developer.mozilla..org`, `beta.developer.mozilla.org`, and `wiki.developer.mozilla.org` (**this task depends on the prior successful completion of https://github.com/mdn/sprints/issues/1205 -- the details are [here](https://github.com/mdn/sprints/issues/1205#issuecomment-481456076)**)

**Comment by escattone** [comment]
I did the following today:
- created new, validated SSL certs for the stage, prod, and standby ELB's
- attached the new SSL certs to their respective ELB's
- deleted all of the old, unused SSL certs for stage, prod, and standby
- with @limed's help, updated the DNS entries for `wiki.developer.allizom.org` and `wiki.developer.mozilla.org` to point to their respective ELB's (bypassing their respective CDN's)
- requested a new SSL cert for the prod CDN (it is still validating at this time)

**Comment by escattone** [comment]
- attached the new SSL cert to the prod CDN
- added `wiki.developer.mozilla.org` and `beta.developer.mozilla.org` to the prod CDN's list of alternate domain names (`CNAME`'s)
- added the prod API S3 bucket as an origin on the prod CDN
- created a new behavior for the production CDN to handle requests to `/api/v1/doc/*` from S3
- created a new behavior for the production CDN to handle requests to `/api/v1/whoami/*` from the ELB

**Comment by escattone** [comment]
I published all of the production documents to the production S3 bucket. Well, all except one. There is this one evil document (`/zh-CN/docs/Archive/Web/LiveConnect`) which crashes the celery worker when it is run. When I tried to publish it manually it crashed Python as well. Also, when I request the document like https://developer.mozilla.org/zh-CN/docs/Archive/Web/LiveConnect, I wait and wait and wait (>30 seconds) but no response. Something is rotten with that document.

**Comment by jmswisher** [comment]
Given that it's under /Archive, it's probably not a big deal to delete that document. It would be great to figure out what's wrong with it, but not if it turns into a rabbit hole.

**Comment by escattone** [comment]
I also re-published all of the stage documents to the stage S3 bucket. I did this because https://github.com/mozilla/kuma/pull/5402 added an `enSlug` attribute to the JSON that the document API returns.

**Comment by escattone** [comment]
I'm going to document the results of my testing against prod.

### Home page

Load https://developer.mozilla.org/en-US and https://wiki.developer.mozilla.org/en-US

* [x] Loads without errors
* [x] Does not have banner "MDN is currently in read-only maintenance mode. Learn more."
* [x] Has "Sign in" or "View Profile" at the top
* [x] Has entries for the Hacks Blog

Load https://beta.developer.mozilla.org/en-US

* [x] Loads without errors
* [x] Does not have banner "MDN is currently in read-only maintenance mode. Learn more."
* **Failed** Missing header as well as MDN contribution banner (this is a known issue)
* [x] Has entries for the Hacks Blog

### Article page

Load https://developer.mozilla.org/en-US/docs/Web/HTML, https://wiki.developer.mozilla.org/en-US/docs/Web/HTML, and https://beta.developer.mozilla.org/en-US/docs/Web/HTML

* [x] Loads without errors
* [x] No Maintenance Mode banner
* [x] Has "Sign in" or "View Profile" at the top

**Comment by escattone** [comment]
### Functional and Headless Tests

The Firefox and Chrome functional tests as well as the headless tests pass when run against stage (https://developer.allizom.org) from Jenkins.

* [x] Functional tests pass
* [x] Headless tests pass

The Firefox and Chrome functional tests as well as the headless tests pass when run against https://wiki.developer.mozilla.org.

* [ ] Functional tests pass
* [x] Headless tests pass

**Comment by escattone** [comment]
Submitted https://github.com/mozilla/kuma/pull/5426 (minor tweaks) to address a testing issue with the headless tests when run against the production or `wiki` domains.

**Comment by escattone** [comment]
The Firefox and Chrome functional tests as well as the headless tests pass when run against https://developer.mozilla.org.

* [x] Functional tests pass
* [x] Headless tests pass

**Comment by escattone** [comment]
### Full Manual Tests

#### Content tests

These URLs should have similar results for anonymous or logged-in users:

* [ ] https://mdn.mozillademos.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color - 200, sample as a stand-alone page
* [ ] https://mdn.mozillademos.org/files/12984/web-font-example.png - 200, PNG of some "Hipster ipsum" text
* [ ] https://developer.mozilla.org/@api/deki/files/3613/=hut.jpg - 200, image of a hat
* [ ] https://wiki.developer.mozilla.org/@api/deki/files/3613/=hut.jpg - 200, image of a hat
* [ ] https://beta.developer.mozilla.org/@api/deki/files/3613/=hut.jpg - **Should we drop support for this legacy endpoint and 404, or redirect to https://mdn.mozillademos.org/files/2767/hut.jpg?**
* [ ] https://developer.mozilla.org/contribute.json - 200, project info
* [ ] https://wiki.developer.mozilla.org/contribute.json - 200, project info
* [ ] https://beta.developer.mozilla.org/contribute.json - 200, project info
* [ ] https://developer.mozilla.org/diagrams/workflow/workflow.svg - 200, SVG with images
* [ ] https://wiki.developer.mozilla.org/diagrams/workflow/workflow.svg - 200, SVG with images
* [ ] https://beta.developer.mozilla.org/diagrams/workflow/workflow.svg - **404 - Drop support for legacy files**
* [ ] https://developer.mozilla.org/en-US/Firefox/Releases - 200, Firefox logo, list of releases (zoned URL)
* [ ] https://wiki.developer.mozilla.org/en-US/Firefox/Releases - 200, Firefox logo, list of releases (zoned URL)
* [ ] https://beta.developer.mozilla.org/en-US/Firefox/Releases - 200, Firefox logo, list of releases (zoned URL)
* [ ] https://developer.mozilla.org/en-US/dashboards/macros - 200, list of macros and page counts
* [ ] https://wiki.developer.mozilla.org/en-US/dashboards/macros - 200, list of macros and page counts
* [ ] https://beta.developer.mozilla.org/en-US/dashboards/macros - 404
* [ ] https://developer.mozilla.org/en-US/dashboards/revisions - 200, list of recent changes (when signed-in)
* [ ] https://wikideveloper.mozilla.org/en-US/dashboards/revisions - 200, list of recent changes (when signed-in)
* [ ] https://beta.developer.mozilla.org/en-US/dashboards/revisions - 404
* [ ] https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Color - 200, with sample as iframe
* [ ] https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Color - 200, with sample as iframe
* [ ] https://beta.developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Color - 200, with sample as iframe
* [ ] https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$toc - 200, HTML table of contents
* [ ] https://wiki.developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$toc - 200, HTML table of contents
* [ ] https://beta.developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$toc - 404
* [ ] https://developer.mozilla.org/en-US/docs/Web/HTML$children - 200, JSON list of child pages
* [ ] https://wiki.developer.mozilla.org/en-US/docs/Web/HTML$children - 200, JSON list of child pages
* [ ] https://beta.developer.mozilla.org/en-US/docs/Web/HTML$children - 404
* [ ] https://developer.mozilla.org/en-US/docs/Web/HTML$compare?locale=en-US&to=1299417&from=1293895 - 200, compares revisions
* [ ] https://wiki.developer.mozilla.org/en-US/docs/Web/HTML$compare?locale=en-US&to=1299417&from=1293895 - 200, compares revisions
* [ ] https://beta.developer.mozilla.org/en-US/docs/Web/HTML$compare?locale=en-US&to=1299417&from=1293895 - 404
* [ ] https://developer.mozilla.org/en-US/docs/Web/HTML$history - 200, list of revisions
* [ ] https://wiki.developer.mozilla.org/en-US/docs/Web/HTML$history - 200, list of revisions
* [ ] https://beta.developer.mozilla.org/en-US/docs/Web/HTML$history - 404
* [ ] https://developer.mozilla.org/en-US/docs/Web/HTML$json - 200, JSON of page metadata
* [ ] https://wiki.developer.mozilla.org/en-US/docs/Web/HTML$json - 200, JSON of page metadata
* [ ] https://beta.developer.mozilla.org/en-US/docs/Web/HTML$json - 404
* [ ] https://developer.mozilla.org/en-US/docs/Web/HTML$revision/1293895 - 200, historical revision
* [ ] https://wiki.developer.mozilla.org/en-US/docs/Web/HTML$revision/1293895 - 200, historical revision
* [ ] https://beta.developer.mozilla.org/en-US/docs/Web/HTML$revision/1293895 - 404
* [ ] https://developer.mozilla.org/en-US/docs/all - 200, paginated list of docs
* [ ] https://wiki.developer.mozilla.org/en-US/docs/all - 200, paginated list of docs
* [ ] https://beta.developer.mozilla.org/en-US/docs/all - 404
* [ ] https://developer.mozilla.org/en-US/docs/ckeditor_config.js - 200, JavaScript
* [ ] https://wiki.developer.mozilla.org/en-US/docs/ckeditor_config.js - 200, JavaScript
* [ ] https://beta.developer.mozilla.org/en-US/docs/ckeditor_config.js - 404
* [ ] https://developer.mozilla.org/en-US/docs/feeds/atom/files/ - 200, Atom feed of changed files
* [ ] https://wiki.developer.mozilla.org/en-US/docs/feeds/atom/files/ - 200, Atom feed of changed files
* [ ] https://beta.developer.mozilla.org/en-US/docs/feeds/atom/files/ - 404
* [ ] https://developer.mozilla.org/en-US/docs/feeds/rss/all/ - 200, RSS feed of new pages
* [ ] https://wiki.developer.mozilla.org/en-US/docs/feeds/rss/all/ - 200, RSS feed of new pages
* [ ] https://beta.developer.mozilla.org/en-US/docs/feeds/rss/all/ - 404
* [ ] https://developer.mozilla.org/en-US/docs/feeds/rss/needs-review/ - 200, RSS feed of pages needing review
* [ ] https://wiki.developer.mozilla.org/en-US/docs/feeds/rss/needs-review/ - 200, RSS feed of pages needing review
* [ ] https://beta.developer.mozilla.org/en-US/docs/feeds/rss/needs-review/ - 404
* [ ] https://developer.mozilla.org/en-US/docs/feeds/rss/needs-review/technical - 200, RSS feed of pages needing technical review
* [ ] https://wiki.developer.mozilla.org/en-US/docs/feeds/rss/needs-review/technical - 200, RSS feed of pages needing technical review
* [ ] https://beta.developer.mozilla.org/en-US/docs/feeds/rss/needs-review/technical - 404
* [ ] https://developer.mozilla.org/en-US/docs/feeds/rss/revisions - 200, RSS feed of changes
* [ ] https://wiki.developer.mozilla.org/en-US/docs/feeds/rss/revisions - 200, RSS feed of changes
* [ ] https://beta.developer.mozilla.org/en-US/docs/feeds/rss/revisions - 404
* [ ] https://developer.mozilla.org/en-US/docs/feeds/rss/tag/CSS - 200, RSS feed of pages with CSS tag
* [ ] https://wiki.developer.mozilla.org/en-US/docs/feeds/rss/tag/CSS - 200, RSS feed of pages with CSS tag
* [ ] https://beta.developer.mozilla.org/en-US/docs/feeds/rss/tag/CSS - 404
* [ ] https://developer.mozilla.org/en-US/docs/needs-review/editorial - 200, paginated list of documents
* [ ] https://wiki.developer.mozilla.org/en-US/docs/needs-review/editorial - 200, paginated list of documents
* [ ] https://beta.developer.mozilla.org/en-US/docs/needs-review/editorial - 404
* [ ] https://developer.mozilla.org/en-US/docs/tag/ARIA - 200, list of documents
* [ ] https://wiki.developer.mozilla.org/en-US/docs/tag/ARIA - 200, list of documents
* [ ] https://beta.developer.mozilla.org/en-US/docs/tag/ARIA - 404
* [ ] https://developer.mozilla.org/en-US/docs/tags - 200, paginated list of tags
* [ ] https://wiki.developer.mozilla.org/en-US/docs/tags - 200, paginated list of tags
* [ ] https://beta.developer.mozilla.org/en-US/docs/tags - 404
* [ ] https://developer.mozilla.org/en-US/docs/top-level - 200, paginated list of documents
* [ ] https://wiki.developer.mozilla.org/en-US/docs/top-level - 200, paginated list of documents
* [ ] https://beta.developer.mozilla.org/en-US/docs/top-level - 404
* [ ] https://developer.mozilla.org/en-US/docs/with-errors - 200, (empty?) paginated list of documents
* [ ] https://wiki.developer.mozilla.org/en-US/docs/with-errors - 200, (empty?) paginated list of documents
* [ ] https://beta.developer.mozilla.org/en-US/docs/with-errors - 404
* [ ] https://developer.mozilla.org/en-US/docs/without-parent - 200, paginated list of documents
* [ ] https://wiki.developer.mozilla.org/en-US/docs/without-parent - 200, paginated list of documents
* [ ] https://beta.developer.mozilla.org/en-US/docs/without-parent - 404
* [ ] https://developer.mozilla.org/en-US/profiles/sheppy - 200, Sheppy's profile
* [ ] https://wiki.developer.mozilla.org/en-US/profiles/sheppy - 200, Sheppy's profile
* [ ] https://beta.developer.mozilla.org/en-US/profiles/sheppy - 404
* [ ] https://developer.mozilla.org/en-US/promote/ - 200, Promote MDN with 4 buttons
* [ ] https://wiki.developer.mozilla.org/en-US/promote/ - 200, Promote MDN with 4 buttons
* [ ] https://beta.developer.mozilla.org/en-US/promote/ - 404
* [ ] https://developer.mozilla.org/en-US/search - 200, Search results
* [ ] https://wiki.developer.mozilla.org/en-US/search - 200, Search results
* [ ] https://beta.developer.mozilla.org/en-US/search - 404
* [ ] https://developer.mozilla.org/fellowship/ - 301 to archive of 2015 MDN Fellowship Program
* [ ] https://wiki.developer.mozilla.org/fellowship/ - 301 to archive of 2015 MDN Fellowship Program
* [ ] https://beta.developer.mozilla.org/fellowship/ - 301 to archive of 2015 MDN Fellowship Program
* [ ] https://developer.mozilla.org/files/12984/web-font-example.png - Redirects to https://mdn.mozillademos.org
* [ ] https://wiki.developer.mozilla.org/files/12984/web-font-example.png - Redirects to https://mdn.mozillademos.org
* [ ] https://beta.developer.mozilla.org/files/12984/web-font-example.png - Redirects to https://mdn.mozillademos.org
* [ ] https://developer.mozilla.org/fr/docs/feeds/rss/l10n-updates/ - 200, RSS feed of out-of-date pages
* [ ] https://wiki.developer.mozilla.org/fr/docs/feeds/rss/l10n-updates/ - 200, RSS feed of out-of-date pages
* [ ] https://beta.developer.mozilla.org/fr/docs/feeds/rss/l10n-updates/ - 404
* [ ] https://developer.mozilla.org/fr/docs/localization-tag/inprogress - 200, paginated list of documents
* [ ] https://wiki.developer.mozilla.org/fr/docs/localization-tag/inprogress - 200, paginated list of documents
* [ ] https://beta.developer.mozilla.org/fr/docs/localization-tag/inprogress - 404
* [ ] https://developer.mozilla.org/humans.txt - 200, list of GitHub usernames
* [ ] https://wiki.developer.mozilla.org/humans.txt - 200, list of GitHub usernames
* [ ] https://beta.developer.mozilla.org/humans.txt - 200, list of GitHub usernames
* [ ] https://developer.mozilla.org/media/kumascript-revision.txt - 200, git commit hash for kumascript
* [ ] https://wiki.developer.mozilla.org/media/kumascript-revision.txt - 200, git commit hash for kumascript
* [ ] https://beta.developer.mozilla.org/media/kumascript-revision.txt - 200, git commit hash for kumascript
* [ ] https://developer.mozilla.org/media/revision.txt - 200, git commit hash for kuma
* [ ] https://wiki.developer.mozilla.org/media/revision.txt - 200, git commit hash for kuma
* [ ] https://beta.developer.mozilla.org/media/revision.txt - 200, git commit hash for kuma
* [ ] https://developer.mozilla.org/miel  - 500 Internal Server Error
* [ ] https://wiki.developer.mozilla.org/miel  - 500 Internal Server Error
* [ ] https://beta.developer.mozilla.org/miel  - 404
* [ ] https://developer.mozilla.org/presentations/microsummaries/index.html - 200, 2006 OSCON presentation
* [ ] https://wiki.developer.mozilla.org/presentations/microsummaries/index.html - 200, 2006 OSCON presentation
* [ ] https://beta.developer.mozilla.org/presentations/microsummaries/index.html - **404 - Drop support for legacy files**
* [ ] https://developer.mozilla.org/robots.txt - 200, robots disallow list
* [ ] https://wiki.developer.mozilla.org/robots.txt - 200, robots disallow list
* [ ] https://beta.developer.mozilla.org/robots.txt - 200, robots disallow list
* [ ] https://developer.mozilla.org/samples/webgl/sample3 - 200, Shows WebGL demo
* [ ] https://wiki.developer.mozilla.org/samples/webgl/sample3 - 200, Shows WebGL demo
* [ ] https://beta.developer.mozilla.org/samples/webgl/sample3 - 200, Shows WebGL demo
* [ ] https://developer.mozilla.org/sitemap.xml - 200, list of sitemaps
* [ ] https://wiki.developer.mozilla.org/sitemap.xml - **I think this should be an empty sitemap**
* [ ] https://beta.developer.mozilla.org/sitemap.xml - **I think this should be an empty sitemap rather than a 404**
* [ ] https://developer.mozilla.org/sitemaps/en-US/sitemap.xml - 200, list of en-US pages
* [ ] https://wiki.developer.mozilla.org/sitemaps/en-US/sitemap.xml - 404
* [ ] https://beta.developer.mozilla.org/sitemaps/en-US/sitemap.xml - 404

#### Anonymous tests

Test these URLs as an anonymous user:

* [ ] https://developer.mozilla.org/admin/users/user/1/ - 302 redirect to the Admin login page, asking for a username and password.
* [ ] https://wiki.developer.mozilla.org/admin/users/user/1/ - 302 redirect to the Admin login page, asking for a username and password.
* [ ] https://beta.developer.mozilla.org/admin/users/user/1/ - 404
* [ ] https://developer.mozilla.org/en-US/dashboards/spam - 302 redirect to user sign-in page, asking to Sign In with GitHub
* [ ] https://wiki.developer.mozilla.org/en-US/dashboards/spam - 302 redirect to user sign-in page, asking to Sign In with GitHub
* [ ] https://beta.developer.mozilla.org/en-US/dashboards/spam - 404
* [ ] https://developer.mozilla.org/en-US/docs/Web/HTML$edit - 302 redirect to user sign-in page
* [ ] https://wiki.developer.mozilla.org/en-US/docs/Web/HTML$edit - 302 redirect to user sign-in page
* [ ] https://beta.developer.mozilla.org/en-US/docs/Web/HTML$edit - 404
* [ ] https://developer.mozilla.org/en-US/docs/Web/HTML$translate - 302 redirect to user sign-in page
* [ ] https://wiki.developer.mozilla.org/en-US/docs/Web/HTML$translate - 302 redirect to user sign-in page
* [ ] https://beta.developer.mozilla.org/en-US/docs/Web/HTML$translate - 404
* [ ] https://developer.mozilla.org/en-US/Firefox/Releases$edit - 302 redirect to user sign-in page
* [ ] https://wiki.developer.mozilla.org/en-US/Firefox/Releases$edit - 302 redirect to user sign-in page
* [ ] https://beta.developer.mozilla.org/en-US/Firefox/Releases$edit - 404
* [ ] https://developer.mozilla.org/en-US/Firefox/Releases$translate - 302 redirect to user sign-in page
* [ ] https://wiki.developer.mozilla.org/en-US/Firefox/Releases$translate - 302 redirect to user sign-in page
* [ ] https://beta.developer.mozilla.org/en-US/Firefox/Releases$translate - 404

#### Regular Account Tests (for https://wiki.developer.mozilla.org)

Some things to try with a regular account, to exercise write functionality:

* [ ] Create a new MDN user account (may require deleting your ``SocialAccount``)
* [ ] Send an account recovery link for an existing MDN user account
* [ ] Update the account profile
* [ ] Add and verify a new email for a profile
* [ ] Create a new page, such as https://wiki.developer.mozilla.org/en-US/docs/User:Ryan10
* [ ] Create a translation of the new page
* [ ] Subscribe to a page, and change it with a different account
* [ ] Update the original page with a KumaScript macro, such as ``{{cssxref("background")}}``.
* [ ] Update the translation of a changed English page
* [ ] Upload an image to the page
* [ ] Add the image to the page content
* [ ] Edit a zoned URL like https://wiki.developer.mozilla.org/en-US/Firefox/Releases
* [ ] Log out

#### Admin Tests (for https://wiki.developer.mozilla.org)

Some things to try with an admin account, to exercise restricted functionality:

* [ ] Move a page
* [ ] Delete a page
* [ ] View https://wiki.developer.mozilla.org/admin/users/user/1/ - 200, first user
* [ ] View https://wiki.developer.mozilla.org/en-US/dashboards/spam - 200, "please wait" or dashboard

**Comment by escattone** [comment]
Test anomalies (none are failures in regard to this effort, but indicate follow-on work):
- The `beta` archive pages are missing the striped warning border. This is something we need to address in the front-end for the `beta` domain archive pages.
- I found one case where a revision created by the `mdnwebdocs-bot` had its `toc_depth` attribute modified from its original value of `4` to `0`, effectively reducing the `$toc` response to an empty one. I'm worried now that this has happened to all revisions modified by the `mdnwebdocs-bot`.

**Comment by escattone** [comment]
The acceptance criteria has been met.
