### ISSUE TITLE
Update to Django 1.10, 1.11

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#145]
# User story
As a developer, I want tests to run under Django 1.8 through 1.11, so that we can continue to integrated testing of 1.11

# References
* [Upgrading Django to a newer version](https://docs.djangoproject.com/en/2.0/howto/upgrade-version/) - advises updating to each version
* [Release Notes](https://docs.djangoproject.com/en/2.0/releases/), including notes for [Django 1.10](https://docs.djangoproject.com/en/2.0/releases/1.10/) and Django 1.11](https://docs.djangoproject.com/en/2.0/releases/1.11/)
* https://github.com/mdn/sprints/issues/15 - Django 1.9 update
* Django 1.10.9 is the last point release in the 1.10.x cycle. 1.11.13 is the current release in the LTS 1.11.x cycle.
* [bug 1401246](https://bugzilla.mozilla.org/show_bug.cgi?id=1401246) - Update to Django 1.11
* [bug 1399639](https://bugzilla.mozilla.org/show_bug.cgi?id=1399639) - Upgrade Kuma dependencies

# Acceptance criteria
- All tests pass on Django 1.8
- All tests pass or xfail (known failures that agreed we won't fix) on 1.9, 1.10, and 1.11
- (If needed) all tests pass on Django 1.11 branch
- Docker images can be created for deployment on Django 1.11

# Tasks
- [x] Modify monkeypatching of form widgets (Django 1.10) @escattone 
- [x] Populate ``ALLOWED_HOSTS`` for tests
- [x] Fix ``AdminEmailHandler``
- [x] Review [1.10 release notes](https://docs.djangoproject.com/en/2.0/releases/1.10/) and point releases (notes at https://github.com/mdn/sprints/issues/146#issuecomment-392933309)
- [x] Review [1.11 release notes](https://docs.djangoproject.com/en/2.0/releases/1.11/) and point releases (notes at https://github.com/mdn/sprints/issues/146#issuecomment-392944983)
- [x] Categorize Django 1.11 failures

**Comment by jwhitlock** [comment]
Changes deployed, running in production, no increase in errors or errors associated with the change.
