### ISSUE TITLE
Lengthen the cache time for the `beta` domain

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#1453]
# User story
As a developer, I want to prepare stage and production to cache the cache-able endpoints within the `beta` domain (primarily the document API and the SSR document pages, but also perhaps the landing page and others) for a lengthy period of time (1 hour rather than 5 minutes).

# Acceptance criteria
- [x] Verify that all cache-able `beta` endpoints on stage and prod are cached for 1 hour rather than 5 minutes

# Tasks
- [x] Increase `shared_cache_control` on all `beta` views from 5 min to 1 hour
- [x] Ensure `contributors` are populated when generating SSR pages for documents (since we're going to be caching the results for a lengthy period of time)

**Comment by peterbe** [comment]
I don't know where else to express this but...
We have a boto3 call that updates S3 with the document JSON data. It would greatly benefit us if that boto3 call is immediately followed by a boto3 call to CloudFront too. ...on the JSON API endpoint. 
Now, when we have that, we could easily deduce what the "web endpoint" would be too. E.g. 
```python
cloudfront = boto3.resource('cloudfront')
cloudfront.invalidate({"endpoint": "api/v1/docs/en-US/Web/CSS"})
cloudfront.invalidate({"endpoint": "docs/en-US/Web/CSS"})
```

I wonder if CloudFront invalidation, although it's not immediate and it's weirdly unpredictable, at least we should work on this before we work on the TTL increase.

**Comment by escattone** [comment]
Confirmed 3600 second (1 hour) caching for the following `beta` endpoints:
- document endpoints via the `cache-control` header (e.g., https://beta.developer.mozilla.org/en-US/docs/Web)
- home page via the `cache-control` header (https://beta.developer.mozilla.org/en-US/)
- the document API endpoints (e.g., https://beta.developer.mozilla.org/api/v1/doc/en-US/Web)(via the TTL setting on the `api/v1/doc/*` behavior on each of the stage and prod CDN's)
- https://beta.developer.mozilla.org/contribute.json via the `cache-control` header
- https://beta.developer.mozilla.org/robots.txt via the `cache-control` header
- https://beta.developer.mozilla.org/favicon.ico via the `cache-control` header
- https://beta.developer.mozilla.org/sitemap.xml via the `cache-control` header
- https://beta.developer.mozilla.org/sitemaps/* via the `cache-control` header
- https://beta.developer.mozilla.org/humans.txt via the `cache-control` header

Confirmed 1 year caching for the following `beta` endpoints:
- https://beta.developer.mozilla.org/*/files/* via the `cache-control` header (these are simple redirects to the attachments domain `mdn.mozillademos.org`)
- https://beta.developer.mozilla.org/*/@api/deki/files/* via the `cache-control` header (these are simple redirects to the attachments domain `mdn.mozillademos.org`)

The following endpoints are never cached:
- https://beta.developer.mozilla.org/api/v1/whoami
- https://beta.developer.mozilla.org/healthz
- https://beta.developer.mozilla.org/readiness
- https://beta.developer.mozilla.org/_kuma_status.json
- https://beta.developer.mozilla.org/media/revision.txt
- https://beta.developer.mozilla.org/media/kumascript-revision.txt

**Comment by escattone** [comment]
See https://github.com/mozilla/kuma/pull/5428
