### ISSUE TITLE
Deploy Django 1.11 to production

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#146]
# User story
As MDN staff, I want to update to Django 1.11, so that we're on a supported release and out of feature freeze.

# References
* [bug 1401246](https://bugzilla.mozilla.org/show_bug.cgi?id=1401246) - Django 1.11 tracking bug

# Acceptance criteria
* Functional tests (selenium and headless) pass in staging
* Manual tests pass in staging
* Developer documentation is still accurate
* Django 1.11 deployed to staging and production
* High-impact bugs are fixed in production

# Tasks
- [x] Check development environment, documentation
- [x] Functional tests pass in staging
- [x] Manual tests pass in staging (https://github.com/mdn/infra/blob/master/apps/mdn/mdn-aws/docs/stage-checklist.md)
- [x] Check crontab tasks
- [x] Check management tasks
- [x] Check logging (https://github.com/mdn/sprints/issues/15#issuecomment-391811435)
- [x] Check redirects with trailing slashes (https://github.com/mdn/sprints/issues/15#issuecomment-391811435)
- [x] Check Chinese localizations (https://docs.djangoproject.com/en/2.0/releases/1.9/#features-removed-in-1-9
- [x] Check setting and removing document tags
- [x] Deploy Django 1.11

**Comment by jwhitlock** [comment]
Stuff from Django 1.9 that could be used immediately once 1.8 is gone:

* The test client has a ``.json()`` method (replacing manual JSON de-serialization) and a ``.force_login`` method (replacing fake passwords for tests)
* [Related set direct assignment](https://docs.djangoproject.com/en/2.0/releases/1.9/#related-set-direct-assignment) may have an impact on document tags (either breaking assignment, or allowing it to be more efficient)
* ``RedirectView.permanent`` now defaults to ``False``

Medium and long--term stuff:
* ``json_dumps_params`` to ``JsonResponse`` could be used to pretty-print some JSON responses
* Use [forms API](https://docs.djangoproject.com/en/2.0/releases/1.9/#forms
) to set field order and widget types, rather than manually laying out forms in Jinja templates
* [``make_aware`` supports is_dst](https://docs.djangoproject.com/en/2.0/releases/1.9/#internationalization), so we may be able to remove custom validation
* [``on_commit`` hook](https://docs.djangoproject.com/en/2.0/releases/1.9/#performing-actions-after-a-transaction-commit), to take actions when a transaction is complete (search indexing around page moves and deletions, replace django-celery-transactions)
* [queryset date functions](https://docs.djangoproject.com/en/2.0/releases/1.9/#models) could move some workloads to database
* Major admin changes may allow for some optimization, such as tuning list queries. Once we're on the Django 1.11 admin, we can also customize stuff, such as removing password login from the Django admin.
* URL namespaces might be useful for us, or may just be useful for 3rd-party library authors.
* [``ModelAdmin.allow_tags`` is deprecated](https://docs.djangoproject.com/en/2.0/releases/1.9/#id1), which is used by soapbox.

**Comment by jwhitlock** [comment]
Short-term stuff from [Django 1.10](https://docs.djangoproject.com/en/2.0/releases/1.10/#):
* Switch to [new-style middleware](https://docs.djangoproject.com/en/2.0/releases/1.10/#new-style-middleware)
* Ensure login / logout still works - several changes were made to [django.contrib.auth](https://docs.djangoproject.com/en/2.0/releases/1.10/#django-contrib-auth).
* [Username is now 150 characters](https://docs.djangoproject.com/en/2.0/releases/1.10/#abstractuser-username-max-length-increased-to-150), may require migration.
* [More logging changes](https://docs.djangoproject.com/en/2.0/releases/1.10/#runserver-output-goes-through-logging), to add to [changes in logging in 1.9](https://docs.djangoproject.com/en/2.0/releases/1.9/#changes-to-the-default-logging-configuration).
* Update our custom ``LocaleMiddlware``, other localization functions, to include Django changes.

Medium- and long-term stuff:
* [Inline JS removed from Django admin(https://docs.djangoproject.com/en/2.0/releases/1.10/#django-contrib-admin)], so a ``Content-Security-Policy`` header could be easier to implement.
* The [File Storage API](https://docs.djangoproject.com/en/2.0/releases/1.10/#django-contrib-auth) looks like it supports non-filesystem storage a bit better, helping with a move to object storage like S3.
* [``prefix_default_language``](https://docs.djangoproject.com/en/2.0/releases/1.10/#internationalization) could allow URLs in English without the ``en-US`` prefix, as somewhat requested in the discussion around [bug 1441672](https://bugzilla.mozilla.org/show_bug.cgi?id=1441672).
* Use new javascript i18n views [``JavaScriptCatalog`` and ``JSONCatalog``](https://docs.djangoproject.com/en/2.0/releases/1.10/#internationalization)?
* [``./manage.py shell --command``](https://docs.djangoproject.com/en/2.0/releases/1.10/#management-commands) could be used instead of piping the command in development instructions.
* Use [``elidable`` and ``atomic``](https://docs.djangoproject.com/en/2.0/releases/1.10/#migrations) as needed in migrations.
* ``User.is_anonymous`` and ``.is_authenticated`` are now [properties](https://docs.djangoproject.com/en/2.0/releases/1.10/#miscellaneous), and other deprecated features that should get warnings.
* Remove ``SessionAuthenticationMiddleware``, which is now the default and does nothing.

**Comment by jwhitlock** [comment]
Short-term stuff from [Django 1.11](https://docs.djangoproject.com/en/2.0/releases/1.11/):

* Check that forms still work after the change to [template-based widget rendering](https://docs.djangoproject.com/en/2.0/releases/1.11/#changes-due-to-the-introduction-of-template-based-widget-rendering).

Medium- and long-term stuff:

* Form rendering is now done with the [template system](https://docs.djangoproject.com/en/2.0/releases/1.11/#template-based-widget-rendering), not in Python. This may make it easier to customize forms in the form class, rather than manually creating forms in Jinja2 templates.
* The built-in Jinja2 backend supports ``context_processors`` option. We should evaluate again if ``django-jinja`` is required.

**Comment by jwhitlock** [comment]
Copied from https://github.com/mdn/infra/blob/master/apps/mdn/mdn-aws/docs/stage-checklist.md

This checklist uses these URLs:

* Base: https://developer.allizom.org
* CDN: https://stage-cdn.mdn.moz.works
* Demo: https://stage-files.mdn.moz.works
* Interactive Examples: https://interactive-examples.mdn.moz.works

# Refreshing staging instance

The staging instance has separate services from the production instance. The
staging database is initialized from an anonymized production database
backup. This database persists between deployments, and is refreshed
infrequently.

*TODO:* Add instructions for refreshing the staging database.

# Manual Sanity Check

## Home page

Load https://developer.allizom.org/en-US

* [ ] Loads without errors
* [ ] Does not have banner "MDN is currently in read-only maintenance mode. Learn more."
* [ ] Has "Sign in" or "View Profile" at the top
* [ ] Has entries for the Hacks Blog

## Article page

Load https://developer.allizom.org/en-US/docs/Web/HTML

* [ ] Loads without errors
* [ ] No Maintenance Mode banner
* [ ] Has "Sign in" or "View Profile" at the top

# Automated Checks

With a Kuma environment,
[run the functional tests](https://kuma.readthedocs.io/en/latest/tests-ui.html),
using a command like:

```
py.test -m "not login" tests/functional tests/redirects --base-url https://developer.allizom.org --driver Chrome --driver-path /path/to/chromedriver
```

Some tests will fail the first time they are run against a server with cold
caches. Some tests are flaky, and will intermittently fail. If a test passes
once in three tries, we consider it a success.

* [ ] Functional tests pass

These check basic site functionality without logging in. It duplicates the Manual Sanity Check.

```
py.test -m "not login" tests/functional tests/redirects --base-url https://developer.allizom.org --driver Chrome --driver-path /path/to/chromedriver
```

# Full Manual Tests

## Content tests

*Note: Many of these are candidates for headless testing*

These URLs should have similar results for anonymous or logged-in users:

* [ ] https://stage-files.mdn.moz.works/en-US/docs/Learn/CSS/Styling_text/Fundamentals$samples/Color - 200, sample as a stand-alone page
* [ ] https://stage-files.mdn.moz.works/files/12984/web-font-example.png - 200, PNG of some "Hipster ipsum" text
* [ ] https://developer.allizom.org/@api/deki/files/3613/=hut.jpg - 200, image of a hat
* [ ] https://developer.allizom.org/contribute.json - 200, project info
* [ ] https://developer.allizom.org/diagrams/workflow/workflow.svg - 200, SVG with images
* [ ] https://developer.allizom.org/en-US/Firefox/Releases - 200, Firefox logo, list of releases (zoned URL)
* [ ] https://developer.allizom.org/en-US/dashboards/macros - 200, list of macros and page counts
* [ ] https://developer.allizom.org/en-US/dashboards/revisions - 200, list of recent changes
* [ ] https://developer.allizom.org/en-US/dashboards/spam - Redirects to Maintenance Mode page
* [ ] https://developer.allizom.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals#Color - 200, with sample as iframe
* [ ] https://developer.allizom.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals$toc - 200, HTML table of contents
* [ ] https://developer.allizom.org/en-US/docs/Web/HTML$children - 200, JSON list of child pages
* [ ] https://developer.allizom.org/en-US/docs/Web/HTML$compare?locale=en-US&to=1299417&from=1293895 - 200, compares revisions
* [ ] https://developer.allizom.org/en-US/docs/Web/HTML$history - 200, list of revisions
* [ ] https://developer.allizom.org/en-US/docs/Web/HTML$json - 200, JSON of page metadata
* [ ] https://developer.allizom.org/en-US/docs/Web/HTML$revision/1293895 - 200, historical revision
* [ ] https://developer.allizom.org/en-US/docs/Web/HTML$translate - Redirect to Maintenance Mode page
* [ ] https://developer.allizom.org/en-US/docs/all - 200, paginated list of docs
* [ ] https://developer.allizom.org/en-US/docs/ckeditor_config.js - 200, JavaScript
* [ ] https://developer.allizom.org/en-US/docs/feeds/atom/files/ - 200, Atom feed of changed files
* [ ] https://developer.allizom.org/en-US/docs/feeds/rss/all/ - 200, RSS feed of new pages
* [ ] https://developer.allizom.org/en-US/docs/feeds/rss/needs-review/ - 200, RSS feed of pages needing review
* [ ] https://developer.allizom.org/en-US/docs/feeds/rss/needs-review/technical - 200, RSS feed of pages needing technical review
* [ ] https://developer.allizom.org/en-US/docs/feeds/rss/revisions - 200, RSS feed of changes
* [ ] https://developer.allizom.org/en-US/docs/feeds/rss/tag/CSS - 200, RSS feed of pages with CSS tag
* [ ] https://developer.allizom.org/en-US/docs/needs-review/editorial - 200, paginated list of documents
* [ ] https://developer.allizom.org/en-US/docs/tag/ARIA - 200, list of documents
* [ ] https://developer.allizom.org/en-US/docs/tags - 200, paginated list of tags
* [ ] https://developer.allizom.org/en-US/docs/top-level - 200, paginated list of documents
* [ ] https://developer.allizom.org/en-US/docs/with-errors - 200, (empty?) paginated list of documents
* [ ] https://developer.allizom.org/en-US/docs/without-parent - 200, paginated list of documents
* [ ] https://developer.allizom.org/en-US/miel  - 500 Internal Server Error
* [ ] https://developer.allizom.org/en-US/profiles/sheppy - 200, Sheppy's profile
* [ ] https://developer.allizom.org/en-US/promote/ - 200, Promote MDN with 4 buttons
* [ ] https://developer.allizom.org/en-US/search - 200, Search results
* [ ] https://developer.allizom.org/fellowship/ - 301 to archive of 2015 MDN Fellowship Program
* [ ] https://developer.allizom.org/files/12984/web-font-example.png - Redirects to https://stage-files.mdn.moz.works
* [ ] https://developer.allizom.org/fr/docs/feeds/rss/l10n-updates/ - 200, RSS feed of out-of-date pages
* [ ] https://developer.allizom.org/fr/docs/localization-tag/inprogress - 200, paginated list of documents
* [ ] https://developer.allizom.org/humans.txt - 200, list of GitHub usernames
* [ ] https://developer.allizom.org/media/kumascript-revision.txt - 200, git commit hash for kumascript
* [ ] https://developer.allizom.org/media/revision.txt - 200, git commit hash for kuma
* [ ] https://developer.allizom.org/presentations/microsummaries/index.html - 200, 2006 OSCON presentation
* [ ] https://developer.allizom.org/robots.txt - 200, robots disallow list
* [ ] https://developer.allizom.org/samples/webgl/sample3 - 200, Shows WebGL demo
* [ ] https://developer.allizom.org/sitemap.xml - 200, list of sitemaps
* [ ] https://developer.allizom.org/sitemaps/en-US/sitemap.xml - 200, list of en-US pages

## Anonymous tests

Test these URLs as an anonymous user:

* [ ] https://developer.allizom.org/admin/users/user/1/ - 302 redirect to the Admin login page, asking for a username and password.
* [ ] https://developer.allizom.org/en-US/docs/Web/HTML$edit - 302 redirect to user sign-in page, asking to Sign In with GitHub
* [ ] https://developer.allizom.org/en-US/Firefox/Releases$edit - 302 redirect to user sign-in page

## Regular Account Tests

Some things to try with a regular account, to exercise write functionality:

* [ ] Create a new MDN user account (may require deleting your ``SocialAccount``)
* [ ] Send a account recovery link for an existing MDN user account
* [ ] Update the account profile
* [ ] Add and verify a new email for a profile
* [ ] Create a new page, such as https://developer.allizom.org/en-US/docs/User:Test
* [ ] Create a translation of the new page
* [ ] Subscribe to a page, and change it with a different account
* [ ] Update the original page with a KumaScript macro, such as ``{{cssxref("background")}}``.
* [ ] Update the translation of a changed English page
* [ ] Upload an image to the page
* [ ] Add the image to the page content
* [ ] Edit a zoned URL like https://developer.allizom.org/en-US/Firefox/Releases
* [ ] Log out

## Admin Tests

* [ ] Move a page
* [ ] Delete a page
* [ ] Move a zoned page
* [ ] View https://developer.allizom.org/admin/users/user/1/

**Comment by jwhitlock** [comment]
I went through the management commands, running ``./manage.py <command> --help``. There are several that have an error (many using the deprecated ``option_list`` attribute, but some others):

* [ ] anonymize
* [ ] delete_old_ip_bans
* [ ] delete_old_revision_ips
* [ ] delete_old_spam_attempt_data
* [ ] djcelerymon
* [ ] pipchecker
* [ ] pop
* [ ] refresh_wiki_caches
* [ ] reindex
* [ ] render_document
* [ ] update_feeds

Other commands look really out-of-date based on the their help message, and may be candidates for deletion:

* [ ] fixaccount
* [ ] merge
* [ ] merge_model_instances
* [ ] populate_attachments
* [ ] repair_translation_breadcrumbs
* [ ] set_fake_emails
* [ ] set_fake_passwords

I need to go through the release notes for management commands again, and look for any other land mines.

**Comment by jwhitlock** [comment]
There are no high-priority bugs remaining. Follow-on work:

* [bug 1467513](https://bugzilla.mozilla.org/show_bug.cgi?id=1467513) - request.user is not available when accessed by early middleware.
* [bug 1467520](https://bugzilla.mozilla.org/show_bug.cgi?id=1467520) - Update to Django 2.2 LTS
* [bug 1467518](https://bugzilla.mozilla.org/show_bug.cgi?id=1467518) - Convert Kuma to Python 3
* [bug 1467532](https://bugzilla.mozilla.org/show_bug.cgi?id=1467532) - Upgrade Kuma dependencies, Q3 2018 - Q4 2018
* [bug 1467529](https://bugzilla.mozilla.org/show_bug.cgi?id=1467529) - Elimate RemovedInDjango2XWarnings
