### ISSUE TITLE
Migrate New Relic from MozMEAO to ET

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#147]
# User story
As a MozMEAO SRE, I want MDN on the ET New Relic account, so that I am not alerted to MDN issues.

# Acceptance criteria
* MDN staging, production, and standby are reporting to the ET New Relic account
* ET New Relic alerts are sent to MDN developers, Papertrail, and MDN Slack channels

# Tasks
* [x] Setup an ET New Relic account, with high-security mode and no browser testing.
* [x] Move staging and production (portland) reporting to ET
* [x] Migrate alerts to ET New Relic account
* [x] Setup MDN alerts channels
* [x] Setup Pagerduty integration
* [x] Create documentation for updating Kubernetes secrets
* [x] Move standby (frankfurt) reporting to ET
* [ ] Debug alert notifications

**Comment by escattone** [comment]
- The documentation has been created for updating the Kubernetes secrets (https://github.com/mozilla/mdn-k8s-private/pull/39 and https://github.com/mozilla/mdn-k8s-private/blob/master/k8s/secrets/README.md)
- The standby cluster is now reporting to the ET-owned New Relic account (https://github.com/mozilla/mdn-k8s-private/pull/40).

**Comment by jwhitlock** [comment]
We're using https://developer.mozilla.org/en-US/ as the URL for New Relic Synthetics, and https://prod.mdn.moz.works/en-US/ as the URL for availability on kuma-web-prod-portland. We'll see if this gives us more actionable alerts during the next incident.
