### ISSUE TITLE
identify and interview stakeholders

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1470]
As a PM I want to identify and interview stakeholders, so we can begin the process of identifying requirements

# Acceptance criteria
- [x] All stakeholders are identified
- [ ] All stakeholders are interviewed
- [ ] Stakeholder expectations are documented

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by jmswisher** [comment]
@atopal Can you link to the document that captures stakeholder expectations?
