### ISSUE TITLE
Submit draft of requirements

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1471]
# User story
As a PM I want to submit a final draft of requirements, so stakeholders are aware of what we are going to build

# Acceptance criteria
- [ ] Synthesized requirements from stakeholder interviews
- [ ] published initial draft
- [ ] collected feedback
- [ ] published final draft

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by jmswisher** [comment]
@atopal Is this issue still valid? It's marked as "Continue in next sprint" in the Lena Horne tab, but doesn't appear in the MC Lyte tab.

**Comment by jmswisher** [comment]
Seems like we've moved beyond this, so I'm closing it.
