### ISSUE TITLE
Ability to run kuma with Python 3

### ISSUE THREAD

**Issue by peterbe** [mdn/sprints#1475]
# User story
Be able to run kuma locally with Python 3. I.e. `docker-compose up` should start and be able to not crash. This includes the Celery worker.

# Acceptance criteria

- [ ] Be able to start `docker-compose` under Python 3 locally
- [ ] Be able to run `make test` inside Docker locally

# Tasks

- [ ] ~~Upgrade to Celery 4~~
- [ ] Remove any Python code that doesn't run in Python 3

**UPDATE May 15 2019**

To better break this down, I filed [a new issue](https://github.com/mdn/sprints/issues/1534) just for upgrading to Celery 4, which I know, will cause a whole host of upgrades of packages. Not only is it a prerequites for Python 3 (due to our old version of `kombu` causing a `SyntaxError` in Python 3).

**Comment by jmswisher** [comment]
@peterbe Is this epic complete? I'm not sure what the extra 3 points mean.

**Comment by peterbe** [comment]
YES! We have some little left-over things we *can* do now that we're in Python3 but nothing that would relate to these issues.
