### ISSUE TITLE
Fork mozmeao/infra to mdn/infra

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#148]
# User story
As a MozMEAO SRE, I want MDN's infrastructure configuration split from MozMEAO, so that I can focus on MozMEAO infrastructure tasks.

# Acceptance criteria
* https://github.com/mdn/infra is used for deployments
* MDN-specific issues are migrated to the new repo
* ~(Stretch) MDN content is removed from https://github.com/mozmeao/infra~ - Will do this after the CI move
* ~(Stretch) Stop using https://quay.io/mozmar/~ - Will do this during the CI move

# Tasks
* [x] Create https://github.com/mdn/infra
* [x] Update deployment to use https://github.com/mdn/infra
* [x] Update documentation for https://github.com/mdn/infra
* [x] Migrate tasks to https://github.com/mdn/infra
* ~Remove MDN content from https://github.com/mozmeao/infra~ - Will do this during the CI move

This is also tracked as https://github.com/mozmeao/infra/issues/839.

**Comment by jmswisher** [comment]
Should this be moved into Sprint 4?

**Comment by escattone** [comment]
Created Bugzilla [#1466976](https://bugzilla.mozilla.org/show_bug.cgi?id=1466976) for tracking updates to the Kuma repo.

**Comment by safwanrahman** [comment]
@jwhitlock If we do not use `https://quay.io/mozmar/`, where should we host it then?

**Comment by escattone** [comment]
https://github.com/mdn/infra is now the active repo used for MDN deployments (see https://github.com/mozilla/kuma/pull/4840 and https://github.com/mdn/kumascript/pull/707).

**Comment by jwhitlock** [comment]
After some discussions last week, we will make the switch to a new docker image repository in the context of setting up a new Jenkins CI server.

@safwanrahman Mozilla Marketing initially used quay.io for private images, but we don't use that feature. Docker Hub seems like a good fit for our usage.

**Comment by jwhitlock** [comment]
I moved this issue:

* https://github.com/mdn/infra/issues/8 - Upgrade Elasticsearch from 2.4 to 5.6

I left these issues:

* https://github.com/mozmeao/infra/issues/839 - Move MDN configuration. This can be closed when we've removed it from that repo.
* https://github.com/mozmeao/infra/issues/824 - MDN Post CDN: Cost Savings? There are potential cost savings, but since MozMEAO has most of the costs, it seems like that issue belongs there.



*

**Comment by jwhitlock** [comment]
We're done with the tasks for this story. Some tasks have been moved to the Continuous Integration setup (https://github.com/mozilla-itcloud/mdn-migration-project/milestone/7), such as picking and setting up a new image repository.  I believe the plan is to build images and deploy with both the MozMEAO JenkinsCI server and the new IT-managed server until production is moved and MozMEAO clusters are decommissioned.
