### ISSUE TITLE
Evaluative testing on new BCD custom configuration and messaging

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1492]
# User story
As a web developer, I want to get a preview of the new BCD custom configuration and messaging feature, so that I can provide feedback and help make it better.

# Acceptance criteria

# Tasks
- [x] Create protocol for moderated sessions
- [x] Create protocol for unmoderated sessions
- [x] Review protocol with Kadir
- [x] Create click-through prototype using InVision mocks
- [x] Set up calendly
- [x] Create email correspondence templates
- [x] Recruit 8-10 participants
- [x] Run sessions

### Research Findings
https://docs.google.com/document/d/1kkCPgR43XKgZQMp7LmcQ3U9CwJIPAzsyXbRUXiVm6a8/edit?usp=sharing
