### ISSUE TITLE
Inform users of the new custom compatibility configuration and messaging feature

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1624]
# User story
As a web developer, I want to be informed about the new custom compatibility feature, so that I can take advantage of this and know when I am viewing a reference that is not supported by my needs.

# Acceptance criteria
- [ ] Message is displayed in browser compatibility section of pages
- [ ] Message shows for users that are both logged in and not logged in
- [ ] Is no longer shown once a user has set up a configuration, or dismisses the message (clicks close button)

# Tasks

# Design
https://invis.io/H7RYTNDM2BT#/362767726_CC_Inform_-_In_BCD_Table

_These may change based off the evaluative sessions in progress_
