### ISSUE TITLE
Display alert message when viewing a reference page that is not supported by user’s custom compatibility settings

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1625]
# User story
As a web developer, I want to see an alert notification at the top of the page when I am viewing a reference that is not supported by my custom compatibility settings, so I’m not surprised about it later.

# Acceptance criteria
- [ ] Displays a red alert bar when the reference is not supported by user's configuration settings
- [ ] Displays a yellow/orange bar when the reference is supported, but some of the values are not
- [ ] Includes an anchor link in the notification that takes the user to the browser compatibility table (jumps down the page)

# Tasks

# Design
Not Supported: https://invis.io/H7RYTNDM2BT#/362771290_CC_Reference_-_Not_Support
Limited Support: https://invis.io/H7RYTNDM2BT#/362771291_CC_Reference_-_Limited_Support

_These may change based off the evaluative sessions in progress_

**Comment by schalkneethling** [comment]
Discussion around this is happening in the following issue:
https://github.com/mdn/sprints/issues/1668
