### ISSUE TITLE
Allow user to configure browsers important to them to receive notifications against

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1626]
# User story
As a web developer, I want to be able to set the browsers and versions I need to support within my account preferences, so I can be informed when I am viewing a reference that is not supported by my settings.

# Acceptance criteria

- [ ] Options would include the latest version of all the browsers we display in the compatibility table
- [ ] Allows users to provide a name for the configuration set, so they can have multiple sets (name is required to save set)
- [ ] Users must select at least 1 browser to save the set

# Tasks

# Design
Initial: https://invis.io/H7RYTNDM2BT#/362767663_CC_Profile_-_Create_-_1
Filled: https://invis.io/H7RYTNDM2BT#/363339196_CC_Profile_-_Create_-_9
Options dropdown: https://invis.io/H7RYTNDM2BT#/362767661_CC_Profile_-_Create_-_3

_These may change based off the evaluative sessions in progress_
