### ISSUE TITLE
Display status of user's selected custom compatibility set in the sidebar of reference pages

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1627]
# User story
As a web developer, I want to see the status of my selected compatibility set in the sidebar when I am viewing a reference, so I understand whether or not the reference is supported by my compatibility settings.

# Acceptance criteria

- [ ] Would be red with the text: Not Supported, for references that are not supported by the user's settings
- [ ] Would be orange/yellow with the text: Limited Support, for references that are are supported, but some of the values are not by the user's settings
- [ ] Would be green with the text: Full Support, for references that are supported as well as the values by the user's settings
- [ ] Includes the ability to toggle between any set the user has created within a dropdown
- [ ] Includes the option to create a new compatibility set as the last option in the dropdown
- [ ] Includes a link to edit the selected compatibility set
- [ ] options to switch/add/edit sets shows a note that the feature will be available soon.

# Tasks

# Design
Not Supported: https://invis.io/H7RYTNDM2BT#/362771290_CC_Reference_-_Not_Support
Full Support: https://invis.io/H7RYTNDM2BT#/362771289_CC_Reference_-_Full_Support
Limited Support: https://invis.io/H7RYTNDM2BT#/362771291_CC_Reference_-_Limited_Support
Dropdown: https://invis.io/H7RYTNDM2BT#/362772778_CC_Reference_-_Not_Support_-_Dropdown

_These may change based off the evaluative sessions in progress_

**Comment by jmswisher** [comment]
For color-vision accessibility, I encourage you to use [vermilion](https://jfly.uni-koeln.de/color/#pallet) or [magenta](https://www.somersault1824.com/tips-for-designing-scientific-figures-for-color-blind-readers/) in place of red, and blue-green or turquoise in place of green.

**Comment by nickbrandt** [comment]
I agree that color-vision accessibility needs to be a part in determining the what we use for this (as well as updating current error colors used on MDN if we choose not to stick with that). However, I don't think it makes sense to use colors like magenta or turquoise, as those do not have the same correlation and meaning to users that something closer to red/green would have (for people that don't have vision impairments). It would be important to make sure there is a clear contrast between the colors chosen for those that are color-blind.

The designs that have been provided in this story are still wireframes (with minimal color added), and were used for testing purposes. Generic red/green colors were used during this, and since it was not a visual design pass, things like color-vision accessibility were not yet considered. This is one reason I was surprised we were already moving forward with development for this feature, seeing that both evaluative efforts (things that may change layout/how things work), as well as visual design (things that may change the look) have yet to be completed.

I do understand the need to get started with this though, but do know that there is more work to be done on this from the design standpoint, which will most definitely add at least some level of effort on the development side.

**Comment by schalkneethling** [comment]
This is also still blocked by the discussion in https://github.com/mdn/sprints/issues/1668
