### ISSUE TITLE
Design for multiple account types (general user and contributor)

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1633]
# User story
As a user, I want to be able to create/have an account with the option to be a contributor, so that my experience on MDN is tailored to how I will be using it.

# Acceptance criteria

# Tasks
- [x] Design flow for creating an account with the option to be a contributor
- [x] Design flow for changing your account type within the profile section
- [x] Changes in UI on reference pages
- [x] Changes in UI in the site header
- [x] Review with Kadir
- [x] Changes based on review
- [x] Visual design

## Design
Profile - Contributor Section (initial): https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368224248_Account_-_Contributing_-initial-

Profile - Contributor Section (contributor): https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/370705979_Account_-_Contributing_-enabled-

Profile - Contributor Section (opted out): https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/372750125_Account_-_Contributing_-opted_Out-

Reference Page - General User:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368126661_GU_-_Reference_Page

Reference Page - Contributor:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368126659_CR_-_Reference_Page

User Menu - General User:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368126660_GU_-_Reference_Page_-_User_Menu

User Menu - Contributor:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368126658_CR_-_Reference_Page_-_User_Menu
