### ISSUE TITLE
Design updates to create account/sign-in flow to improve experience

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1634]
# User story
As a user, I want the create account/sign-in experience to be easily understood and effortless, so that I am not confused in this process and it is not a barrier to me having an MDN account.

# Acceptance criteria
- [x] Authentication flow for Google auth and Github auth

# Tasks

- [x] Create account flow
- [x] Sign In flow

## Design

Sign In - Landing Page:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/370705984_Sign_In

Create Profile (used Github):
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368129372_Create_Account_-_MDN_Profile

Create Profile (used Google):
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/370705985_Create_Account_-_MDN_Profile_-google-

---

Create Profile (used Github) - alternate (no profile pic):
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/372899930_Create_Account_-_MDN_Profile_-alt_2-

Create Profile (used Github) - alternate (has profile pic):
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/372899931_Create_Account_-_MDN_Profile_-alt_2_-_With_Pic-

**Comment by tobinmori** [comment]
@atopal is there supposed to be a difference between the last 2 links Nick shared? No profile pic vs has profile pic?

**Comment by atopal** [comment]
I think the links might have broken and now they just link to the start of the flow instead of specific steps. Here's what they should have linked to (probably):

no profile pic: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/screens/374829955
has profile pic: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/screens/374095626

**Comment by tobinmori** [comment]
thanks @atopal I see them now.
