### ISSUE TITLE
Add Speedcurve LUX snippet for Real User Metrics

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#1648]
# User story

As a product owner, I want to add the Speedcurve LUX script to MDN Web Docs pages, so I can track real user metrics.

Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1553075

# Acceptance criteria

- [x] Script is added to head of all MDN Web Docs pages
- [x] Deployed to production
- [x] Speedcurve is receiving data

# Tasks

1. - [x] Add script to head off the base template
2. - [x] Open PR
3. - [x] Deploy to production
4. - [x] Verify that data is received by Speedcurve

**Comment by schalkneethling** [comment]
This is in production and Speedcurve is receiving data.
