### ISSUE TITLE
As  PM I want to have launch plan for Kuma.Next so we can prepare ourselves and others for the launch

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1651]
# User story
As  PM I want to have launch plan for Kuma.Next so we can prepare ourselves and others for the launch

# Acceptance criteria

- [ ] Beta testing plan, including audience participation drafted and shared
- [x] Launch schedule drafted and shared
- [x] comms team briefed
- [x] communications with user/contributors planed
- [x] Professional QA resources investigated and if possible contracted

# Tasks
*If relevant, you can make a checklist for tasks.*

- [ ] Identify beta test phases/audiences
- [ ] Identify QA resources
- [ ]

**Comment by atopal** [comment]
Link to plan https://docs.google.com/document/d/17OYK5uvYvU-WD6roXo2CeWXvLodfC0llV9GNjGDa5ug/edit
