### ISSUE TITLE
As a BCD user I want to be able to set the browser versions I care about, so I can be notified only when there is an issue with them

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1665]
As a BCD user I want to be able to set the browser versions I care about, so I can be notified only when there is an issue with them

# Acceptance criteria

- [ ] user can select specific version for a browser
- [ ] user can select "latest version"
- [ ] user can select "last 3 versions" 

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.
