### ISSUE TITLE
Determine how to show warnings

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1668]
# Feature
The BCD on top feature relies on BCD data to determine whether the browsers that people care about are supported. The logic is straight forward for simple cases, where there is only one table row and it's all green, or one table row and there is an unsupported browser. It's more complicated when there is more than one row or missing data. This story intends to clarify the logic.

# Acceptance criteria
- [ ] Documented how the logic works
- [ ] logic for missing support implemented
- [ ] logic for partial support implemented
- [ ] logic for full support is implemented
- [ ] The default set of browser is implemented as "latest Chrome, Edge, Safari, IE, Firefox, chrome on Andorid, Safari on iOS"

# Tasks
- [ ] List possible cases
- [ ] Solve for the simple cases
- [ ] Make proposals for the non-simple cases
- [ ] Get input from team on those non-simple cases
- [ ] Drive decision
- [ ] Implement logic

**Comment by schalkneethling** [comment]
# Documented how the logic works

I have been working on[https://github.com/schalkneethling/mdn-magellan] and thinking about this for some time now, and here follows my feedback so far. To start with, this is no simple matter, but here goes.

The first topic that needs to be addressed and decided upon is the meaning of the various colors?

If you have for example the following browser selection:
Firefox, Chrome, Safari, Edge (the latest version only)

Do we show green if, and only if:

1. All four of these browsers/versions fully support the feature?
2. What if one of the browsers support the feature, but via a prefix i.e. `-moz-`, `-webkit-` etc? Does that count as full support?

Do we show red if, and only if:

1. All four of these browsers/versions do *not* support the feature?

If the above is true, does that mean we show partial support for all other instances?

If true, it seems to me that for most(80-90%?) modern language features we will show the partial support bar. Meaning users will have to look over the browser compatibility table to figure out what the actual support breakdown is.

Does this feature then become a lot less useful?
Would it perhaps be better to only focus on full support and no support?

If there is variation in what defines green and red, i.e. it is not all or nothing, how will we communicate this to the user. For example, using the same browser scenario from earlier, what if support is as follows:

Firefox[supported], Chrome[supported], Edge[supported], Safari[not supported]

If we show green for the above scenario, how will we communicate to the user that in fact, one of their browsers does not [fully]support the feature? This becomes a lot more complicated when you have a browser matrix such as:

```
Firefox 67, 66, 65
Chrome 77, 76, 75
Safari 9.1, 10.1, 11.1
Edge 16, 17, 18
```

One option that may be worth exploring is to constrain browser/version selection too, at most, 4 browsers and 3 versions per browser. In other words, the above metric would be the most complex.

We can then show a simplified BCD table as opposed to a single bar, for example:

## One Browsers, One Version

![1browser1version](https://user-images.githubusercontent.com/10350960/58913756-2e2ccc80-871d-11e9-9bd7-bcb9e72c890a.png)

## Two Browsers, Latest Version

![2browsers1version](https://user-images.githubusercontent.com/10350960/58913343-4819df80-871c-11e9-82a2-81a1f105856f.png)

## Four Browsers, Latest Version

![4browsers1version](https://user-images.githubusercontent.com/10350960/58913367-5405a180-871c-11e9-8a3c-b59974ec9d18.png)

## Four Browsers, Three Version (most complex/worst case scenario)

![4browsers3version](https://user-images.githubusercontent.com/10350960/58913402-67b10800-871c-11e9-89b9-97547af370d7.png)

## Deprecated features

What do we do about features marked as deprecated? I am thinking we do not want to encourage people to use these feature still so, perhaps we should not show support information on these pages?

The information is still contained in the BCD table. Although, it might still be useful to some users who need to support very old browser versions. Thought I would mention it though.

## Partial support of a feature

Have we thought about scenarios such as flexbox's `justify-contents`? https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#Browser_compatibility

Here, for example, we generally have great support, but for some of the "newer" values, support is all over the place, and for Safari data is sparse. Do we focus on "basic" support?

There is more to this, but I reckon this is a good place to stop for now. Let me know your thoughts on the above @atopal @nickbrandt - Thank you in advance.

**Comment by nickbrandt** [comment]
@schalkneethling perhaps I didn't explain this thoroughly enough regarding the initial expectations for when you would receive different warnings. Below are my thoughts on how this would work, but definitely would love to hear your feedback regarding it:

Lets take the scenario a user selects the following in their browser set:
- Chrome (last 3 versions)
- Firefox (last 3 version)
- IE (specific version - 11)

When viewing a reference page...

They would see a **red** warning if:
**Any** of those browser versions are not supported for the specific reference. So even if it was just IE 11 that was not supported, we show a red warning. The notion of these browser sets is these are requirements they have for their project, and if even one of these browsers is not supported, this needs to be seen as a red flag.

They would see a **yellow/orange** warning if:
**All** of those browsers are supported for the general reference, but some of the subcomponents (ex: values for CSS properties) are not supported. This would mean that overall they are OK using this reference, but there is **limited** support for what they could do with it.

They would see **green** in the status if:
**All** of the browsers are supported for the general reference, as well as any subcomponents for the reference.

One thing that still needs to be determined is what happens when there are unknown values in the table, meaning we don't have answers for whether or not it is supported.

In regards to prefixes: if something is supported, but it requires a prefix, I see that as full support. I don't find it necessary for us to distinguish areas where a user needs to add prefixes, as that is discussed in the reference documentation. These alerts/statuses are more for a quick notice on whether or not there is support for their requirements.

I don't really like the idea of restricting the number of browsers a user can configure, nor the idea of recreating a compatibility table at the top that represents their selections. From the evaluative research, there were some expectations from participants that we would update the compatibility table  (at the bottom) based on their configuration (either filtering or highlighting errors within their configured browsers), though for now we are not planning any enhancements to that for the MVP of this feature.

Let me know your thoughts on this, as I'm sure there are still many unanswered questions. @atopal will probably have some thoughts on this as well.

**Comment by schalkneethling** [comment]
Thank you for the feedback @nickbrandt, this helps a lot.

**Comment by jpmedley** [comment]
(Side comment. Everyone treats compatibility strictly as a mater of browser version numbers. It's also a matter of browser market share and version market share in the geography bounding your target audience or customer base.)

**Comment by nickbrandt** [comment]
@jpmedley it is dangerous to say things such as **everyone**, as although that may be the case for some, it is not for all. We definitely had a fair share of participants in our research that explained they didn't have specific versions that they cared about or were required to support on projects, but instead wanted to make sure what they were building was supported by most "modern browsers", or a good percentage of their target audience (hence your comment regarding market share). I think the point you make regarding market share and the geography of your target audience are important factors for determining where those cutoffs are, and I wish we had that information accessible to us at this time (as far as I know we do not). I can definitely see this feature including those sort of capabilities in the future, where user's are able to see what sort of market share their settings support in assisting them in making better judgment calls. I hope that all makes sense.

**Comment by schalkneethling** [comment]
@jpmedley @nickbrandt I wonder where caniuse get their data? Could it be an open source data set that we can tap into as well? I don't mean for it to be a blocker, but would be useful if we could add that kind of information.

@nickbrandt I do not entirely agree that having to use a vendor prefix is equal to full support. Other than the BCD table at the end of documentation pages, I do not believe it is addressed in the content. I therefore still feel that we need to inform the user in some way that, although the feature works in browser X, it requires a vendor prefix and to look for further details in the BCD table.

**Comment by jmswisher** [comment]
I support the idea of being conservative with the meaning of "green". It should signify "no worries, go ahead and use as-is". "Yellow" should mean "Pause, read carefully and think about it". Vendor prefixes require special coding, therefore special consideration, therefore I think they should trigger "yellow".

By similar reasoning, unknown values should trigger a "yellow", meaning "we don't know -- you figure it out"; whereas "red" is "we know it's NOT supported" and "green" is "we know it IS supported". (This implies that "yellow" is doing double duty: in some cases it's about certainty and in other cases it's about completeness. I think this is OK.)

**Comment by jpmedley** [comment]
Sounds simple enough. The reality of that is not. Compare [Payment Request](https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest#Specifications) with [Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker#Specifications). Based on W3C status you might set Payment Request to green and Service Worker to yellow. If you look at implementations by major browsers, I'd give them exactly the opposite colors. Payments API are volatile and unstable and based on what I've seen in my inbox, will continue to be for a while. Service workers have been stable and widely supported for several years.

**Comment by atopal** [comment]
@jpmedley yellow and green would depend on the browser set that people have explicitly selected.

@schalkneethling I'd go with Nick's specification for now. We can still user test to make sure it matches people's expectations in beta. Besides, pre-fixes are becoming less and less of an issue.
