### ISSUE TITLE
KumaScript: Use `inheritance.json` from the `mdn‑data` package

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/sprints#1694]
## Acceptance criteria
API interface inheritance data is used from the `mdn‑data` package within **KumaScript** and `InterfaceData.json` is deleted.

## Tasks
- [ ] https://github.com/mdn/data/pull/358: Sort `mdn‑data/api/inheritance.json`
- [ ] https://github.com/mdn/data/pull/371: Import remaining `InterfaceData.json` changes from KumaScript
- [ ] https://github.com/mdn/kumascript/pull/1178: Use `inheritance.json` from the `mdn‑data` package

## See also
- #1062

**Comment by ExE-Boss** [comment]
<https://github.com/mdn/kumascript/pull/1178> is ready for review.
