### ISSUE TITLE
[meta] KumaScript: Use the `mdn‑data` package

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/sprints#1695]
## User story
As a MDN contributor, I want to have the data in a centralised place, so I know where to contribute data, which is then displayed in MDN pages.

## Acceptance criteria
All `*Data.json` have been migrated from KumaScript to `mdn‑data`.

## Tasks
- [ ] Migrate `InterfaceData.json` (#1694)
- [ ] Migrate `GroupData.json`
- [ ] Migrate `SpecData.json`
- [ ] Migrate `SVGData.json`
