### ISSUE TITLE
Report number of rate-limit errors experienced by Google

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#1711]
# User story
As a developer I'd like to know if the rate-limit increase made in https://github.com/mdn/sprints/issues/1629 has actually eliminated the rate-limit error responses (429's) experienced by Google Crawler and Google Translate.

NOTE: The time and date of the deployment of https://github.com/mozilla/kuma/pull/5466 to production was 5pm PT on June 4, 2019.

# Acceptance criteria
- [x] Report the actual number of 429 responses on document page views experienced by the Google Crawler or Google Translate since 5pm PT on June 4.

# Tasks
- [x] Using AWS Athena, query the production CDN logs since 5pm PT on June 4 for all of the IP addresses that have experienced 429 errors on document page views. (@escattone)
- [x] Determine if any of the IP addresses match those used by the Google Crawler or Google Translate. (@limed)

**Comment by escattone** [comment]
Using AWS Athena, I've queried production CDN logs and given the resulting CSV data to @limed for an analysis of the IP's.

**Comment by escattone** [comment]
Here's the query that I used:
```sql
SELECT count(*), requestip
FROM prod_cdn_logs
WHERE (status = 429) AND (uri LIKE '%/docs/%') AND (date BETWEEN DATE '2019-06-05' AND DATE '2019-06-12')
GROUP BY requestip
ORDER BY count(*) DESC;
```
NOTE: Since 5pm PT June 4 translates to 12am UTC June 5 (the AWS CDN logs use UTC for dates/times), I could use a simple date of `2019-06-05` for the start of the query's date range.

**Comment by limed** [comment]
Based on the data provided these are the IP's that are from the google domains

```
['215', '35.230.89.108', '108.89.230.35.bc.googleusercontent.com']
['105', '35.197.118.104', '104.118.197.35.bc.googleusercontent.com']
['75', '35.247.125.48', '48.125.247.35.bc.googleusercontent.com']
['73', '34.83.49.24', '24.49.83.34.bc.googleusercontent.com']
['53', '34.83.148.77', '77.148.83.34.bc.googleusercontent.com']
```

The domain `googleusercontent.com` however I believe is actually from GCP (google cloud services) and not from crawlers. Based on their documentation [here](https://support.google.com/webmasters/answer/80553?hl=en) google bots should have a domain of `googlebot.com` or just `google.com`

**Comment by escattone** [comment]
Based on @limed's analysis of the data, I think it's safe to say that both Google Bot and Google Translate have not experienced any 429's since 5pm PT on June 4th, 2019.

**Comment by escattone** [comment]
Actually, Google translate uses the `*googleusercontent.com` domain (see https://helpx.adobe.com/analytics/kb/googleusercontentcom-instances.html), so although it's safe to say that the Google Bot is no longer throttled, Google Translate still may be sometimes.
