### ISSUE TITLE
Publish May 2018 Changelog

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#174]
# User story
As an MDN enthusiast, I want to know what was done in May 2018, so I know where MDN is improving.

# Acceptance criteria

* May 2018 Changelog is published on Hacks on June 8
* Post is promoted on Twitter and Discourse

# Tasks
- [x] Gather things that shipped and June plans
- [x] Submit draft to Havi
- [x] Approve final draft for publishing
- [x] Publish June 8
- [x] Reshare on Twitter
- [x] Update [Discourse post](https://discourse.mozilla.org/t/mdn-changelog-2018/25271)
- [x] Correct Interactive Examples section

**Comment by jwhitlock** [comment]
@schalkneethling tells me that the Shadow DOM polyfill did ship in May, in https://github.com/mdn/interactive-examples/pull/894. I think I was relying on the meeting notes at https://github.com/mdn/interactive-examples/wiki/Weekly-Meeting-Notes#8-may-2018. I'm going to see if I can add a correction, and point to https://github.com/mdn/interactive-examples/issues?q=is%3Aissue+is%3Aopen+label%3AP1

**Comment by jwhitlock** [comment]
This shipped on June 8: https://hacks.mozilla.org/2018/06/media-mathml-and-django-1-11-mdn-changelog-for-may-2018/
