### ISSUE TITLE
Delete articles Document/policy and HTMLIFrameElement/policy

### ISSUE THREAD

**Issue by bershanskiy** [mdn/sprints#1758]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

## Summary

As discussed in https://github.com/mdn/browser-compat-data/issues/4367, `{document,HTMLIFrameElement}.policy` was renamed into `{document,HTMLIFrameElement}.featurePolicy`. A few MDN pages need to be deleted or moved and updated.

## Tasks
- [x] Delete https://developer.mozilla.org/en-US/docs/Web/API/Document/policy
       Content was moved to https://developer.mozilla.org/en-US/docs/Web/API/Document/featurePolicy and updated
   - [x] Update and move Japanese translation from https://developer.mozilla.org/ja/docs/Web/API/Document/policy to https://developer.mozilla.org/ja/docs/Web/API/Document/featurePolicy
- [x] Delete https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/policy
- [x] Content was moved to https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/featurePolicy and updated
       No translations at the time of writing

**Comment by bershanskiy** [comment]
# NOTE: Please wait until https://github.com/mdn/browser-compat-data/pull/4381 is merged so that the compatibility tables do not link to nonexistent pages.

**Comment by bershanskiy** [comment]
Update: The browser compatibility data has landed onto the website already, so the links in browser compatibility tables are updated. I think these old pages can be safely deleted now. Please note that translations should also be deleted (I already moved translations to new URLs and just replaced `policy` with `featurePolicy` where applicable).

**Comment by irenesmith** [comment]
Pages have been deleted.

**Comment by bershanskiy** [comment]
@irenesmith 
> Pages have been deleted.

Thanks, but I still can see this article translation that I believe should be deleted too:
https://developer.mozilla.org/ja/docs/Web/API/Document/policy
Most likely, it will not help anyone (`document.policy` is not used in any browser anymore) and will only cause confuse people.

**Comment by irenesmith** [comment]
Just deleted it as well. Sorry to have missed it.
