### ISSUE TITLE
Create K8s resource files required by the developer portal

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#1767]
# User story
As a staff developer, as part of the effort to integrate the developer-portal (https://github.com/mdn/developer-portal) into MDN's AWS infrastructure, so it's ready for the new membership content, I want to create the Kubernetes resource files necessary for deploying it into our EKS-based Kubernetes cluster.

# Tasks

- [x] Create/test an SSL cert for the `service` resource
- [x] Create/test `service` resource
- [x] Create/test `deployment` resource
- [x] Create/test `job` resource for database migrations
- [x] Create/test `secrets` resource
- [x] Create/test Makefile for deploying/deleting the resources as well as for getting status

**Comment by escattone** [comment]
https://github.com/mdn/developer-portal/pull/17
