### ISSUE TITLE
SVG: Update low priority API pages [2/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#178]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern MDN API layout pages.

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAltGlyphDefElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAltGlyphElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAltGlyphItemElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGGlyphRefElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTRefElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGViewElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGStyleElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMeshElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedPoints
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMeshrowElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSolidcolorElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGStopElement
