### ISSUE TITLE
Design the flow for the new Learning Pathways

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1786]
# User story
As a user, I want to be able to locate content for dedicated learning pathways, and be able to easily navigate through those sections, so that I can be guided towards a tangible outcome in my learning progress.

# Acceptance criteria

- [ ] User can be directed to the 2 pathways from the Learning Area landing page
- [ ] Learning pathways direct users to information within MDN, on Developer Portal, as well as 3rd party resources
- [ ] User must log in to view "premium content" on the Developer Portal

# Tasks

- [ ] User flows in lucidchart
- [ ] Review with Team
- [ ] Alterations as needed
- [ ] Final review

https://www.lucidchart.com/invitations/accept/ee6f6d0c-aca2-49bb-84e9-c8020db43fb1
