### ISSUE TITLE
Epic: Design the experience for new Learning Pathways

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1792]
# User story
As a user, I want to be able to locate content for dedicated learning pathways, and be able to easily navigate through those sections, so that I can be guided towards a tangible outcome in my learning progress.

# Acceptance criteria

- [ ] User can be directed to the 2 pathways from the Learning Area landing page
- [ ] User clearly understands where links on the pathway pages are directed (MDN, Dev Portal, 3rd Party)
- [ ] User clearly understands what content requires a login vs not
- [ ] There is messaging around some of the content that will not always be free
- [ ] User is able to understand their place in the pathway process, and easily get back to where they were in their journey
- [ ] User understands the time it takes to go through different sections

# Tasks

- [ ] User flows in lucidchart
- [ ] Wireframe experience on MDN
- [ ] Review with dev team
- [ ] Review with Kadir
- [ ] Put together clickable prototype in InVision
- [ ] Create visual design based on wireframes
- [ ] Final review

# Included Stories
#1786 Design the flow for the new Learning Pathways
#1793 Create wireframes and visual design based off user flow for Learning Pathways
