### ISSUE TITLE
As a PM I want a short list of potential partners that have content that fits into the learning pathways

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1799]
# User story
As a PM I want a short list of potential partners that have content that fits into the learning pathways

# Acceptance criteria

- [ ] Partners selected and documented
- [ ] Selection reviewed by content manager

# Tasks

- [ ] Potential partners identified
- [ ] Partners rated by fit of content, quality of instruction, accuracy of material, reputational safety and potential M&A candidates
- [ ] short list documented

**Comment by atopal** [comment]
See https://docs.google.com/spreadsheets/d/1bMnuh5IntD24EeqHyqSXmnUKQd0E9UWZ4sGiuQubMmY/edit#gid=0
