### ISSUE TITLE
SVG: Update low priority API pages [3/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#180]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern MDN API layout pages.

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMPathElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/TimeEvent
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMetadataElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSwitchElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSymbolElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTitleElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGDescElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedPreserveAspectRatio
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedTransformList
