### ISSUE TITLE
PWAs: Engage with related external groups to plan a content outline

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#1800]
Several external parties are interested in participating to ensure this documentation is up to snuff. Engage with them to make sure we have a content plan that makes sense and is thorough, covering all the topics of value and of interest, including cross platform support, mobile platform support issues (such as the sort-of support on iOS), etc.

## Tasks

- [x] Share the current plan document and invite input and suggested changes
- [ ] Schedule and hold a conversation in Zoom or whatever to discuss the plan as needed
- [ ] The same discussion may be a good time to elicit  volunteers to contribute content; the assignments are part of issue #1802.

The interested parties include:

* Joe Medley (Google)
* Dan Appelquist (Samsung)
* Aaron Gustafson (Microsoft)

## Acceptance criteria

- [ ] A content outline or plan document has been sketched out
