### ISSUE TITLE
Design improvements to mobile experience

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1805]
# User story
As a user, I want to be able to easily navigate MDN on my mobile device, so that I can still access that content when I am away from my computer.

# Acceptance criteria

# Tasks

- [ ] Audit of current mobile experience
- [ ] Changes for main navigation
- [ ] Update search placement
- [ ] Decide on best approach for sidebar content on mobile
- [ ] Design for how breadcrumbs and language selector appear on mobile
- [ ] Demos are not scrollable (horizontally) on mobile
- [ ] Anchor links don't appear to be functional (able to be copied)
