### ISSUE TITLE
Make the published stage version of the developer-portal CMS available on MDN stage

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#1806]
# User story
As a developer-portal developer, I'd like to ensure that the published version of the stage developer-portal CMS is available on the stage instance of MDN.

# Acceptance criteria

- [ ] The published stage version of the developer-portal is available at https://developer.allizom.org/portal

# Tasks

- [x] Add a behavior to the stage MDN CDN with a path of `/portal` and an origin of the stage developer-portal S3 bucket
- [x] Add configuration and/or code to the developer-portal CMS "build" command (the command that creates a static version of the CMS) that syncs the build results to the stage S3 bucket

**Comment by escattone** [comment]
It looks like [django-bakery](https://django-bakery.readthedocs.io/en/latest/), upon which [wagtail-bakery](https://github.com/wagtail/wagtail-bakery) is built, supports publishing to S3 via a `publish` management command. That's good news for us, since it means we don't have to create the code that syncs the contents of the build directory to S3 (which is not difficult, just more time consuming), but instead simply provide the proper configuration (see https://django-bakery.readthedocs.io/en/latest/settingsvariables.html#aws-bucket-name). One potential wrinkle is that instead of AWS access/secret keys, we're using a special AWS IAM role associated with the Kubernetes pods running the Wagtail CMS, but looking through the `django-bakery` source code, they're using standard `boto3` commands which, in the absence of the AWS access/secret keys, should detect and use the AWS IAM role.

**Comment by escattone** [comment]
Just a note to say that testing the publication to S3 is a two step process. We first have to `build`, then `publish`. So assuming we're on a Kubernetes pod that's part of the `wagtail` deployment:
```sh
./manage.py build
./manage.py publish
```

**Comment by escattone** [comment]
- [x] I manually created the origin `S3-mdn-dev-portal-stage` (`developer-portal-stage-178589013767.s3-website-us-west-2.amazonaws.com`) on the MDN stage CloudFront instance
- [x] I also manually added the behavior `/portal/*` to the MDN stage CloudFront instance

**Comment by escattone** [comment]
In order to publish, I logged into one of the stage `wagtail` pods, and did the following:
```sh
./manage.py build --build-dir /app/build/portal
./manage.py publish
```

**NOTE**: The `--build-dir /app/build/portal` portion of the `build` command. That's necessary so that the request paths map directly to the keys in the S3 bucket.

**Comment by escattone** [comment]
This is done. The current wagtail-bakery build (`./manage.py build --build-dir /app/build/portal`) of the developer-portal produces rubbish (every page is `<h1>Bad Request (400)</h1>`). I think that's due to the fact that we don't yet have Potato's latest code in our repo (https://github.com/mdn/developer-portal), but I think we're going to receive an update within the next day or two. We may have further adjustments to make at that time, but this task as planned is complete.

**Comment by escattone** [comment]
Wanted to record associated PR's:
https://github.com/mdn/developer-portal/pull/21
https://github.com/mdn/developer-portal/pull/23
https://github.com/mdn/developer-portal/pull/24
https://github.com/mdn/developer-portal/pull/25
https://github.com/mdn/developer-portal/pull/26

**Comment by escattone** [comment]
We discovered some issues with the build step that need to be addressed.

**Comment by escattone** [comment]
There are issues that make building a site using django-bakery complicated in our case:
- the static file URL's must be prefixed with `/portal/static/` rather `/static/` so that the CDN behavior that handles the requests for the developer-portal captures those static-file requests (and routes them to the developer-portal S3 bucket that serves those files) instead of the MDN-specific behavior (which would route them to the MDN Django instances which know nothing about those static files)
- the CDN behavior captures requests for the developer-portal based on paths starting with `portal/` and passes along the full path (including the `portal/` prefix) to the developer-portal S3 bucket that serves those requests, so the keys for all of the objects in the S3 bucket should start with `portal/`

Here's what I had to do in order to successfully build and publish:
- created a new settings file `developerportal/settings/build.py` with contents:
```python
from .production import *

STATIC_URL = '/portal' + STATIC_URL
BUILD_DIR = BUILD_DIR + '/portal'
```
- pre-built the build directory to avoid a bug in the build command where it can't handle a `STATIC_URL` setting with multiple-segment directory paths
```sh
mkdir -p build/portal/portal
```
- ran the build command this way:
```sh
./manage.py build --settings developerportal.settings.build --keep-build-dir
```
- moved the static files into their proper place:
```sh
mv build/portal/portal/static build/portal
rm -rf build/portal/portal
```
- the publish remains the same and uses the normal `BUILD_DIR` setting so that it includes the `portal/` prefix for all objects it creates in S3 :
```sh
./manage.py publish
```

**Comment by tobinmori** [comment]
In the backlog for Steve.

**Comment by escattone** [comment]
The new domain for the "build-and-sync'ed" (or what above has been called "published") stage site is https://developer-portal-published.stage.mdn.mozit.cloud/. I think this task is nearly done, but @stevejalim, with support from @limed and occasional support from myself, has taken command of the developer portal project.

**Comment by escattone** [comment]
@stevejalim has re-organized, improved, and clarified much of this, and all that may remain here is to do a fresh `build-and-sync`, but I'll leave the status of this in his hands.

**Comment by jmswisher** [comment]
@escattone @stevejalim @limed Can this issue be closed?

**Comment by stevejalim** [comment]
@jmswisher Yep, this ticket is now basically irrelevant to the current shape of the developerportal project, so happy to close.

To clarify: we're now no longer building out a static version of the site, and instead are simply running Wagtail behind a CDN.
