### ISSUE TITLE
SVG: Add example on top of low priority API pages [3/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#181]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMPathElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/TimeEvent
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMetadataElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSwitchElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSymbolElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTitleElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGDescElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedPreserveAspectRatio
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedTransformList
