### ISSUE TITLE
E - Automated account management

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#1815]
### Overall owner
Kadir

### Rationale
Currently we are receiving about 2 account deleting requests per week. Once we incentivize account creation, we expect that number to rise, so we should allow people to delete their own accounts before we do that.

### Description 
Users can delete her own account and we account for all cases.

### Scoring
- [x] 50% People without any contributions can delete their account
- [x] 25% People with contributions who want to keep being attributed can delete their account
- [x] 25% People with contributions who don’t want to keep being attributed can delete their account

**Comment by chinikes** [comment]
HI @atopal - Are we taking the items under "Scoring" as the acceptance criteria for this Epic?

**Comment by atopal** [comment]
@chinikes yes

**Comment by chinikes** [comment]
@atopal, @tobinmori - With all user stories / tasks under this epic marked as closed, can we deem this epic as done? Are the ACs now satisfied?

**Comment by atopal** [comment]
Yes, they are. Closing now.
