### ISSUE TITLE
SVG: Update low priority API pages [4/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#182]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern MDN API layout pages.

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGComponentTransferFunctionElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEBlendElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEColorMatrixElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEComponentTransferElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFECompositeElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEConvolveMatrixElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDiffuseLightingElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDisplacementMapElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDistantLightElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDropShadowElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFloodElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncAElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncBElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncGElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncRElement
