### ISSUE TITLE
SVG: Update low priority API pages [5/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#184]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern MDN API layout pages.

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEGaussianBlurElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEImageElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMergeElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMergeNodeElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMorphologyElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEOffsetElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEPointLightElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFESpecularLightingElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFESpotLightElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFETileElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFETurbulenceElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFilterElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFilterPrimitiveStandardAttributes
