### ISSUE TITLE
SVG: Add example on top of low priority API pages [5/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#185]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEGaussianBlurElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEImageElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMergeElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMergeNodeElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEMorphologyElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEOffsetElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEPointLightElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFESpecularLightingElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFESpotLightElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFETileElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFETurbulenceElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFilterElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFilterPrimitiveStandardAttributes
