### ISSUE TITLE
Display options for MDN auth on Sign In landing page

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1855]
# User story
As a user, I want to have options other than Github to sign in to MDN, so that I can utilize my Google account if I want.

# Acceptance criteria

- [ ] Includes option for Github
- [ ] Includes option for Google
- [ ] If a user has already authorized with one of these services (and is currently logged in to that service), can we bypass this screen and sign them in automatically (similar to how it behaves for Github today)? _does this need to be its own story?_

# Tasks

- [ ] Options displayed and styled as designed (new button styles included below)
- [ ] Options appear within a div with supporting copy (heading and paragraph)
- [ ] Options link off to their respective authorization pages

# Design

InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/370705984_Sign_In
Zeplin: https://zpl.io/2jYxyzq

Mobile version (without header/footer): https://zpl.io/Vxwepgw
