### ISSUE TITLE
Inform users of benefits of an MDN account on Sign In landing page

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1856]
# User story
As a user, I want to understand what the benefits are for having an MDN account, so I can be informed while making my decision of whether or not to do so.

# Acceptance criteria

- [ ] Displayed to the right of the sign in options on the landing page

# Tasks

- [ ] Finalize content (Kadir)
- [ ] Display benefits content as designed

# Design

InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/370705984_Sign_In
Zeplin: https://zpl.io/2jYxyzq

Mobile version (without header/footer): https://zpl.io/Vxwepgw
