### ISSUE TITLE
Display step progress on Create MDN Profile page

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1857]
# User story
As a user, I want to understand where I am at in the process of creating an MDN account, so that I know that I am almost complete with the process.

# Acceptance criteria

- [ ] First step displays authorized by Github or Google (whichever they performed)
- [ ] Displays the auth service's respective logo in first step
- [ ] Second step (current step on page) is "Create MDN Profile"
- [ ] Displays user avatar pulled from Github or Google in the second step (if available), otherwise display MDN's default avatar (dino head)
- [ ] Shows indicator that the first step is complete (checkmark)

# Tasks

- [ ] This is an incomplete task.

# Design

Github Auth:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368129372_Create_Account_-_MDN_Profile

Google Auth:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/370705985_Create_Account_-_MDN_Profile_-google-

Avatar Available:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/374095626_Create_Account_-_MDN_Profile_-alt_-_With_Pic-

**Comment by tobinmori** [comment]
Currently blocked by #mozilla/kuma/5888

**Comment by jmswisher** [comment]
To be continued.
