### ISSUE TITLE
Provide sensible defaults for user's username and email address on Create MDN Profile page

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1858]
# User story
As a user, I want MDN to default my username and email address to what is used in the auth service I am utilizing, so that this process is quick and painless.

# Acceptance criteria

- [x] If authenticating with Github, utilize the username from that account and display as read-only
- [ ] If authenticating with Google, username field is open for the user to enter the username they would like to use (there are no usernames in Google) _confirm with Kadir that we don't just want to strip the '@gmail.com' portion and display that as the username_
- [x] When defaulting to a username, display "Change Username" link next to the read only field, which would open a textfield where they could change it to a custom name
- [x] Default the email address to the primary email address pulled from the auth service, and display as read-only
- [x] Display "Change Email" link next to the read-only email address, which would display all verified email addresses pulled from the auth service as radio options, with the last option being "Other" where they can enter a custom email address.
- [ ] If the username pulled from the auth service is already taken on MDN, present the blank field instead of the default username in that instance.

# Tasks
*If relevant, you can make a checklist for tasks.*

- [ ] This is an incomplete task.

# Design

Default Username and Email Address (Github example):
InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368129372_Create_Account_-_MDN_Profile
Zeplin: https://zpl.io/2jYxqKp

Default Email Address only (Google example):
InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/370705985_Create_Account_-_MDN_Profile_-google
Zeplin: https://zpl.io/VOA8L3r

After choosing to change both:
InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/372750123_Create_Account_-_MDN_Profile_-_Change
Zeplin: https://zpl.io/25Avz5o

Username taken (Github example):
InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/374095520_Create_Account_-_MDN_Profile_-username_Taken-
Zeplin: https://zpl.io/25Avz5o

Username - Error:
InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/374829956_Create_Account_-_MDN_Profile_-_Error
Zeplin: https://zpl.io/adN5K8K

Mobile version of page (excluding header/footer): https://zpl.io/2v0ejgQ

**Comment by schalkneethling** [comment]
In the acceptance criteria, there is mention of Google sign-in. I am thinking we want that split out from this so the focus is on improving the existing flow and then, we can focus on adding an additional auth provider? @atopal

**Comment by schalkneethling** [comment]
Also, does this include the work to pull your avatar from Github/Google or, will this be Gravatar based?

**Comment by nickbrandt** [comment]
@schalkneethling agreed on the Google work, I should have broken that out into a separate story for once we have added Google as an authentication method. 

As for the avatar, I had included that as part of the steps story (https://github.com/mdn/sprints/issues/1857), as that is where we are displaying the avatar. If it makes sense to including pulling the avatar in this story, then we can add it here.

**Comment by schalkneethling** [comment]
> As for the avatar, I had included that as part of the steps story (#1857), as that is where we are displaying the avatar. If it makes sense to including pulling the avatar in this story, then we can add it here.

Thanks, @nickbrandt, I would limit the scope for this one as much as possible. If we, therefore, can stick with Gravatar for this one that it would be preferable.

**Comment by schalkneethling** [comment]
After having talked some over here we have identified two work items that needs to be done/defined over and above the work currently in this issue:

1. How do we test the account flow locally while working on implementing the new design? @peterbe Has some ideas we need to explore.
2. When a user wants to sign up for a new account, we do not want them to be directed to the `wiki` domain but remain on the main devmo domain
3. Do we:
3.1 Implement this in React
3.2 Implement it purely in Jinja/Django
3.3 A combination of React and Jinja/Django (think the current homepage).

**Comment by jmswisher** [comment]
@schalkneethling My notes from the End-of-sprint review meeting say this issues is Done. Is that correct?

**Comment by schalkneethling** [comment]
> @schalkneethling My notes from the End-of-sprint review meeting say this issues is Done. Is that correct?

Nope, my bad :/ I will add it to the next sprint as it is the logical next step with regards to the new account flow. Thanks for reaching out @jmswisher

**Comment by schalkneethling** [comment]
@jmswisher - After mentally stepping through the work it will take to implement this and creating the relevant issue on the Kuma side(https://github.com/mozilla/kuma/issues/5909), I realized that there is additional upfront work required to be able to test this locally.

Taking that into account and the work on implementation, this will have to wait until the next sprint. I have therefore removed this from any milestone, and also did not add the issue on the Kuma side to any milestone.

**Comment by atopal** [comment]
I think we can consider this done.
