### ISSUE TITLE
Allow user to opt-in to MDN news and promotional emails

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1859]
# User story
As a user, I want to be able to opt-in to emails about MDN news and promotions, so that I can be up to date on what's happening on MDN if I choose.

# Acceptance criteria

- [ ] Display checkbox on Create MDN Profile page
- [ ] Display checkbox on MDN Profile page (in personal section)
- [ ] If this option is checked on the Create MDN Profile page, this is reflected on the MDN Profile page after the account has been created
- [ ] This option is stored as a flag in the db that we can reference when sending out emails

# Tasks

- [ ] Finalize copy (Kadir)

# Design

Create MDN Profile Page:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368129372_Create_Account_-_MDN_Profile

Profile Page (personal section):
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/372750124_Account_-_Profile_-_Filled

**Comment by jmswisher** [comment]
To be continued in next sprint.
