### ISSUE TITLE
SVG: Update low priority API pages [6/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#186]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern MDN API layout pages.

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGColorProfileElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceFormatElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceNameElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceSrcElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceUriElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGGlyphElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGHKernElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMissingGlyphElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGVKernElement
