### ISSUE TITLE
As a user I want a streamlined account creation experience, so I can get started quickly

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1860]
# User story
As a user, I want the instructions and help text to be simple and to the point when creating an account on MDN, so that I can get through this process quickly and easily.

# Acceptance criteria

- [ ] Instruction content above fields is simplified to provided copy (Kadir to approve)
- [ ] Help text for trouble creating an account is moved to underneath submit button
- [ ] Remove the checkbox to make your Github URL public
- [ ] Update the help text for the username and email address fields (Kadir to approve)
- [ ] Simplify submit button text to "Create profile"

# Tasks

- [ ] Include any tasks here...

# Design
InVision: https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/368129372_Create_Account_-_MDN_Profile
Zeplin: https://zpl.io/2jYxqKp

Mobile Version (without header/footer): https://zpl.io/2v0ejgQ

**Comment by schalkneethling** [comment]
After having talked some over here we have identified two work items that need to be done/defined over and above the work currently in this issue:

How do we test the account flow locally while working on implementing the new design? @peterbe Has some ideas we need to explore.
When a user wants to sign up for a new account, we do not want them to be directed to the wiki domain but remain on the main devmo domain
Do we:
3.1 Implement this in React
3.2 Implement it purely in Jinja/Django
3.3 A combination of React and Jinja/Django (think the current homepage).

**Comment by schalkneethling** [comment]
PR - https://github.com/mozilla/kuma/pull/5659

**Comment by schalkneethling** [comment]
> 3\. Do we:
>     3.1 Implement this in React
>     3.2 Implement it purely in Jinja/Django
>     3.3 A combination of React and Jinja/Django (think the current homepage).

During the workweek in Portland, we thought it would be ok to simply update the styling for the main content of the page for the new flow. After starting work on this I felt that it would be much better to rather opt for option 3.3. The discussion around this is currently happening on https://github.com/mozilla/kuma/issues/5660
