### ISSUE TITLE
SVG: Add interactive example on top for high priority element pages [1/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#188]
**Task**
Make examples on top interactive for each pages

**Pages**
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/ellipse
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polygon
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg
