### ISSUE TITLE
SVG: Add interactive example on top for high priority element pages [2/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#189]
**Task**
Make examples on top interactive for each pages

**Pages**
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/pattern
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text
- [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath
