### ISSUE TITLE
SVG: Add interactive example on top for high priority attribute pages [1/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#190]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/cx
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/cy
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dx
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dy
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/height
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pathLength
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/points
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/rx
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/ry
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x1
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x2
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y1
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y2
