### ISSUE TITLE
SVG: Add interactive example on top for high priority attribute pages [2/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#191]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dashoffset
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-opacity
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width
