### ISSUE TITLE
SVG: Add interactive example on top for high priority attribute pages [3/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#192]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clipPathUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-path
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/mask
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/maskContentUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/maskUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternContentUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternTransform
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-end
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-mid
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-start
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerHeight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerWidth
