### ISSUE TITLE
Design for MDN promotional newsletter subscription welcome email

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1927]
# User story
As a user, I want to receive an email upon signing up for MDN news and events, so that I know I have been successfully added to the list and understand additional details about what sort of information MDN will be sending me.

# Acceptance criteria

- [x] Provides user with details about what sorts of information MDN will be sending them
- [x] Provides a way for the user to unsubscribe to the list

# Tasks

- [x] Create content for the email
- [x] Create design for the email
- [x] Review with product (Kadir)
- [ ] Review content with Janet

# Design
InVision:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/379683162_Welcome

# Content
https://docs.google.com/document/d/1GIjh6M8lZMYp-39eTXoGC4Osaypswk8IsYZx1pFFeo8/edit?usp=sharing

**Comment by nickbrandt** [comment]
@jmswisher would you mind reviewing the content for this email (link is in description). You can also view the design with the InVision link. Thanks!

**Comment by jmswisher** [comment]
Updated with suggested new text.
