### ISSUE TITLE
Design for MDN promotional newsletter cancelation/unsubscribe email

### ISSUE THREAD

**Issue by nickbrandt** [mdn/sprints#1928]
# User story
As a user, I want to receive an email upon canceling/unsubscribing to MDN news and events, so that I know I have been successfully removed from the list and will no longer receive promotional emails from MDN.

# Acceptance criteria

- [x] Provides user with confirmation that they have been unsubscribed to promotional emails

# Tasks

- [x] Create content for the email (who is this assigned to?)
- [x] Create design for the email
- [x] Review with product (Kadir)
- [ ] Review content with Janet

# Design
InVision:
https://mozilla.invisionapp.com/share/Y8SGMKQBCW3#/379683161_Unsubscribe

# Content
https://docs.google.com/document/d/1GIjh6M8lZMYp-39eTXoGC4Osaypswk8IsYZx1pFFeo8/edit?usp=sharing

**Comment by nickbrandt** [comment]
@jmswisher would you mind reviewing the content for this email (link is in description). You can also view the design with the InVision link. Thanks!

**Comment by jmswisher** [comment]
Updated with suggested new text.
