### ISSUE TITLE
SVG: Add interactive example on top for high priority attribute pages [4/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#193]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/direction
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-family
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-size
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-stretch
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-style
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-variant
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-weight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-decoration
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/textLength
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/word-spacing
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/writing-mode
