### ISSUE TITLE
Source Partner Content

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#1935]
For learning pathways we have identified content areas and content that we will want to source from potential partners. We now need to identify and prepare partners for an inclusion in the launch

# Acceptance criteria

- [ ] Identify at least one partner for a vendor review
- [ ] Perform vendor review with at least one partner
- [ ] Perform RRA with at least one partner

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by chrisdavidmills** [comment]
The one main module that we'd like to use a partner for is the Introduction to GitHub, and for that we'd like to partner with GitHub (Jess has contacts there)

**Comment by jmswisher** [comment]
@atopal, @chrisdavidmills This seems stalled -- how can we start moving it forward?

**Comment by chrisdavidmills** [comment]
@jmswisher apparently this can't happen; Christopher Arnold from the BizDev team looked into it, and legally and policy-wise it is too difficult. @atopal has more details.

I still don't really get what is stopping us from just linking to stuff. I'd still like to link to some GitHub learning material, at the very least, as my plan for GitHub coverage was to use external content, and if we can't use external content, then I have no plan. I was going to talk to Jess about this next week.

**Comment by jmswisher** [comment]
@atopal Should this issue move into Queen Latifah, or be parked until Ali makes a decision?

**Comment by atopal** [comment]
She made a decision: we are not moving forward with this.
