### ISSUE TITLE
SVG: Add interactive example on top for high priority attribute pages [5/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#194]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/id
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/class
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/display
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/style
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/tabindex
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/cursor
