### ISSUE TITLE
SVG: Add interactive example on top for high priority attribute pages [6/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#195]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filter
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/radius
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/refX
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/refY
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/opacity
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/visibility
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overflow
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/paint-order
