### ISSUE TITLE
Need a page about setting up Network debugging

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#1976]
# User story
As a developer, I want to be able to setup network debugging, to debug over a local network. Need to create a page to describe this situation.

Document with background information:
- [Debug a local Firefox using about:debugging](https://gist.github.com/juliandescottes/b0d3d83154d9ea8a84db5d32aa35d2c1)
- []()

# Acceptance criteria

- [x] New page has been created.
- [ ] Page has been reviewed by remote debugging team
- [ ] Links to this page have been added to the main remote debugging page

# Tasks

1. - [ ] Content added to existing page
2. - [ ] Instructions have been tested on macOS, Linux, and Windows
