### ISSUE TITLE
SVG: Add interactive example on top for medium priority element pages [4/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#201]
**Task**
 Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateColor
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateMotion
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mpath
