### ISSUE TITLE
Prep for integration with Salesforce

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#2044]
# User story
As an MDN dev I want to know how to integrate with Salesforce, so we can sign people up for our emails

# Acceptance criteria

- [x] LCM team/pmac has shared what the necessary steps are
- [x] MDN developers are aware and have reviewed the steps
- [x] user stories are written for the next sprint

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by tobinmori** [comment]
Kadir, I checked out the wireframes noted above in Nick's user story and have a question-

How will end users unsubscribe? 

There are easier and more challenging ways to do this:
1) allow user to unsubscribe via 'unsubscribe' link at bottom of email (easy, no work needed on our end)
2) providing an MDN interface that allows them to unsubscribe (more work - we need UX for this would need to store user's email UID); and depending on the interface things can get more or less complex. 

The answer here will affect the technical user stories that need to be written for this.

**Comment by atopal** [comment]
Let's do it from the email.

**Comment by tobinmori** [comment]
@atopal one other question - the design comps show the Email Newsletter. Do we have comps for the screens where the user actually subscribes?

**Comment by tobinmori** [comment]
all steps have been completed. @escattone will take this on in #5792
