### ISSUE TITLE
Review Signaling tool

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#2057]
# User story
As an MDN user I want a simple way to provide feedback about BCD issues, so they can be properly prioritized by the BCD maintainers

# Acceptance criteria

- [ ] signaling tab is shown on all browser compat data tables
- [ ] tab slides open to reveal browser icons
- [ ] clicking browser icons marks them as selected
- [ ] user can choose affected feature in drop down
- [ ] users can add explanation
- [ ] users get reminders when mandatory explanation is not provided
- [ ] users can add additional text material
- [ ] submitting report adds the data to the MDN database
- [ ] MDN maintainers can see data in django admin 

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

# Design
* see [Miro](https://miro.com/app/board/o9J_kx62CPY=/)

**Comment by schalkneethling** [comment]
@escattone If you have some free cycles, I would appreciate the help.

**Comment by tobinmori** [comment]
This works only involves PR reviews from @escattone, so closing.
