### ISSUE TITLE
As a PM I want the content on staging to be similar to production, so I can verify features before they go to production.

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#2060]
# User story
As a PM I want the content on staging to be similar to production, so I can verify features before they go to production.

# Acceptance criteria

- [ ] developer.allizom.org has the same content as developer.mozilla.org
- [ ] user permissions are the same between production and staging
- [ ] on the first of every month production content is synced over to staging

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.
