### ISSUE TITLE
Quarterly planning for Q4

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#2080]
# User story
As the MDN PM I want an OKR doc for Q4, so we can start sprint planning

# Acceptance criteria

- [x] Objectives in spreadsheet
- [x] KRs in Spreadsheet
- [x] Scoring in spreadsheet
- [ ] all KRs have docs

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by jmswisher** [comment]
Moving this to Queen Latifah, as the ACs are not done.

**Comment by jmswisher** [comment]
@atopal I think there is now scoring for all KRs in the spreadsheet, but I don't think they all have docs.
