### ISSUE TITLE
SVG: Add interactive example on top for medium priority API pages [1/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#209]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateColorElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateMotionElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimateTransformElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimationElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGCursorElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGDefsElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGForeignObjectElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGGradientElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGLinearGradientElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGRadialGradientElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMarkerElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGScriptElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSetElement
