### ISSUE TITLE
SVG: Add interactive example on top for low priority attribute pages [2/4]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#214]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/externalResourcesRequired
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/requiredExtensions
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/requiredFeatures
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/systemLanguage
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/solid-color
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/solid-opacity
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/white-space
