### ISSUE TITLE
Create the forms epic

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#2151]
Write an outline for the Forms area.
Create tickets for the work.

outline currently looks something like this:

HTML forms (25-30 hrs) (already available at https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms, but this could really do with some improvement; in fact, I think this could do with being in a separate place to HTML, CSS, or JS, as it covers aspects of all three. The below article titles describe what I think the course should cover, not what it necessarily does cover)

* [X] HTML forms overview
* [X] [Your first HTML form](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Your_first_HTML_form)
* [ ] Making selections: radio buttons, checkboxes, selects, and datalists
* [ ] Special text fields: search, passwords, urls, and more
* [ ] Collecting numbers, choosing from ranges and dates (also include meters/progress)
* [ ] How to structure an HTML form
* [X] Sending form data
* [ ] Form validation
* [ ] How to build custom form widgets
* [ ] Sending forms through JavaScript
* [ ] Basic HTML form styling
* [ ] Other articles to cover styling “the more difficult ones”
* [ ] Assessments

-----

* [X] [Your first HTML Form](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Your_first_HTML_form)
* [X] [How to structure an HTML form](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form)
* [X] [Native Form Widgets](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/The_native_form_widgets)
* [X] [Sending form data](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_and_retrieving_form_data) made edits and created a task

**Comment by estelle** [comment]
[ ] - check https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Your_first_HTML_form "Smashing Magazine has very good articles about forms UX, but perhaps the most important is their Extensive Guide To Web Form Usability.
UXMatters is also a very thoughtful resource with good advice from basic best practices to complex concerns such as multi-page forms." to see if this is still good advice.
