### ISSUE TITLE
SVG: Add interactive example on top for low priority API pages [3/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#219]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMPathElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/TimeEvent
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMetadataElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSwitchElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGSymbolElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGTitleElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGDescElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedPreserveAspectRatio
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedTransformList
