### ISSUE TITLE
SVG: Add interactive example on top for low priority API pages [4/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#220]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGComponentTransferFunctionElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEBlendElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEColorMatrixElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEComponentTransferElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFECompositeElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEConvolveMatrixElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDiffuseLightingElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDisplacementMapElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDistantLightElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEDropShadowElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFloodElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncAElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncBElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncGElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFEFuncRElement
