### ISSUE TITLE
SVG: Add interactive example on top for low priority API pages [6/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#222]
**Task**
Make examples on top interactive for each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGColorProfileElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceFormatElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceNameElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceSrcElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGFontFaceUriElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGGlyphElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGHKernElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGMissingGlyphElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGVKernElement
