### ISSUE TITLE
Renew Akismet subscription, update Akismet account

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#225]
# User story
As a MDN maintainer, I want to retain the Akismet subscription on July 11 for another year, so I can monitor spam attempts.

As a Mozilla developer (MDN and AMO teams), I want to maintain the Akismet account, so that I use Akismet on other Mozilla properties and monitor classification performace.

# Acceptance criteria 

* A credit card is added to the Akismet account
* Akismet subscription is renewed on or before July 11, 2018
* AMO team has access to Akismet account
* akismet_mgrs@mozilla.com distribution list reflects current users of account
* Account contact will monitor communication and can escalate issues

# Tasks

* [x] Determine who will provide the credit card - *IT vendor management*
* [x] Get login credentials to credit card provider
* [x] Determine department(s) to pay for subscription - dev outreach
* [x] Add credit card to Akismet account
* [x] Confirm new renewal date
* [x] Get login credentials to AMO team
* [x] Determine owner, membership list of akismet_mgrs
* [x] Remove unneeded members from akismet_mgrs
* [x] Update contact info in Akismet account - *Set to me*
* [x] Add accounting to akismet_mgrs
* [x] Add AMO team to akismet_mgrs
