### ISSUE TITLE
Remove zone URLs and custom styles

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#229]
# User story
As a MDN maintainer, I want to remove Zone URL roots and custom styles, so that they are no longer a source of extra work and unexpected bugs.

# References
* [bug 1462475](https://bugzilla.mozilla.org/show_bug.cgi?id=1462475) - Remove URL roots for zones
* [bug 1469029](https://bugzilla.mozilla.org/show_bug.cgi?id=1469029) - Support selected CSS rules for the Add-ons zone

# Acceptance criteria
* "Vanity URLs" are redirects to the standard wiki URLs.
* Zones no longer have custom styling.
* Zone sidebars are converted to standard sidebars

# Tasks
* [x] Remove zone code and styles  - [PR 4853](https://github.com/mozilla/kuma/pull/4853)
* [x] Convert zone sidebars to standard KumaScript sidebars
* [x] Update wiki pages to use KumaScript sidebars
* [x] Add select zone styles back to CSS - [PR 4858](https://github.com/mozilla/kuma/pull/4858)
* [x] Update layout on [History of MDN](https://developer.mozilla.org/en-US/docs/MDN_at_ten/History_of_MDN) 
* [x] Update layout on [Mozilla/Connect](https://developer.mozilla.org/en-US/docs/Mozilla/Connect) ([thanks ExE-Boss](https://github.com/mozilla/kuma/pull/4853#discussion_r200823523))
* [x] Update scraper for zone removal
* [x] Remove zone usage
* [x] Remove zone table, zone nav field from database
* [x] Remove zone table from anonymized DB

**Comment by jwhitlock** [comment]
@escattone pushed the code to production, and flushed the CDN cache just in case. @wbamberg converted many sidebars, and added them to the relevant pages. I updated [History of MDN](https://developer.mozilla.org/en-US/docs/MDN_at_ten/History_of_MDN) to make sense without the custom styling, and @ExE-Boss fixed up [Mozilla/Connect](https://developer.mozilla.org/en-US/docs/Mozilla/Connect).

There's some known development tasks, to simplify the scraper and drop the zones data from the database. Are there other development, content, or documentation tasks to finish this work?

**Comment by wbamberg** [comment]
There aren't any more content tasks planned for this. If content issues come up I'd like to handle them as separate bugs.

**Comment by escattone** [comment]
@jwhitlock Other than the known development tasks you've already mentioned, I don't know of any others that are needed.

**Comment by jwhitlock** [comment]
Zones are removed from the code, and zone tables are dropped in stage and production.
