### ISSUE TITLE
WebXR: Finish the overview page [MVP]

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2293]
The WebXR Device API overview page has a good bit of info; possibly too much. Evaluate what needs to be there and what should move to one of the subpages. Add needed links to new subpagess and generally ready the article for use.

## Tasks

- [x] Brief intro to WebXR
- [x] Offers links with short descriptions to all "top-level" members of the API (dictionaries, interfaces, globals, types, etc)
- [x] Offers links to subpages containing tutorial, example, and guide content
- [x] "See  also" links to relevant related APIs including canvas, WebGL, and so forth
- [x] Any useful information which is excessive for the intro page is moved to appropriate subpages
- [x] A helpful compatibility table is provided

## Things to remember
* Definitions of terms: spatial tracking / tracking, position and orientation, session, space and reference space, pose
* Be thorough without extending too far into general position and such.

## Acceptance criteria
- [ ] Content complete
- [ ] Links to all interfaces and types included in appropriate sections
- [ ] All guide and tutorial content listed appropriately
- [ ] All appropriate links to outside-WebXR documentation included

**Comment by Elchi3** [comment]
This was marked as done in the "Golf Hotel" sprint, so I'm closing this.
