### ISSUE TITLE
Update Kuma to Python 3

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#230]
# User story
As a MDN developer, I want Kuma to run under Python 3 by the end of 2018, to be on a current Python release and to be ready for Django 2.2.

# References
* [bug 1467518](https://bugzilla.mozilla.org/show_bug.cgi?id=1467518)

# Acceptance criteria
Kuma runs in development and production on Python 3 and Django 1.11

# Tasks
* [x] Add Python 3 optional build to TravisCI
* [x] Convert backend from django-memcached-hashring to supported backend - [PR 4870](https://github.com/mozilla/kuma/pull/4870)
* [x] Retire ``ok_()`` test function - 
* [x] Retire ``eq_()`` test function - [PR 4869](https://github.com/mozilla/kuma/pull/4869)
* [x] Get migrations working with Python 3
* [x] Tests passing in ``attachments`` app
* [x] Tests passing in ``authkeys`` app
* [x] Tests passing in ``core`` app
* [x] Tests passing in ``dashboards`` app
* [x] Tests passing in ``feeder`` app
* [x] Tests passing in ``health`` app
* [x] Tests passing in ``humans`` app
* [x] Tests passing in ``landing`` app
* [x] Tests passing in ``redirects`` app (*note: no tests, but updated*)
* [ ] Tests passing in ``payments`` app
* [ ] Tests passing in ``scrape`` app
* [ ] Tests passing in ``search`` app
* [ ] Tests passing in ``spam`` app
* [ ] Tests passing in ``users`` app
* [ ] Tests passing in ``version`` app
* [ ] Tests passing in ``wiki`` app
* [ ] Switch Docker images to Python 3

**Comment by MatonAnthony** [comment]
Retire `ok_()` and `eq_()` test functions have been merged to `master` and are already in production.
