### ISSUE TITLE
Update front-end development workflow

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#231]
# User story
As a front end developer, I want a better integrated development environment by the end of 2018, so that I can more rapidly make changes.

# Acceptance criteria
* [x] Goal: There is one place to add and update front-end tools (https://github.com/mozilla/kuma/pull/4852)
* [ ] Goal: No host installs are *required* for front-end development except for Docker
* [ ] A node-based tool chain, not ``django-pipeline``, is used to process assets (see [bug 1380419](https://bugzilla.mozilla.org/show_bug.cgi?id=1380419), [Taiga US 1799](https://tree.taiga.io/project/viya-mdn-durable-team/us/1799)
* [ ] Assets continue to have unique names based on contents and long cache lifetimes
* [ ] Front-end development documentation is up-to-date

**Comment by tobinmori** [comment]
Closing because this is old.
