### ISSUE TITLE
Document XRRigidTransform

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2335]
While the main page exists, it's incomplete, and none of the subpages have been written yet.

# Tasks

- [x] Add more explanatory introduction text
- [x] Add example
- [x] Document the constructor
- [x] Document the `position` property
- [x] Document the `orientation` property
- [x] Document the `matrix` property
- [x] Document the `inverse` property
- [x] Ensure cross links are in place as appropriate
- [x] Submit to engineers for review
