### ISSUE TITLE
Document XRWebGLLayer

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2340]
Fully document the `XRWebGLLayer` interface. The main page has been created but needs to be reviewed and completed. None of the subpages have been created.

# Tasks

- [ ] Document the `XRWebGLLayerInit` dictionary
- [ ] Document the constructor
- [ ] Document the `antialias` property
- [ ] Document the `ignoreDepthValues` property
- [ ] Document the `framebuffer` property
- [ ] Document the `framebufferWidth` property
- [ ] Document the `framebufferHeight` property
- [ ] Document the `getViewport()` method
- [ ] Document the `getNativeFramebufferScaleFactor() static method
- [ ] Ensure cross links are provided as appropriate
- [ ] Ensure the guide content explains this interface and its use
- [ ] Submit to devs for review
