### ISSUE TITLE
Publish June 2018 MDN Changelog

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#239]
# Acceptance criteria
* June 2018 Changelog is published on Hacks on July 6
* Post is promoted on Twitter and Discourse

# Tasks
- [ ] Gather things that shipped and July plans
- [ ] Submit draft to Havi
- [ ] Approve final draft for publishing
- [ ] Publish July 6
- [ ] Reshare on Twitter
- [ ] Update [Discourse post](https://discourse.mozilla.org/t/mdn-changelog-2018/25271)
