### ISSUE TITLE
Set up framework for scraping and linting wiki content

### ISSUE THREAD

**Issue by ddbeck** [mdn/sprints#2411]
# User story
As an author or developer, I want to be able to develop new scrapers and linting for content on the wiki, so I can improve content quality, work with raw HTML wiki dumps, or ingest content into stumptown.

# Acceptance criteria

- [ ] running a `node` or `npm` command that scrapes a wiki page into Markdown with frontmatter (scraping mode)
- [ ] running that same command in a no-op mode that reports on one or more problems (linting mode)
- [ ] the code is accompanied by a file that provides guidelines or hints for adding additional structures and checks (e.g., for #2410)

# Tasks

Some implementation notes here:

1. - [ ] Use unified framework's `vfile` for reporting

**Comment by wbamberg** [comment]
As discussed: although we haven't done all the things in the original scope of this, we have landed a useful piece of it, and we now have a couple of user stories for the next pieces:
* https://github.com/mdn/sprints/issues/2518
* https://github.com/mdn/sprints/issues/2519

So let's call this one closed.
