### ISSUE TITLE
Dev Tools audit and plan

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#242]
# User story
As an MDN reader, I want to understand the Dev Tools available to me, so I can make the best use of my debugging time.

Audit existing Dev Tools documentation and determine where there are holes or inaccuracies.
|Develop a specific plan for improvement.

# Acceptance criteria
*A reviewed and verified plan for updating/improving the existing Dev Tools documentation.*

# Tasks
- [x] Perform audit of existing documentation, include areas needing update or improvement.
- [x] Write plan for implementing suggested/needed changes.
- [ ] Review plan and create issues to make updates/changes.

**Comment by irenesmith** [comment]
I've created a folder on my Google Drive where I can store all documents related to DevTools. The Audit and Plan information will be stored there.

[DevTools Documents](https://drive.google.com/drive/folders/1mYG6F--pnAA0SmaI2STh8Tlv_bAT5Y_o?usp=sharing)

**Comment by jmswisher** [comment]
@irenesmith, @chrisdavidmills Can this issue be closed? The folder link above takes me to a "Web Architecture" folder.

**Comment by irenesmith** [comment]
Wow! I never noticed that was wrong. It's supposed to point to a different folder. I fixed the link for historical purposes but I think this can be closed because I have several tasks that will act on the decisions made here.
