### ISSUE TITLE
As the PM I want our new user flow to be instrumented so we can identify bottle necks

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#2436]
# User story
As the PM I want our new user flow to be instrumented so we can identify bottle necks

# Context
We have a new user flow that will hopefully allow more users to easily get an MDN account. We have already talked about some potential confusing screens. Instrumenting the flow should allow us to identify issues and check whether our optimizations are working. 

## My questions:
1. How many people have tried to sign up to MDN on any given day (not sign in to an account)?
2. How many people have tried to sign in to MDN on any given day?
3. How many users chose Google to sign up? 
4. How many users chose Github to sign up? 
5. How many users signed in with Google? 
6. How many users signed in with Github? 
7. How many Google users came back to create their profile?
8. How many Github users came back to create their profile?
9. How many people clicked to edit their username?
10. How many people clicked to change their email address?
11. How many people saw a username error?
12. How many people saw an email error?
13. How many people opted in to receive news?
14. How many people opted out of receiving news?
15. How many people ended up creating an account?
16. How many people ended up creating an account authenticated with Google?
17. How many people ended up creating an account authenticated with Github?

## Breakdown for events
category | action | label
3. signup-flow | sign-up | Google
4. signup-flow | sign-up | Github
5. signup-flow | sign-in | Google
6. signup-flow | sign-in | Github
7. signup-flow | profile-audit | Google
8. signup-flow | profile-audit | Github
9. signup-flow | profile-edit | username edit
10. signup-flow | profile-edit | email edit
11. signup-flow | profile-edit-error | username
12. signup-flow | profile-edit-error | email
13. signup-flow | free-newsletter | opt-in
14. signup-flow | free-newsletter | opt-out
16. signup-flow | profile-created | Google
17. signup-flow | profile-created | Github

# Acceptance criteria
- [ ] sign-up events are implemented
- [ ] sign-in events are implemented
- [ ] profile events are implemented
- [ ] newsletter events are implemented
- [ ] test run successfully documented
- [ ] Google analytics dashboard created for analysis

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.
