### ISSUE TITLE
Quarterly Planning for Q1 2020

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#2553]
# User story
As the MDN PM I want an OKR doc for Q4, so we can start sprint planning

# Acceptance criteria

- [x] Objectives in spreadsheet
- [x] KRs in Spreadsheet
- [ ] Scoring in spreadsheet
- [ ] all KRs have docs

# Tasks
*If relevant, you can make a checklist for tasks.*

- [x] Draft 2020 OKRs
- [x] Share 2020 OKRs with Chris and Tobin
- [x] Incorporate feedback
- [x] Share 2020 OKRs with Ali
- [x] Incorporate feedback
- [x] Break annual OKRs down into Q1 objectives
- [x] Break down Q1 objectives into Q1 KRs
- [x] Share OKRs with Chris and Tobin
- [x] Incorporate feedback
- [ ] Share OKRs with team
- [ ] Incorporate feedback
