### ISSUE TITLE
break out of iframe to work with instead of against browser

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#264]
Tasks:
- [ ]

Acceptance Criteria:
- [ ] Interactive example is requested earlier and loads faster
- [ ] security concerns are considered in solution
- [ ] contribution workflow concerns are considered in solution
- [ ] performance impact reported
