### ISSUE TITLE
WebXR: Document XRWebGLLayer

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2663]
The main page for this and most of its properties are documented (though all should be reviewed). However, neither of the methods are documented yet. Finish this up.

https://developer.mozilla.org/en-US/docs/Web/API/XRWebGLLayer

## Tasks

- [x] Document getViewport()
- [x] Document getNativeFramebufferScaleFactor()
- [x] Review existing pages
- [x] Make sure BCD is good to go
- [x] Make sure there are appropriate examples in place
- [x] Make sure there are appropriate cross-references between this and other content including WebGL; should be bidirectional

## Acceptance criteria

- [ ] All tasks are done and content is readable and accurate
- [ ] Submitted for engineering review
