### ISSUE TITLE
Implement tools/documents for new sprint process

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#2670]
# User story
As an MDN team member, I want to have tools in place to track sprints when we start the new sprint process and cadence, so the transition goes smoothly, without losing information. 

# Acceptance criteria

- [ ] Documents and/or tools corresponding to the current ones exist for both the Dev team and the Content team.

These include:
- [x] OKR spreadsheet
- [x] Planning scratchpad
- [x] User story spreadsheet
- [x] Availability spreadsheet
- [x] Retrospectives (Trello board)

# Tasks

1. - [x] Talk to Kadir, Chris and Tobin about needs for these items.
2. - [x] Draft new documents.
3. - [x] Share for and incorporate feedback.
4. - [x] Share to team for going forward.

**Comment by jmswisher** [comment]
- [OKR spreadsheet](https://docs.google.com/spreadsheets/d/1agrldRIU6UO7-zhFs2-KxVkLRW12sG9JEsd_M6oPXtc/edit?usp=sharing)
- [Content planning scratchpad](https://docs.google.com/document/d/1KgE8CIAxumPrObd5PdHjSPVJvl0inw7W2uOfN_jumP4/edit?usp=sharing)
- [Dev planning scratchpad](https://docs.google.com/document/d/10dqEFKXgbPI9ZAv4vDQ8ZzI3Br9Pj8bEjbp6LUjWlho/edit?usp=sharing)
- [User story spreadsheet](https://docs.google.com/spreadsheets/d/1Mg9hRtaH32BRbCGygtYm_w4zsneCvIGDOJcBso9Rxao/edit?usp=sharing)
- [Availability spreadsheet](https://docs.google.com/spreadsheets/d/1nFUi34gG8bQLiqRwq74SE6giemFZl02h1u8Ra2qAUHQ/edit?usp=sharing)
- [Content retrospectives](https://trello.com/b/FMyNN0dq/mdn-content-retros)
- [Dev retrospectives](https://trello.com/b/SdgWb7Un/mdn-dev-retros)
- [Joint retrospectives](https://trello.com/b/PCiuLuDZ/mdn-joint-retrospectives) (same as old retro board)
