### ISSUE TITLE
Identify JS pages' corresponding recipe types

### ISSUE THREAD

**Issue by ddbeck** [mdn/sprints#2671]
With the stumptown-content linter, I want to be able to match a page to a [stumptown-content recipe](https://github.com/mdn/stumptown-content/tree/master/recipes) based on the page's tags, or be warned if it doesn't match.

Ideally, we'll learn how much work we'll need to do to tag or re-tag JS pages with enough information to assign recipes to all of them.

# Acceptance criteria

- [x] Running the linter, I get a warning or error if I can't match some cluster of tags to a recipe

# Tasks

- [x] Manually look at a sample of JS pages for each recipe type and decide on a tag signature for that recipe
- [x] Write some code to get tags from pages
- [x] Write a unified plugin that attaches some recipe metadata to the vfile
- [x] Do some sort of reality checking against the URL structure, to make sure recipe signatures make sense
- [x] Write or extend a unified plugin to warn about not matching a recipe

**Comment by wbamberg** [comment]
@ddbeck , it seems to be that https://github.com/mdn/stumptown-content/pull/288 completes this. Is that right, or was there something else to do here?

**Comment by ddbeck** [comment]
Yeah, I guess I've _technically_ satisfied the acceptance criteria https://github.com/mdn/stumptown-content/pull/288. But…

> Ideally, we'll learn how much work we'll need to do to tag or re-tag JS pages with enough information to assign recipes to all of them.

I haven't really done this part yet. Let's leave this open until the end of week—at very least, I expect I can produce a spreadsheet showing what recipes we're currently matching in the JS docs.

**Comment by ddbeck** [comment]
OK, here's a few more words to wrap this up.

I wrote some additional lists of tags for JS recipe types. Running against `/en-US/docs/Web/JavaScript`, I got:

```
Summary
Missing recipe                      175 errors  file-require-recipe       
One and only one recipe must apply  8 errors    file-require-recipe-unique

2 notice types (183 notices, ✖ 183 errors) in 917 files
```

I also generated [a spreadsheet](https://docs.google.com/spreadsheets/d/1O_B5XYYO94-Edr_Rk7NJLFR7qBfvUmlkxYCl9oJdd58/edit?usp=sharing) to show what reviewing this might look like.

On first glance, lots of the missing recipes will be for guides and landing pages. 175 pages is not so many that we could not manually tag them and get into a good position for scraping. Fixing the eight over matched pages should be a piece of cake.

I assume that some pages have been falsely identified, though I don't have an estimate for how many. I expect these false matches will eventually be revealed by other, more detailed checks. For example, when we ultimately scrape pages, we'll find that pages that are falsely identified for a recipe won't contain the right set of section headings.

Overall, I'm really happy with how this worked out. This seems like an approach we could actually use to scrape the JS pages. I'll go ahead and close this now.
