### ISSUE TITLE
As a web developer, I want MDN to tell me which browsers to support

### ISSUE THREAD

**Issue by malqinneh** [mdn/sprints#2676]
# Project documentation
[See project doc here](https://docs.google.com/document/d/1FzdyN-YXRLfu4I4xOhANb4I67IB7UiVmED4WCbg3mc8/edit?usp=sharing)

# User story
As a web developer, I want MDN to tell me which browsers to support so that I don’t have to select browsers myself.

# Acceptance criteria

- [ ] UX/UI mock-ups where MDN users (after sign-in) view the full list of default browsers that MDN recommends they should support
- [ ] PM has approved UX/UI mock-ups where MDN users (after sign-in) view the full list of default browsers that MDN recommends they should support
- [ ] Engineering team has UX/UI mock-ups where MDN users (after sign-in) view the full list of default browsers that MDN recommends they should support

# Tasks

1. - [ ] This is an incomplete task.

**Comment by jmswisher** [comment]
No longer valid
