### ISSUE TITLE
As a web developer, I want to specify which browser lists I need to support

### ISSUE THREAD

**Issue by malqinneh** [mdn/sprints#2677]
# Project documentation
[See project doc here](https://docs.google.com/document/d/1FzdyN-YXRLfu4I4xOhANb4I67IB7UiVmED4WCbg3mc8/edit?usp=sharing)

# User story
As a web developer, I want to specify which browser lists I need to support because I need to support specific browsers.

# Acceptance criteria

- [ ] UX/UI mock-ups where MDN users (after sign-in) can specify a list of browsers they want to support
- [ ] PM has approved UX/UI mock-ups where MDN users (after sign-in) can specify a list of browsers they want to support
- [ ] Engineering team has UX/UI mock-ups where MDN users (after sign-in) can specify a list of browsers they want to support

# Tasks

1. - [ ] This is an incomplete task.

**Comment by jmswisher** [comment]
No longer valid
