### ISSUE TITLE
As a web developer, I want MDN to tell me when the platform feature I’m looking at is problematic with specified browser list(s)

### ISSUE THREAD

**Issue by malqinneh** [mdn/sprints#2678]
# Project documentation
[See project doc here](https://docs.google.com/document/d/1FzdyN-YXRLfu4I4xOhANb4I67IB7UiVmED4WCbg3mc8/edit?usp=sharing)

# User story
As a web developer, I want MDN to tell me when the platform feature I’m looking at is problematic with specified browser list(s) so that I don’t waste time reading a platform feature that is not supported by specified browser list(s).

# Acceptance criteria

- [ ] UX/UI mock-ups where MDN users (after sign-in) are notified within platform feature pages regarding browser compatibility of the platform feature and the specified browser list.
- [ ] PM has approved UX/UI mock-ups where MDN users (after sign-in) are notified within platform feature pages regarding browser compatibility of the platform feature and the specified browser list.
- [ ] Engineering team has UX/UI mock-ups where MDN users (after sign-in) are notified within platform feature pages regarding browser compatibility of the platform feature and the specified browser list.

# Tasks

1. - [ ] This is an incomplete task.

**Comment by jmswisher** [comment]
No longer valid
