### ISSUE TITLE
As a web developer, I want to turn off the browser list feature

### ISSUE THREAD

**Issue by malqinneh** [mdn/sprints#2679]
# Project documentation
[See project doc here](https://docs.google.com/document/d/1FzdyN-YXRLfu4I4xOhANb4I67IB7UiVmED4WCbg3mc8/edit?usp=sharing)

# User story
As a web developer, I want to turn off the browser list feature so that it does not appear on platform feature pages.

# Acceptance criteria

- [ ] UX/UI mock-ups where MDN users (after sign-in) can turn off the browser list feature.
- [ ] PM has approved UX/UI mock-ups where MDN users (after sign-in) can turn off the browser list feature.
- [ ] Engineering team has UX/UI mock-ups where MDN users (after sign-in) can turn off the browser list feature.

# Tasks

1. - [ ] This is an incomplete task.

**Comment by jmswisher** [comment]
No longer valid
