### ISSUE TITLE
Provide guidance on (not) using placeholders

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#271]
https://bugzilla.mozilla.org/show_bug.cgi?id=1470321

### Tasks

- [x] Update `<input>` page; rewrite note about placeholder usage to recommend caution and reference a new section that will talk about labels and placeholders and using them properly.
- [x] Add a section “Labels and placeholders” to the `<input>` page, explaining why you should avoid placeholders and how to use them properly if you really really need to. Cover why to use labels instead and how to use them right.
- [x] Update the `<textarea>` article similarly

**Comment by a2sheppy** [comment]
I’ve made the initial pass at updating the description of `placeholder` on the `<input>` page, and have added the section [Labels and placeholders](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Labels_and_placeholders) with a good bit of text about this topic.
