### ISSUE TITLE
U - WebXR: Write Guide to lighting in AR and VR environments [MVP]

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2723]
Though we can largely leave lighting up to general WebGL documentation, there are aspects that are especially relevant to XR developers. Primarily, this includes things such as ensuring that the light sources are placed in ways that don't seem weird as the user moves around. For instance, if there's a light source in the middle of the room somewhere, it needs to either correspond with an object or be in a location the user can't access. Otherwise, the lighting can seem "off", especially when it transitions as they pass through or past the lighting source point.

_**Much of this content has to wait until the AR module comes out to see if there's anything good there we can use; some may need to hold off until the Hit Test Module, too, so that ray tracing can be used for light source management.**_

A potentially larger issue comes in with AR: when you add 3D imagery to the scene, if your lighting doesn't match that of the real world, your object is going to look strange or out of place. Certainly if you're attempting realism, it won't work if you don't match the lighting color, texture, and directionality.

These and any other lighting issues need to be covered.

## Tasks
This is not an exhaustive list as yet.

- [x] Intro to lighting; mostly the same as in any 3D graphics environment, but...
- [x] When possible, make light sources correspond to objects that emit light, instead of just being invisible light generators
- [x] Avoid viewer conflicts - ensure lights aren't placed in "impossible" spots, or spots that cause certain viewer positions to reveal the falseness of the lighting
- [x] In AR, ensure that your virtual light source matches the lighting of the real world as well as possible or your imagery will fail to fit in
- [x] Introduction to lighting estimation
- [x] Other lighting topics (temporal and spatial filtering, etc)
- [x] Security and privacy issues
- [x] (any other issues that need coverage)

## Acceptance criteria
- [x] Content written and understandable and accurate
- [x] Submitted to MR devs, GL devs, or other 3D expert for review
