### ISSUE TITLE
Document AudioTrack and AudioTrackList

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#273]
https://bugzilla.mozilla.org/show_bug.cgi?id=1454268

This is the HTML DOM `AudioTrack`, not the Media Capture and Streams `AudioStramTrack`. Represents an audio track on an HTML `<audio>` or `<video>` element.

### Tasks

- [x] Create overview page for `AudioTrack`
- [x] Document the 5 attributes of `AudioTrack`
- [x] Create overview page for `AudioTrackList`
- [x] Document the `length` attribute
- [x] Document the `getTrackById()` method
- [x] Document the indexed getter
- [x] Document the `onchange` event handler
- [x] Document the `onaddtrack` event handler
- [x] Document the `onremovetrack` event handler
- [x] Document the `change`, `addtrack`, and `removetrack` events
- [x] Make sure the `HTMLMediaElement.audioTracks` property is documented properly and links to the new content appropriately

**Comment by a2sheppy** [comment]
The indexed getter is as documented as we ever really do, by simply mentioning in all the right places that you can use that syntax to access items.

These docs are now complete. Hurray!

**Comment by a2sheppy** [comment]
(Reopened just to make sure it shows up under “Done” for now.
