### ISSUE TITLE
[WebAPI] general APIs, Fx 74 tasks

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#2743]
# Trello

https://trello.com/c/aBs1o6Pg/86-dom-general-enhancements-fx-74

# Tasks

- [x] [Consider firing languagechange events on workers](https://bugzilla.mozilla.org/show_bug.cgi?id=1154779)
- [x] [Set document.URL (location) to url of active document when navigation started for javascript:-generated documents per HTML5 (Nested javascript: iframe doesn't load, runs into nesting limit for frames with same URL)](https://bugzilla.mozilla.org/show_bug.cgi?id=836567)
- [x] [Disable toSource/uneval in non-chrome code](https://bugzilla.mozilla.org/show_bug.cgi?id=1565170)
- [x] [Unship HTMLCanvasElement.mozGetAsFile()](https://bugzilla.mozilla.org/show_bug.cgi?id=1588980)
- [x] [[UI Events][Input Events] implement beforeinput event](https://bugzilla.mozilla.org/show_bug.cgi?id=970802)

**Comment by a2sheppy** [comment]
* Made a few improvements to the article about the [beforeinput event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event)
* Added a row to the DOM section of the article [Experimental features in Firefox](//wiki.developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) describing this change
* Added the `dev-doc-needed` keyword to bug 1609291 (covering enabling the event by default)
