### ISSUE TITLE
Support services for subscriptions in place

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#2786]
# User story
As the MDN PM I want assurance that all supporting services for subscriptions are in place so we don't have unexpected surprises

# Acceptance criteria

- [ ] Legal has signed off on flow and implementation
- [ ] support has mailing list in place
- [ ] support has made decision on supporting launch or not
- [ ] accounting has signed off on revenue from Stripe

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by chinikes** [comment]
Hi @atopal - This user story is marked for Alfa. Want to confirm who in the Team it's being assigned to? Thanks

**Comment by atopal** [comment]
That's me.

**Comment by atopal** [comment]
Support is on board, legal has to review latest changes to the copy. Accounting is stuck.

**Comment by atopal** [comment]
Legal is okay with changes to copy. Just accounting left: tracked in https://biztera.com/projects/14879
