### ISSUE TITLE
U - Design guidelines for MDN footer to improve mobile SEO

### ISSUE THREAD

**Issue by malqinneh** [mdn/sprints#2799]
# User story
Design guidelines for MDN footer to improve mobile SEO

# Acceptance criteria

- [x] Design system guidelines and specs for desktop footer are accessible
- [x] Design system guidelines and specs for mobile footer are accessible
- [x] Schalk and Mindy approved desktop and mobile footer design spec

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [x] Desktop footer
2. - [x] Mobile footer
3. - [x] Update MDN design system Sketch file to include font styles and components
