### ISSUE TITLE
E - Explore Yari 1 Mitigations - L10n Tooling

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#2832]
# User story
As a ..., I want to ..., so I can ...

*Ideally, this is in the issue title, but if not, you can put it here. If so, delete this section.*

# Acceptance criteria

- [ ] This is something that can be verified to show that this user story is satisfied.

# Tasks
*If relevant, you can make a checklist for tasks.*

1. - [ ] This is an incomplete task.

**Comment by chinikes** [comment]
Hi @atopal - Please update this epic with your expectations on its output. including acceptance criteria - cc: @tobinmori Thanks!

**Comment by atopal** [comment]
AC: 
- [ ] we know what localizers want from a new process
- [ ] we have a pretty good idea of what state of art online l10n is
- [ ] Outline how the contribution workflow would work for contributors posting L10n content using Yari 1
