### ISSUE TITLE
Assign topic owners and 2nds for all MDN topic areas

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#288]
# User story
As a content lead, I want to share out responsibility for drive-by edits (and other content issues) among writers, so I can be sure all content edits are being reviewed.

# Acceptance criteria
* docs trees listed
* docs trees shared out
* docs trees watched

# Tasks
*If relevant, you can make a checklist for tasks.*
- [x] Audit and list all documentation trees (maybe reuse [Topic drivers and curators](https://developer.mozilla.org/en-US/docs/MDN/Community/Roles/Topic_driver_role/Drivers_and_curators))
- [x] Share them out sensibly among staff writers
- [x] Assign 2nd for each topic area
- [ ] Get all the staff writers to "watch" their areas of responsibility
