### ISSUE TITLE
E - Increase conversions (Incentivize Subscriptions) 

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#2900]
# Epic
As a PM I want to present potential subscribers with incentives to sign up to increase conversions 

# Acceptance criteria
- [x] Assign unique subscriber number for users that become monthly subscribers
- [x] Provide discount codes for subscribers to Spreadshirt merch
- [x] Invite subscribers to exclusive events and parties

**Comment by chinikes** [comment]
Hi @atopal , @malqinneh  - Are you guys on the same page with the ACs as added to this epic? cc: @tobinmori 

#2989 has been mapped for implementation in Delta. Any questions / objections?

**Comment by atopal** [comment]
Yes, I'm good with these

**Comment by tobinmori** [comment]
Good with me, but some question on discount code for @atopal @malqinneh 

- How are discount codes generated? (same for all, delivered to us? or need to be retrieved via API?)
- How are we delivering discount codes to customers (email?) 
- How are they redeemed?

**Comment by malqinneh** [comment]
Thanks for the questions Tobin! That's exactly the kind of information we would research for discount Spreadshirt codes and invites to MDN parties (they're in the investigation stage).

**Comment by tobinmori** [comment]
@chinikes I've ported over @malqinneh's user story for the first AC. #6732

Tasks are here:
#6731 needs to be done first (sprint Delta)
#6733 can be done once 6731 is complete. (most likely next sprint)
