### ISSUE TITLE
Document WebAssembly.Global

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#291]
WebAssembly.Global is being launched in Firefox 62, so we need to have it documented. See https://github.com/mdn/sprints/issues/290 for a starting point, and https://github.com/mdn/browser-compat-data/pull/2402 for useful notes.

# User story
As a web developer, I want to learn how to use new features of WebAssembly, so I can use them in my apps.

# Acceptance criteria
* All writing work done
* Review requested from a suitable engineer

# Tasks
- [x] Get description and minimal example from Luke Wagner, or another suitable engineer.
- [x] Write useful example for developers to follow and add it to https://github.com/mdn/webassembly-examples
- [x] Document WebAssembly.Global() constructor page
- [x] Document WebAssembly.Global.value
- [x] Document WebAssembly.Global.valueOf
- [x] Add section to https://developer.mozilla.org/en-US/docs/WebAssembly/Using_the_JavaScript_API to show how to use a global from JS-land
- [x] Add a section to https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format to show what globals look like on the WASM text format side
- [x] Add necessary links to https://developer.mozilla.org/en-US/docs/WebAssembly
