### ISSUE TITLE
Ensure MDN CI code works with IT's CI Service

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#293]
# User story
As an MDN developer, I want to ensure our CI code works within IT's CI infrastructure so that we can continue to run tests, send notifications to Slack and IRC, build and register Docker images, and deploy code.

# Acceptance criteria
* Jenkins service provided by IT with admin privileges for John and Ryan
* The Kuma `Jenkinsfile` runs successfully for the default case as well as the following custom branches:
    * master
    * stage-push
    * stage-integration-tests
* The Kumascript `Jenkinsfile` runs successfully for the default case as well as the following custom branches:
    * master
    * stage-push
* Notifications successfully sent to IRC #mdndev
* Docker images successfully registered on https://hub.docker.com/
* Successful deployments to new stage instance
* Follow-on tasks are documented with the migration team

# Tasks
- [ ] Verify access to Jenkins service
- [ ] Configure Jenkins (e.g., connect to MDN's Kuma and Kumascript GitHub repos) (mostly IT?)
- [ ] Create DockerHub account for MDN and give credentials to John and Ryan
- [ ] Modify [new stage set-up](https://github.com/mdn/infra/blob/master/apps/mdn/mdn-aws/k8s/regions/oregon/stage.sh) to use DockerHub rather than quay.io
- [ ] Test both the Kuma and Kumascript `Jenkinsfile` (as detailed in the acceptance criteria)

Tracked also in [MDN migration project](https://waffle.io/mozilla-itcloud/mdn-migration-project), e.g. [Build Out CI Jobs](https://github.com/mozilla-itcloud/mdn-migration-project/issues/12).

**Comment by jwhitlock** [comment]
Incomplete, need to restart task with fresh infrastructure. Now tracked in  https://github.com/mdn/sprints/issues/293
