### ISSUE TITLE
Make GitHub changes to support doc issue process

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#295]
# Acceptance criteria
- A repo for dev doc issues has been selected/created.
- An issue template for dev doc issues is available.

# Tasks

- [x] Reach a decision on a repo to use for doc issues.
- [ ] If necessary, create the repo.
- [x] Create an issue template similar to the [Bugzilla dev doc request form](https://bugzilla.mozilla.org/form.doc)
