### ISSUE TITLE
Add working example to "Perfect negotiation" article

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#2971]
While having an article introducing perfect negotiation was IMO part of MVP, I feel that a working example can wait and be added after the rest of the MVP work is done. So I'm adding this issue to remember to put that together.

## Tasks
- [ ] Construct a simple working example showing perfect negotiation
- [ ] Connect to the sample from the article
- [ ] Add any introductory/explanatory text needed

## Acceptance criteria
- [ ] Content added
- [ ] Review requested
