### ISSUE TITLE
Add the Permissions API stuff to the WebXR reference

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#3000]
The dictionaries and such for the Permissions API were missed first time around when adding things to the reference (or they're new). They need to be added.

## Tasks
- [x] Add reference doc for the `XRPermissionDescriptor` dictionary and its members
- [x] Add reference doc for the `XRPermissionStatus` interface and its members
- [x] Submit BCD updates needed for these
- [x] Appropriate reviews requested

## Acceptance criteria
* All reference pages are written, formatted properly, and complete
* Because no browsers implement this API yet, I've decided to forgo the guide for now, until I can do practical testing
