### ISSUE TITLE
E - Clean up JS page structures

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3017]
# Epic 
As an MDN user, I want to read consistent JS reference docs, so I can find information reliably.

# User Stories / tasks
- [x] #2537 Properly structure JS `Intl` docs
- [x] #3039 Move Microsoft JS docs into archive
- [x] #3040 Cleanup JS error docs according to linting rules
- [x] https://github.com/mdn/stumptown-content/issues/411 Fix linting errors "Expected h2#Examples for data.examples"
- [x] https://github.com/mdn/stumptown-content/issues/410 Fix linting errors "No H3-demarcated examples found"
- [x] https://github.com/mdn/stumptown-content/issues/407 Fix linting errors "dt elements in link lists must contain a single anchor element" 
- [x] https://github.com/mdn/stumptown-content/issues/405 data.browser_compatibility ingredient doesn't allow multiple BCD tables
- [x] https://github.com/mdn/stumptown-content/issues/447 Fix ordering issues

See also the label "js-linting" that mark all issues that affect the linting output for JS docs: https://github.com/mdn/stumptown-content/labels/js-linting

# Acceptance criteria

Zero **errors** from the linter when its run on all JS pages.

**Comment by Elchi3** [comment]
@wbamberg the stories above exclude warnings/errors about macro usage and missing ingredient handlers. I assume we still have open issues about them? 

To meet the acceptance criteria, "Zero errors from the linter when its run on all JS pages", we need to either silence the linter about macro usage, or actually remove macros. (or formulate this AC differently).

I could image this AC to be "Zero **ingredient** errors from the linter when its run on all JS pages." and leave macro usages and missing ingredient handler implementations to other user stories and epics. Let me know.

**Comment by wbamberg** [comment]
> @wbamberg the stories above exclude warnings/errors about macro usage and missing ingredient handlers. I assume we still have open issues about them?

> To meet the acceptance criteria, "Zero errors from the linter when its run on all JS pages", we need to either silence the linter about macro usage, or actually remove macros. (or formulate this AC differently).

But the messages about macros an unimplemented handlers are *warnings*, not *errors*. So "Zero errors from the linter" excludes them already, doesn't it?

```
Macro: optional_inline                                            200 warnings   optional_inline                                                        
Handler for data.info_box is unimplemented                        110 warnings   javascript-property/data.info_box/handler-not-implemented              
Expected short description for prose.short_description            73 errors      javascript-error/prose.short_description/missing-prose-section      
```

**Comment by Elchi3** [comment]
Oversight from my side. Thanks Will!

**Comment by Elchi3** [comment]
https://github.com/mdn/stumptown-content/pull/438 has now landed and so https://github.com/mdn/stumptown-content/issues/447 becomes a new task under this epic

**Comment by wbamberg** [comment]
I've checked the current status of this. There are **57 errors remaining**.

## Examples, 28 errors:

[JavaScript/Reference/Operators/Arithmetic_Operators](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators)
[JavaScript/Reference/Operators/Assignment_Operators](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Assignment_Operators)
[JavaScript/Reference/Operators/Comparison_Operators](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators)
[JavaScript/Reference/Operators/Destructuring_assignment](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
[JavaScript/Reference/Operators/Logical_Operators](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators)
[JavaScript/Reference/Operators/Object_initializer](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer)
[JavaScript/Reference/Operators/Property_Accessors](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors)
[JavaScript/Reference/Operators/this](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)
[JavaScript/Reference/Global_Objects/Date/@@toPrimitive](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/@@toPrimitive)
[JavaScript/Reference/Global_Objects/Intl](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl)
[JavaScript/Reference/Global_Objects/Intl/Locale](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale)
[JavaScript/Reference/Global_Objects/Intl/Locale/Locale](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/Locale)
[JavaScript/Reference/Global_Objects/Math](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math)
[JavaScript/Reference/Global_Objects/Number/NaN](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NaN)
[JavaScript/Reference/Global_Objects/Object/toLocaleString](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toLocaleString)
[JavaScript/Reference/Global_Objects/Promise/any](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any)
[JavaScript/Reference/Global_Objects/Reflect](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect)
[JavaScript/Reference/Global_Objects/SharedArrayBuffer](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer)
[JavaScript/Reference/Global_Objects/Symbol/valueOf](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/valueOf)
[JavaScript/Reference/Global_Objects/Symbol/@@toPrimitive](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/@@toPrimitive)
[JavaScript/Reference/Global_Objects/Symbol/replace](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/replace)
[JavaScript/Reference/Global_Objects/Symbol/search](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/search)
[JavaScript/Reference/Global_Objects/Symbol/split](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/split)
[JavaScript/Reference/Global_Objects/TypedArray](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray)
[JavaScript/Reference/Global_Objects/WebAssembly/Instance](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Instance)
[JavaScript/Reference/Global_Objects/WebAssembly/Instance/Instance](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Instance/Instance)
[JavaScript/Reference/Global_Objects/WebAssembly/Module](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module)
[JavaScript/Reference/Global_Objects/WebAssembly/Module/Module](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module/Module)

This is being tracked in https://github.com/mdn/stumptown-content/issues/411.

## SpecName, 21 errors

[JavaScript/Reference/Classes/Private_class_fields](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields)
[JavaScript/Reference/Classes/Public_class_fields](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields)
[JavaScript/Reference/Operators/Pipeline_operator](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Pipeline_operator)
[JavaScript/Reference/Global_Objects/AggregateError](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError)
[JavaScript/Reference/Global_Objects/AggregateError/AggregateError](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError/AggregateError)
[JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRange)
[JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRangeToParts](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatRangeToParts)
[JavaScript/Reference/Global_Objects/Intl/DisplayNames](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames)
[JavaScript/Reference/Global_Objects/Intl/ListFormat](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat)
[JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/ListFormat)
[JavaScript/Reference/Global_Objects/Intl/ListFormat/supportedLocalesOf](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/supportedLocalesOf)
[JavaScript/Reference/Global_Objects/Intl/ListFormat/format](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/format)
[JavaScript/Reference/Global_Objects/Intl/ListFormat/formatToParts](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/formatToParts)
[JavaScript/Reference/Global_Objects/Intl/ListFormat/resolvedOptions](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/resolvedOptions)
[JavaScript/Reference/Global_Objects/Promise/any](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any)
[JavaScript/Reference/Global_Objects/RegExp/n](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n)
[JavaScript/Reference/Global_Objects/RegExp/input](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/input)
[JavaScript/Reference/Global_Objects/RegExp/lastMatch](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastMatch)
[JavaScript/Reference/Global_Objects/RegExp/lastParen](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastParen)
[JavaScript/Reference/Global_Objects/RegExp/leftContext](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/leftContext)
[JavaScript/Reference/Global_Objects/RegExp/rightContext](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/rightContext)

I couldn't find an issue for this one.

## Missing prose.syntax, 4 errors:

[JavaScript/Reference/Operators/Arithmetic_Operators](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators)
[JavaScript/Reference/Operators/Bitwise_Operators](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators)
[JavaScript/Reference/Operators/Comparison_Operators](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators)
[JavaScript/Reference/Operators/Logical_Operators](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators)

These are connected with https://github.com/mdn/stumptown-content/issues/411#issuecomment-631107923.

## Miscellaneous, 4 errors:

This includes:
* three errors which depend on https://github.com/mdn/stumptown-content/pull/461 landing, then some small updates to the [`Generator`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) and [`TypedArray`](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) pages
* the regression for BigInt which we are discussion in https://github.com/mdn/stumptown-content/issues/459.
