### ISSUE TITLE
U - Document injection attacks and mitigation

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3057]
# User story
As a web developers, I want information on injection attacks and how to mitigate them, so I can securely configure my site.

# Acceptance criteria
- [ ] Injection attacks and mitigation best practices have been documented.

# Tasks
- [ ] Meet with SME (April King) re important info to cover. 
- [ ] Draft article.
- [ ] Get it reviewed.
- [ ] Iterate as needed.
