### ISSUE TITLE
U - Document how to prevent subdomain takeovers

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3058]
# User story
As a web developer, I want to know how to prevent subdomain takeovers, so I can securely configure my site.

# Acceptance criteria
- [ ] Prevention of subdomain takeovers has been documented.

# Tasks
- [x] Meet with Jon Claudius re important info to cover. (See also ['Deep thoughts' on subdomain takeover vulnerabilities](http://claudijd.github.io/2017/02/03/deep-thoughts-on-subdomain-takeovers/) and [Preventing subdomain takeovers for shared hosting providers](http://claudijd.github.io/2017/02/06/preventing-subdomain-takeover/))
- [x] Draft article.
- [ ] Get it reviewed.
- [ ] Iterate as needed.

See also 
- [The ultimate guide for subdomain takeover with practical](http://claudijd.github.io/2017/02/06/preventing-subdomain-takeover/) [sic]
- [Hostile Subdomain Takeover using Heroku/Github/Desk + more](https://labs.detectify.com/2014/10/21/hostile-subdomain-takeover-using-herokugithubdesk-more/)
- [A guide to subdomain takeovers](https://www.hackerone.com/blog/Guide-Subdomain-Takeovers)
- [Can I take over XYZ?](https://github.com/EdOverflow/can-i-take-over-xyz)
