### ISSUE TITLE
Create "MDN Web Performance Guide" Epic

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#308]
1) Research everything MDN has on web performance and everything MDN should have.

2) Create an outline for a new web performance guide

3) Create the EPIC

4) Create tickets for all the associated moving parts 

## Acceptance criteria

1 (above) has already been done

- [x] finish the outline — turn what's in the rough outline into actual units of work — clear articles along with what their contents will be
- [ ] Write an epic with the units of work included as sub tasks (issues)
- [ ] Add any other tasks to the epic that will be needed.

**Comment by jmswisher** [comment]
@estelle Is there an Epic, or is the outline (in the [Web Performance landing page](https://developer.mozilla.org/en-US/docs/Web/Performance)) the guide to work to be done?
