### ISSUE TITLE
T - UX for users to opt-into marketing email during account creation

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3134]
# Task 
UX for users to opt-into marketing email during account creation

# Acceptance Criteria
- [x] Legal sign-off
- [x] Engineering sign-off
- [x] Product manager sign-off

**Comment by malqinneh** [comment]
Updated copy to reflect value prop for signing up to the marketing email during account creation:

![MDN_Account-Creation - 01](https://user-images.githubusercontent.com/4819906/80647960-4f855e00-8a3d-11ea-8efd-bc1408ab3731.png)

**Comment by malqinneh** [comment]
Added acceptance criteria for engineering (@tobinmori) and product manager (@atopal) sign off - thank you!

**Comment by atopal** [comment]
Hey @malqinneh the language change has to be cleared with legal. I added that as an AC

**Comment by atopal** [comment]
Never mind, it was already there, I just didn't see it :)
