### ISSUE TITLE
T - UX for users to opt-into marketing email anytime

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3135]
# Task 
UX for users to opt-into marketing email anytime

# Acceptance Criteria
- [x] Legal sign-off
- [x] Engineering sign-off
- [x] Product manager sign-off

**Comment by malqinneh** [comment]
Similar to account creation UX; adding the same opt-in checkbox within the Edit Profile page:

![MDN_Edit-Profile - 01](https://user-images.githubusercontent.com/4819906/80733315-8ad66a00-8adb-11ea-8e08-30fa78787f07.png)

**Comment by malqinneh** [comment]
Added acceptance criteria for engineering (@tobinmori) and product manager (@atopal) sign off - thank you!

**Comment by atopal** [comment]
Thanks @malqinneh that looks good to me 👍
