### ISSUE TITLE
T - UX for users to opt-out of marketing emails

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3136]
# Task 
UX for users to opt-out of marketing emails

# Acceptance Criteria
- [x] Legal sign-off
- [x] Engineering sign-off
- [x] Product manager sign-off

**Comment by malqinneh** [comment]
If a user is already opted-in, they can opt-out by unchecking the box below their email address and clicking [Save] button at the bottom of their profile. This is not intuitive since modern forms/fields auto save. But this is the current functionality on MDN.

![MDN_Edit-Profile - 02](https://user-images.githubusercontent.com/4819906/80733770-24058080-8adc-11ea-8f4b-fd179341cfee.png)

**Comment by malqinneh** [comment]
Added acceptance criteria for engineering (@tobinmori) and product manager (@atopal) sign off - thank you!

**Comment by tobinmori** [comment]
I'm good with this design though I should say that making the opt-in checkbox 'live' (vs saved on page submit) will require extra work (require an API call and some JS), so maybe we implement as 'save on submit' for phase 1 and wait for phase 2 to make this page more dynamic (to keep Yari1 moving forward).

**Comment by malqinneh** [comment]
Agreed, the functionality proposed is 'saved on page submit' as you said. Also, proposed revising the copy in the button from [publish] to [save] for this reason.

**Comment by atopal** [comment]
Thanks @malqinneh that looks good to me 👍  Can you make sure the implementing dev is aware that the button text is changing as well? I missed that at first glance.

**Comment by malqinneh** [comment]
![MDN Edit Profile](https://user-images.githubusercontent.com/4819906/80984401-cf277a00-8dfb-11ea-8126-a2b704227b14.png)
