### ISSUE TITLE
E - CSP error messages are exposed via dev tools

### ISSUE THREAD

**Issue by atopal** [mdn/sprints#316]
CSP error messages are some of the most common error messages seen in Firefox. Developers are often unaware of how to fix the error message shown. A direct link to a trouble shooting doc in MDN would help developers without a Google visit and increase MDN's direct reach. 

# User Story
As a web developer, I want to see documentation about CSP error messages on MDN and in Firefox Dev Tools, so that I can understand how to correct these errors when I encounter them.

# Acceptance Criteria
- [ ] relevant CSP error messages have a troubleshooting doc
- [ ] Firefox links to docs with error messages

**Comment by digitarald** [comment]
If we come up with a URL scheme for the errors we can land the code and uplift it to beta.

**Comment by chrisdavidmills** [comment]
@digitarald for consistency with the JavaScript and CORS error messages, the URL scheme would be:

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/[ErrorName]

**Comment by atopal** [comment]
@digitarald I couldn't find any CSP error message names. Do you have a list handy?

**Comment by digitarald** [comment]
@atopal all logs possible are listed in https://dxr.mozilla.org/mozilla-central/source/dom/locales/en-US/chrome/security/csp.properties#73

@ckerschb for input on what we actually need from that list.

**Comment by digitarald** [comment]
Updating from bugzilla: Categories landed (and uplifted into Beta: https://bugzilla.mozilla.org/show_bug.cgi?id=1304645 ).

**Comment by Elchi3** [comment]
According to https://dxr.mozilla.org/mozilla-central/source/dom/locales/en-US/chrome/security/csp.properties, there are 36 warnings/errors related to CSP. They should live on MDN under these URLs:

- [ ] [The page’s settings blocked the loading of a resource: %1$S](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/CSPViolation)
- [ ] [The page’s settings blocked the loading of a resource at %2$S (“%1$S”).](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/CSPViolationWithURI)
- [ ] [A violation occurred for a report-only CSP policy (“%1$S”). The behavior was allowed, and a CSP report was sent.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/CSPROViolation)
- [ ] [The page’s settings observed the loading of a resource at %2$S (“%1$S”). A CSP report is being sent.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/CSPROViolationWithURI)
- [ ] [Tried to send report to invalid URI: “%1$S”](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/triedToSendReport)
- [ ] [couldn’t parse report URI: %1$S](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/couldNotParseReportURI)
- [ ] [Couldn’t process unknown directive ‘%1$S’](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/couldNotProcessUnknownDirective)
- [ ] [Ignoring unknown option %1$S](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/ignoringUnknownOption)
- [ ] [Ignoring duplicate source %1$S](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/ignoringDuplicateSrc)
- [ ] [Ignoring source ‘%1$S’ (Not supported when delivered via meta element).](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/ignoringSrcFromMetaCSP)
- [ ] [Ignoring “%1$S” within script-src or style-src: nonce-source or hash-source specified](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/ignoringSrcWithinScriptStyleSrc)
- [ ] [Ignoring “%1$S” within script-src: ‘strict-dynamic’ specified](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/ignoringSrcForStrictDynamic)
- [ ] [Ignoring source “%1$S” (Only supported within script-src).](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/ignoringStrictDynamic)
- [ ] [Keyword ‘strict-dynamic’ within “%1$S” with no valid nonce or hash might block all scripts from loading](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/strictDynamicButNoHashOrNonce)
- [ ] [The report URI (%1$S) should be an HTTP or HTTPS URI.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/reportURInotHttpsOrHttp2)
- [ ] [This site (%1$S) has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/reportURInotInReportOnlyHeader)
- [ ] [Failed to parse unrecognized source %1$S](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/failedToParseUnrecognizedSource)
- [ ] [An attempt to execute inline scripts has been blocked](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/inlineScriptBlocked)
- [ ] [An attempt to apply inline style sheets has been blocked](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/inlineStyleBlocked)
- [ ] [An attempt to call JavaScript from a string (by calling a function like eval) has been blocked](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/scriptFromStringBlocked)
- [ ] [Upgrading insecure request ‘%1$S’ to use ‘%2$S’](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/upgradeInsecureRequest)
- [ ] [Ignoring srcs for directive ‘%1$S’](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/ignoreSrcForDirective)
- [ ] [Interpreting %1$S as a hostname, not a keyword. If you intended this to be a keyword, use ‘%2$S’ (wrapped in single quotes).](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/hostNameMightBeKeyword)
- [ ] [Not supporting directive ‘%1$S’. Directive and values will be ignored.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/notSupportingDirective)
- [ ] [Blocking insecure request ‘%1$S’.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/blockAllMixedContent)
- [ ] [Ignoring ‘%1$S’ since it does not contain any parameters.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/ignoringDirectiveWithNoValues)
- [ ] [Ignoring sandbox directive when delivered in a report-only policy ‘%1$S’](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/ignoringReportOnlyDirective)
- [ ] [Referrer Directive ‘%1$S’ has been deprecated. Please use the Referrer-Policy header instead.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/deprecatedReferrerDirective)
- [ ] [Ignoring ‘%1$S’ because of ‘%2$S’ directive.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/IgnoringSrcBecauseOfDirective)
- [ ] [Couldn’t parse invalid source %1$S](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/couldntParseInvalidSource)
- [ ] [Couldn’t parse invalid host %1$S](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/couldntParseInvalidHost)
- [ ] [Couldn’t parse scheme in %1$S](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/couldntParseScheme)
- [ ] [Couldn’t parse port in %1$S](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/couldntParsePort)
- [ ] [Duplicate %1$S directives detected.  All but the first instance will be ignored.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/duplicateDirective)
- [ ] [Directive ‘%1$S’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/deprecatedChildSrcDirective)
- [ ] [Couldn’t parse invalid sandbox flag ‘%1$S’](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP/Errors/couldntParseInvalidSandboxFlag)

To proceed: 
- The above 36 pages need to written. I think this is a full sprint worth of work.
- The categories have been implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1304645 already :+1: 
- The mapping to Devtools is not yet implemented, as we haven't written the pages yet. It will be similar to https://bugzilla.mozilla.org/show_bug.cgi?id=1475391.

Like with CORS, there is no telemetry on how often the CSP errors/warnings are thrown, so we don't know how many people we can reach by implementing [Learn more] links for CSP. It might be similar to CORS, or less. We do want to support the adoption of CSP, and Firefox error messages are always helpful currently. So, this could be a step in the right direction.

**Comment by chrisdavidmills** [comment]
Let's return to this one next year.
