### ISSUE TITLE
E - CSS docs: write page structure recipes and update linter to lint pages against recipes

### ISSUE THREAD

**Issue by wbamberg** [mdn/sprints#3170]
# Epic 

This epic ensures that:
* we understand which structures we want to have for CSS reference documentation
* are able to lint our CSS documentation to check that it follows these structures

# Acceptance Criteria 
- [ ] We have recipes defined for the CSS reference documentation
- [ ] All pages in the CSS doc set map to a recipe
- [ ] We have an agreed specification describing how to lint pages against recipes
- [ ] The linter implements checks for all the structures described in the specification
