### ISSUE TITLE
E - Update Existing web security docs 

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3227]
# Epic
Update Existing web security docs

# Acceptance criteria
- [ ]  Existing documentation have been updated 
     - [ ] TLS related docs 
     - [x] Secured data management related docs 
     - [x]  clickjacking protection related docs 
     - [ ] Integrity
