### ISSUE TITLE
U — Get feedback on FED learning pathways proposal

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3296]
After [writing the proposal](https://github.com/mdn/sprints/issues/3295), I want to send it out for review by some of my peers (and perhaps some of the folks that gave me feedback), collect feedback on the proposal, and update it accordingly.

# Acceptance criteria

- [ ] Useful feedback received from at least 5 people.
- [ ] Proposal updated acordingly.

# Tasks 

- [x] Make list of people to send it out to 
- [x] Send it out
- [ ] Collate feedback
- [ ] Update proposal accordingly
