### ISSUE TITLE
U — Interview people to collect feedback on the FED pathway

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3299]
I want to interview people about the FED learning parthway.

# Acceptance criteria

- [ ] Interview at least 3 professional front-end developers about the pathway.
- [ ] Interview at least 3 aspiring front-end developers about the pathway.

# Tasks

- [x] Compile list of folks to ask for an interview
- [x] Work out process for running the interviews
- [x] Set up spreadsheet to record interview schedule
- [x] Create GDocs for recording interview notes 
- [x] Conduct interviews

**Comment by chrisdavidmills** [comment]
I've written up a plan of what to do here, and contacted would-be interviewees. I'm not linking that information here, and it contains sensitive details (email addresses, etc.)

**Comment by chrisdavidmills** [comment]
I've got all the interviews done that I'm going to do — only three in the end. They were super useful, but it has been challenging getting them set up.
