### ISSUE TITLE
E - Publish MVP roadmap

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3342]
# Epic 
E - Publish MVP roadmap

# Acceptance criteria
- [ ] We have a **Document** that sketches out basic path to Yari based on the decisions made.
- [ ] We have a **defined MVP** that incorporates Writer feedback
- [ ] Our defined MVP has been **scoped for delivery at the end of Q3**
