### ISSUE TITLE
E — Update WebAssembly docs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3343]
# User story
As a developer, I want to read updated WebAssembly docs, so I can find out how it works without experiencing errors or falling foul of outdated information.

Note: Not creating user stories yet; just collecting issues together for now.

# Acceptance criteria

- [ ] Update code in WA docs so that readers following along locally do not fall foul of incorrect mime type issues, as described in https://github.com/mdn/webassembly-examples/issues/5 (GitHub supports `application/wasm`, but most local servers don't, and finding out how to add them seems really hard).
- [ ] Audit WA JS API features to see if we are missing any. Add pages we are missing.
- [ ] Test web assembly text examples, and update out of date syntax. For example:
  * `local.get` is out of date; should be replaced by `get_local`

# Sprint Ready Checklist
