### ISSUE TITLE
Intersection Observer API overview: incorrect claims about isIntersecting

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#3403]
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API this article claims that the isIntersecting property is true when an entry passes the threshold, but this is incorrect. It will always be true when the entry intersects the root. You have to manually check the threshold.

The mildly annoying thing is that Chrome does handle this like the article describes, but FF does not (and I believe that FF's implementation is, technically, more correct).

## Tasks
- [x] Verify that the reported issue is in fact an error
- [x] Update the overview to be correct as needed
- [x] Make sure the code sample works and is updated

## Acceptance criteria
- [ ] Text and sample have been fixed to match the spec

**Comment by a2sheppy** [comment]
The article at https://wiki.developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API has been updated. I updated the [Thresholds](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Thresholds) section primarily. These changes involved updating the description of `isIntersecting` and some text to clarify that the entry list given to the callback isn't a list of entries for the elements that experienced a state change, but for all the observed elements.

Changes related to the latter were also made to the section [Intersection change callbacks](https://wiki.developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Intersection_change_callbacks).

Confirmed that the `isIntersecting` article is accurate.
