### ISSUE TITLE
[WebRTC] Add remoteTimestamp to RTCRemoteOutboundRtpStreamStats, Fx 79

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#3412]
# User story

As a web developer, I want to know how about WebRTC updates that are now implemented in Firefox 79 and in other browsers.

# Tasks
[This dictionary](https://www.w3.org/TR/webrtc-stats/#remoteoutboundrtpstats-dict*) has not been documented at all yet, so this will involve creating the following pages:

- [x] Create [overview page](https://wiki.developer.mozilla.org/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats).
- [x] Create page for the [remoteTimestamp](https://wiki.developer.mozilla.org/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/remoteTimestamp) property
- [x] (Ideally) Create page for the [localId](https://wiki.developer.mozilla.org/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/localId) property
- [x] (Ideally) Create page for the [reportsSent](https://wiki.developer.mozilla.org/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats) property
- [x] Ensure BCD is up to date
- [x] Add the dictionary to the overview page's list of dictionaries, if it's not there
- [x] Make sure the dictionary is included in GroupData.json.
- [x] Update Firefox 79 for developers

# Acceptance criteria

- [ ] [Add remoteTimestamp to RTCRemoteOutboundRtpStreamStats](https://bugzilla.mozilla.org/show_bug.cgi?id=1615191) marked as dev-doc-complete
- [ ] Compat data updated
- [ ] MDN pages written
- [ ] Added to Firefox 79 for developers

**Comment by Elchi3** [comment]
@a2sheppy do you reckon you can use this bug for your yari test session?

**Comment by Elchi3** [comment]
@a2sheppy oh, and please also estimate this issue (if this is your yari task, then take that into account and plan a longer time for it.)

**Comment by a2sheppy** [comment]
@Elchi3 Yari test session? I think I'm confused. All I'm doing is adding tags to CSS pages.

**Comment by a2sheppy** [comment]
Documentation updates completed:

## New articles added

*   https://developer.mozilla.org/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats
*   https://developer.mozilla.org/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/localId
*   https://developer.mozilla.org/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/remoteTimestamp
*   https://developer.mozilla.org/en-US/docs/Web/API/RTCRemoteOutboundRtpStreamStats/reportsSent

## Code

*   Forked off a new version of my WebRTC chat and video calling example that has now been updated to display some statistics. Other improvements have been made that will eventually need to migrate back to the base code used in the original version of this project. Available on Glitch: https://glitch.com/~websocket-webrtc-chat-with-stats

## Existing articles updated

*   [Firefox 79 for developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79)
*   Revamped the WebRTC Statistics API landing page with a new [Reference section](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_Statistics_API) containing a table mapping statistic names to the objects that contain the data, complete with all the parent dictionaries for each one
*   Rewrote swaths of the [RTCStatsReport overview page](https://wiki.developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport), since there was much of it that was entirely wrong. Page is still incomplete but is at least no longer painfully misleading.

## Other

*   Submitted, obtained review for, and merged [BCD PR 6387](https://github.com/mdn/browser-compat-data/pull/6387) to add compatibility data for `RTCRemoteOutboundRtpStreamStats`.
