### ISSUE TITLE
U - Finish the article "Privacy, permissions, and information security"

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#3415]
This article, located at https://wiki.developer.mozilla.org/en-US/docs/Web/Privacy, is intended to be an introduction to concepts around privacy and data security. Terminology, basic descriptions of concepts, that sort of thing. Parts of the article are done or essentially done, but there's a bunch left to finish up.

## Tasks

*   [ ] Review the previously existing material to ensure it's accurate and up to date.
*   [ ] Write the section "Personal and private information"; this should detail what kinds of information are personal or could be used against the user in some way, either by direct attack or as a means to obtain further access.
*   [ ] Finish the section "Privacy risks." This section lists ways that private or personal information could be obtained by bad actors.
*   [ ] Write the section "Keeping personal data safe," which should cover things users should do while using browsers to ensure their data is secure from bad actors.
*   [ ] Write the section "Managing site permissions" to cover how permissions are managed for individual web sites in modern browsers. This will be about things like the Permissions API but also permissions that are managed separately from this API still.
*   [ ] Finish the section "Bringing it all together," which needs to cover how to to ensure privacy and data security by using all the available APIs and settings available within a web app.

## Acceptance criteria

*   Article is complete and accurate
*   Submitted to the security team for their review

**Comment by jmswisher** [comment]
Please be sure to check for overlap with other articles, so we don't end up with similar content (e.g., "keeping personal data safe") in multiple places.

**Comment by a2sheppy** [comment]
Yep. Was planning to but good reminder! The idea is to get this stuff into one place finally.


Eric "Sheppy" Shepherd
Senior Technical Writer
MDN Web Docs
Mozilla

**Comment by Elchi3** [comment]
We de-prioritized this.
