### ISSUE TITLE
Create materials to celebrate 15 years of MDN

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3418]
# User story
As a MDN writer, developer, contributor, fan, or general well-wisher, I want to read about Mozilla's achievements in the last 15 years, so I can feel happy, and help to promote MDN even further.

Mozilla is 15 years old this year. It would be nice to celebrate it in some way. Given that we don't have a huge amount of budget or free time at the moment, it might be good to do so in the way we know best — write some great content about it, and spread it far and wide. We can start by brainstorming ideas.

Sandra has also done some work here, see https://docs.google.com/document/d/1wUUzfLoPGszJ5XidqOJ8-gNo__v2R2wG4R_qqvhUaGQ/edit. So really a good first step is to have a brainstorming session to finalize what we might want to do.

# Tasks

- [ ] Brainstorming session to decide what we want to do exactly.

- [ ] Write hacks post. This should say a bit about the beginnings of MDN, and talk about what it has become. For more of this content we can reference the [MDN at Ten](https://wiki.developer.mozilla.org/en-US/docs/MDN_at_ten) work we did after 10 years. It should also:
  * give numbers to say the progress we've made in the last 5 years
  * talk about the major projects that have come to light in the last 5 years (BCD, Learning Area, Interactive Examples, MDN moving to React, XXXXX others)
  * also talk about the future we are heading towards (Yari, Stumptown).

- [ ] Create some kind of infographic to show what we've done, in visual form.

# Acceptance criteria

- [ ] Hacks post published
- [ ] Hacks post (and other materials) promoted on social/community.

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by Elchi3** [comment]
@chrisdavidmills can you estimate this?

**Comment by chrisdavidmills** [comment]
> can you estimate this?

I'm not really sure exactly what we are doing here yet, so I've given it a timebox of 3 for now.

**Comment by chrisdavidmills** [comment]
This happened.
