### ISSUE TITLE
As a MDN writer, I want to record video and audio content, so I can contribute to creating promotional videos about MDN

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#3421]
# User story
As a MDN writer, I want to record video and audio content, so I can contribute to creating promotional videos about MDN.

# Acceptance criteria

- [ ] Setup successfully created and tested.
- [ ] Sample footage sent to Sandra

# Tasks

- [ ] Get hold of greenscreen/background
- [ ] Get hold of lighting setup
- [ ] Get hold of screen capture software
- [ ] Test audio/video
- [ ] Try creating a sample first minute of episode 1 of the MDN learning pathways video.

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified
