### ISSUE TITLE
[DevTools] Document Application panel

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3432]
# User story
As a web developer, I want to understand how to use the new DevTools Application panel, so I can understand and debug my PWAs and other uses of service workers. 

Note: This feature is enabled in Dev Edition 78, and will be enabled in Release 79. 

# Acceptance criteria

- [ ] The Application panel is fully documented, and has been reviewed by DevTools engineers.

# Tasks

- [x] Write above pages
- [x] Get following documentation reviewed by DevTools folks (probably Harald?) SENT FOR REVIEW (Harald, Belén, & Honza)
- [x] Publish documentation on MDN at the appropriate URLs
- [x] Update about:debugging page to mention service workers Application panel functionality, and how the two relate
- [x] Update Network Inspector pages to mention how service workers appear there, if they don’t already?
- [x] Include Application panel in the tools sidebar. I’m assuming we want it as a top-level item along with the other core tools, rather than an item under “More tools”?

# Resources
- [PRD](https://docs.google.com/document/d/1z1XBgD0R7PnBLZ-gFPl9h6e6qHlYhGsUsPAACwWELJg/edit?usp=sharing)
- [Existing doc about Service Workers in about:debugging](https://developer.mozilla.org/en-US/docs/Tools/about:debugging#Workers)

**Comment by chrisdavidmills** [comment]
draft doc for the new documentation items: https://docs.google.com/document/d/1PfIqRu0oS-96Hljqfq0nALDi5RpHRLf6rGHJrmtmDlc/edit#

**Comment by chrisdavidmills** [comment]
Added a note to https://developer.mozilla.org/en-US/docs/Tools/about:debugging#Service_worker_state to point to the application panel and give people an idea of how the two relate.

**Comment by chrisdavidmills** [comment]
PR filed to add the Applications panel to the devtools sidebar: https://github.com/mdn/kumascript/pull/1403

**Comment by chrisdavidmills** [comment]
Application panel added to the list of core tools on the DevTools landing page: https://developer.mozilla.org/en-US/docs/Tools

**Comment by chrisdavidmills** [comment]
Application panel articles published:

* https://developer.mozilla.org/en-US/docs/Tools/Application
* https://developer.mozilla.org/en-US/docs/Tools/Application/Service_workers
* https://developer.mozilla.org/en-US/docs/Tools/Application/Manifests

**Comment by Elchi3** [comment]
@chrisdavidmills has this been reviewed? close this?

**Comment by chrisdavidmills** [comment]
This was reviewed over a mail thread, so yeah, we can close.
