### ISSUE TITLE
O - Agree with partners on how MDN should represent specification and standardization information

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3508]
# Objective  
O - Agree with partners on how MDN should represent specification and standardization information

# Acceptance criteria
- [ ] KR: Collect user and partner requirements
- [ ] KR: Define updates to BCD semantics
- [ ] KR: Define revamp of MDN specification section
- [ ] KR: Prototype new spec sections for a few pages
- [ ] KR: Collect user and partner feedback and iterate if needed
