### ISSUE TITLE
Document cryptography basics for web developers

### ISSUE THREAD

**Issue by jmswisher** [mdn/sprints#3549]
# User Story
As a web developer, I want to know the basics of cryptography that I need to secure my site, without getting overwhelmed with cryto details.

# Acceptance Criteria
- [ ] Crypto basics for web devs have been documented to satisfaction of SMEs.

# Tasks

- [ ] Confirm outline with Thyla and/or Dana
- [ ] Draft article, and verify existing related articles (e.g., TLS)
- [ ] Get reviews from SMEs.
- [ ] Iterate as needed.
