### ISSUE TITLE
WebRTC: Finish documentation of ICE events

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#36]
Ensure that all of the ICE events are documented.

## Tasks
Document each following events and their event handlers. If documents already exist, ensure they're up to date, accurate, and complete, with appropriate examples. In each case, ensure the corresponding event handler page is done as well.

### RTCPeerConnection
- [ ]  [`negotiationneeded`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/negotiationneeded_event)
- [ ]  [`signalingstatechange`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/signalingstatechange_event)
- [ ]  [`iceconnectionstatechange`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceconnectionstatechange_event)
- [ ]  [`icegatheringstatechange`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icegatheringstatechange_event)
- [ ]  [`icecandidate`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icecandidate_event)
- [ ]  [`connectionstatechange`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionstatechange_event)
- [ ] BCD is up to date
- [ ] GroupData includes each of these

### RTCIceTransport
- [ ]  [`statechange`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/statechange_event)
- [ ]  [`gatheringstatechange`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/gatheringstatechange_event)
- [ ]  [`selectedcandidatepairchange`](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/selectedcandidatepairchange_event)
- [ ] BCD is up to date
- [ ] GroupData includes each of these

## Acceptance criteria
- [ ] All event pages exist and are complete
- [ ] All event handler pages exist and are complete
- [ ] All pages are linked from the appropriate places on the site, including the interface overview pages
- [ ] BCD is up to date

**Comment by wbamberg** [comment]
@a2sheppy , @jmswisher , I think perhaps this should not be part of #685 ? #685 is primarily about refactoring our existing event docs, not about writing new event docs.

**Comment by a2sheppy** [comment]
I agree. Although, interestingly, I was told that part of the event reference refactor was to finish up the missing/incomplete content. Florian, I think. I may have interpreted his answer wrong though; he may have just meant we were to update existing material that had gaps, not to write missing content. Anyway, yeah, I don't think this is part of the refactor of the event docs.

**Comment by chrisdavidmills** [comment]
I think I may have also been leaning on this idea too; I've been creating missing event and event handler property pages as I've come across them. 

But the ones I've done so far are small, with good quality existing event pages, and didn't have much in the way of new pages to create. Some of them are in much worse shape, and I think we'll need to forego this to make this project manageable.

We can always look at filling in missing pages as part of the ongoing page maintenance work we've got scheduled to start around end of Q2/Q3.

**Comment by a2sheppy** [comment]
Agreed; we'll look at this work separately from the events refactor. Good.

**Comment by jmswisher** [comment]
@a2sheppy  This is marked "Done" in the spreadsheet. Is it Done?

**Comment by jmswisher** [comment]
I'm assuming it is done.
