### ISSUE TITLE
Beta Community Trial launch 

### ISSUE THREAD

**Issue by chinikes** [mdn/sprints#3671]
# Epic 
Beta Community Trial launch 

# Acceptance Criteria 
- [x] Set up contribution workflow - # Week of Sep 21 
- [x] Blog post created for Community announcing Beta release with call to action (sign up) 
- [x] [Contribution workflow documented in Readme](https://github.com/mdn/yari/issues/1108) and Community notified - @chrisdavidmills - Week of Oct 26
