### ISSUE TITLE
Firefox 63 Layout DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#369]
# User story
As a web developer, I want to learn about the new Layout features in Firefox 63, so I can use them in my own projects.

# Acceptance criteria

1. - [ ] All DDNs complete.
2. - [ ] Reviews request from engineers for all documentation work.

# Tasks

## Standalone larger items

1. - [x] [Implement syntax improvements for media queries from level 4 specification](https://bugzilla.mozilla.org/show_bug.cgi?id=1422225) [1 day]
2. - [x] [[css-logical] rename offset-* properties to inset-block-start, inset-block-end, inset-inline-start and inset-inline-end](https://bugzilla.mozilla.org/show_bug.cgi?id=1464782) [1 day]
3. - [x] [Add support for CSS prefers-reduced-motion media feature for Windows](https://bugzilla.mozilla.org/show_bug.cgi?id=1365045) [1 day]
4. - [x] NEW [[css-logical] Flow-Relative Values for the "resize" Property](https://bugzilla.mozilla.org/show_bug.cgi?id=1464786) [1 day at most, needs a simple check?]

## Smaller items estimated together

Total estimate — 4.25 days

1. - [R: 427] [[css-flexbox] Implement flexbox layout for the row-gap and column-gap properties](https://bugzilla.mozilla.org/show_bug.cgi?id=1398483) 
2. - [422 ] [Support CSS3 content property replacement of element (rather than pseudo-element)](https://bugzilla.mozilla.org/show_bug.cgi?id=215083)
3. - [ 423] [Remove CSS pref "layout.css.unset-value.enabled"](https://bugzilla.mozilla.org/show_bug.cgi?id=1211330)
4. - [424 ] [remove <angle> values from image-orientation](https://bugzilla.mozilla.org/show_bug.cgi?id=1473450)
5. - [R: 431] [Turn layout.css.offset-logical-properties.enabled off by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1471838)
6. - [ 425] [Extend @-moz-document syntax to let users style standalone images and videos](https://bugzilla.mozilla.org/show_bug.cgi?id=1475511)
7. - [ 426] [Hide display: -moz-box and display: -moz-inline-box from content in Nightly / early beta.](https://bugzilla.mozilla.org/show_bug.cgi?id=1477553)
8. - [x] [[css-flexbox][css-align] Implement flexbox layout for <overflow-position> (safe/unsafe) in align-self, align-content, and justify-content](https://bugzilla.mozilla.org/show_bug.cgi?id=1297774) [we already have these documented in pages, but probably need to update BCD, and improve descriptions, e.g. make it clear that it needs to be used in conjunction with another value]

------------------------
The following has been moved to https://app.zenhub.com/workspace/o/mdn/sprints/issues/436

1.  [Add initial support of scrollbar-width](https://bugzilla.mozilla.org/show_bug.cgi?id=1475033) [1 day]
1. [ ] NEW [Implement path() function for offset-path](https://bugzilla.mozilla.org/show_bug.cgi?id=1429298) [1 day, page exists but needs structure sorting out; BCD needs updating]
1.  [ ] NEW [-webkit pseudo selectors makes the CSS rules fail.](https://bugzilla.mozilla.org/show_bug.cgi?id=1424106) [1 day, not much content but need to investigate where to put it]
1. [ ] NEW [Add support for |clip-path: path()|](https://bugzilla.mozilla.org/show_bug.cgi?id=1246764) [1.5 days]

 
1. [ ] NEW [Tracking -moz-scrollbars-none when creating webcompat issues.] (https://bugzilla.mozilla.org/show_bug.cgi?id=1481125)
1. [R] NEW [swap values of 2-value 'overflow' syntax so block is first and inline is second] (https://bugzilla.mozilla.org/show_bug.cgi?id=1481866)

**Comment by rachelandrew** [comment]
re: Flexbox `row-gap` and `column-gap`, I can see the implementation in Flex layout has already been added to `column-gap` (https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap) and I can do the same for `row-gap` which currently only has grid listed.

I'll also document these on the Flexbox Guides as a 63 feature.

I can also look at the safe/unsafe alignment keywords and make sure these are properly documented in the Guides and elsewhere.

**Comment by rachelandrew** [comment]
I have documenting Logical Properties and values and writing guides for those as a chunk of work already so could prioritize that for 63, I'm also very familiar with media queries 4 so could take that on.
