### ISSUE TITLE
Firefox 63 DevTools DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#373]
# User story
As a web developer, I want to learn about the new DevTools features in Firefox 63, so I can use them in my own projects.

# Acceptance criteria

- [ ] All DDNs complete.
- [ ] Reviews request from engineers for all documentation work.

# Tasks

## Standalone larger items

- [x] [Implement screenshot command in the console panel](https://bugzilla.mozilla.org/show_bug.cgi?id=1464461) [2 points]

## Smaller items estimated together

Total estimate — 2.25 points

- [x] [Separate user add-ons and system add-ons](https://bugzilla.mozilla.org/show_bug.cgi?id=1425347)
- [x] [Migrate restart command to browser console](https://bugzilla.mozilla.org/show_bug.cgi?id=1458840)
- [x] [Show accessible object's name and role information with info-bar highlight.](https://bugzilla.mozilla.org/show_bug.cgi?id=1473030)
- [x] [The network tab should flag resources on the tracking protection list](https://bugzilla.mozilla.org/show_bug.cgi?id=1333994)
- [x] [Move the codeMirror console input in-line with the logs](https://bugzilla.mozilla.org/show_bug.cgi?id=1136299)

**Comment by irenesmith** [comment]
Documentation updated for #[1464461](https://bugzilla.mozilla.org/show_bug.cgi?id=1464461), added to 63 release notes, and review requested.

Added the command here: https://developer.mozilla.org/en-US/docs/Tools/Tips under general tips and added to the Web Console section of the same page.
Added to [Web Console Helpers](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Helpers) as well.
 
Finally, I added a description of the command to the release notes: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/63

**Comment by chrisdavidmills** [comment]
@irenesmith Nice work! Remember to set the bug to dev-doc-complete, and ask the engineer to review your work in the bug.

**Comment by chrisdavidmills** [comment]
Also, that one was targeted to Fx63, but it was actually fixed in Fx62, so you'll need to move your rel note to the Fx62 note page.

**Comment by irenesmith** [comment]
@chrisdavidmills Moved the information to 62 release notes. I thought dev-doc-complete was only after the changes had been reviewed?

**Comment by chrisdavidmills** [comment]
In the end we decided to just do it after we've done the work, and have the engineering review as desirable but not essential for completion. If we did require it, we'd end up with yet another step of chasing people for reviews, which would add even more time on to the DDNs.

**Comment by irenesmith** [comment]
Remaining DDNs:

[1333994](https://bugzilla.mozilla.org/show_bug.cgi?id=1333994) - There is a related bug to this, but I can add the initial information and will have this one done today.
