### ISSUE TITLE
Firefox 63 Media DDNs

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#374]
# User story
As a web developer, I want to learn about the new Media features in Firefox 63, so I can use them in my own projects.

# Acceptance criteria

- [x] All DDNs complete.
- [x] Reviews requested from engineers for all documentation work.

# Tasks

## Standalone larger items

- [x] [Expose to web content whether autoplay is blocked](https://bugzilla.mozilla.org/show_bug.cgi?id=1478208) [1 point]
- [x] NEW [website should handle rejected promise from video.play() properly when the pref "media.autoplay.enabled=false"](https://bugzilla.mozilla.org/show_bug.cgi?id=1412772) [1 point]
- [x] NEW [Enable SourceBuffer.changeType by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1481166) [1 point, looks like changeType needs documenting in the first place]

## Smaller items estimated together

Total estimate — 5 points
- [x] [Emit new SCTP data channel offer format in Fx >= 62](https://bugzilla.mozilla.org/show_bug.cgi?id=1335206)
- [x] [Add AudioWorkletProcessor interface definitions](https://bugzilla.mozilla.org/show_bug.cgi?id=1466182) [probably just needs adding to sheppy's AudioWorkets plan]
- [x] [Add "AudioWorklet" definition](https://bugzilla.mozilla.org/show_bug.cgi?id=1470856) [probably just needs adding to sheppy's AudioWorkets plan]
- [x] [Remove audioWorklet attribute from Window](https://bugzilla.mozilla.org/show_bug.cgi?id=1471843)
- [x] [setValueCurveAtTime doesn't accept sequence<float>](https://bugzilla.mozilla.org/show_bug.cgi?id=1421091)
- [x] [ConstantSourceNode.offset min/max values incorrect](https://bugzilla.mozilla.org/show_bug.cgi?id=1413256) [this is a dupe, but it explains what needs to be done better than the original]
- [x] [enumerateDevices() should enumerate audio output devices (if we have any)](https://bugzilla.mozilla.org/show_bug.cgi?id=1152401)
- [x] [ConstantSourceNode.start(-1) should throw RangeError](https://bugzilla.mozilla.org/show_bug.cgi?id=1413284)
- [x] [Remove the doppler effect from the PannerNode](https://bugzilla.mozilla.org/show_bug.cgi?id=1148354)
- [x] [Mark ctor-constantsource.html as passing, since bug 1456266 landed](https://bugzilla.mozilla.org/show_bug.cgi?id=1413283)
- [x] NEW [Add deprecation warning for removal of stat.isRemote in 65.](https://bugzilla.mozilla.org/show_bug.cgi?id=1393306) [0.25 point; stats are not documented yet so this is just adding a note to Fx 63 for devs for now]
- [x] NEW [Flip media.media-capabilities.enabled to true](https://bugzilla.mozilla.org/show_bug.cgi?id=1480190) [0.25 points, if not already done]
- [x] NEW [setValueCurveAtTime throws incorrect exceptions](https://bugzilla.mozilla.org/show_bug.cgi?id=1472095) [0.25 points]

**Comment by a2sheppy** [comment]
Documentation updated:

https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/start — Rewrote the Exceptions list to be complete and up to date, incorporating this fix among others. Added an example with a description. Updated some formatting.

https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/stop — Updated the Exceptions list. Revised the example a bit. Added example description. Fixed some formatting.

Also added a mention to Firefox 63 for developers.

**Comment by a2sheppy** [comment]
Removed MediaCapabilities work since Estelle has cards for this herself.
