### ISSUE TITLE
Firefox 63 Media DDNs

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#379]
# User story
As a web developer, I want to learn about the new Media, WebRTC, and Web Audio features in Firefox 63, so I can use them in my own projects.

# Acceptance criteria

1. - [ ] All DDNs complete.
2. - [ ] Reviews request from engineers for all documentation work.

# Tasks

## Standalone larger items
_Each with its own estimate._

- [ ] [Add AudioWorkletProcessor interface definitions](https://bugzilla.mozilla.org/show_bug.cgi?id=) (Web Audio) (2 days - together with the next two bugs)
- [ ] [Add "AudioWorklet" definition](https://bugzilla.mozilla.org/show_bug.cgi?id=) (Web Audio)
- [ ] [Remove audioWorklet attribute from Window](https://bugzilla.mozilla.org/show_bug.cgi?id=) (Web Audio)
- [ ] [Implement supports for MediaCapabilities object](https://bugzilla.mozilla.org/show_bug.cgi?id=) (Audio/Video: Playback)

## Smaller items estimated together

Total estimate — 2 days

- [x] [Remove the doppler effect from the PannerNode](https://bugzilla.mozilla.org/show_bug.cgi?id=) (Web Audio) (0.25 days)
- [ ] [Emit new SCTP data channel offer format in Fx >= 62](https://bugzilla.mozilla.org/show_bug.cgi?id=) (WebRTC: Signaling) (0.25 days)
- [ ] [Add deprecation warning for removal of stat.isRemote in 65.](https://bugzilla.mozilla.org/show_bug.cgi?id=) (WebRTC) (0.25 days)
- [x] [Mark ctor-constantsource.html as passing, since bug 1456266 landed](https://bugzilla.mozilla.org/show_bug.cgi?id=) (Web Audio) (0.25 days)
- [ ] [ConstantSourceNode.start(-1) should throw RangeError](https://bugzilla.mozilla.org/show_bug.cgi?id=) (Web Audio) (0.25 days)
- [ ] [setValueCurveAtTime doesn't accept sequence<float>](https://bugzilla.mozilla.org/show_bug.cgi?id=) (Web Audio) (0.25 days)
- [ ] [Expose to web content whether autoplay is blocked](https://bugzilla.mozilla.org/show_bug.cgi?id=) (Audio/Video: Playback) (0.25 days)
- [ ] [Rename RTCRTPStreamStats to match the spec RTCRtpStreamStats](https://bugzilla.mozilla.org/show_bug.cgi?id=) (WebRTC) (0.25)

**Comment by chrisdavidmills** [comment]
I already created this dude — https://github.com/mdn/sprints/issues/374 ;-)

**Comment by a2sheppy** [comment]
I was already working on this before you created it :)
