### ISSUE TITLE
bug 1477468 - Redirect request for /en-US/docs/Mozilla/QA/Marionette

### ISSUE THREAD

**Issue by escattone** [mdn/sprints#381]
# User story
As an MDN user, I want all requests for "docs/Mozilla/QA/Marionette", as well as its children, to be redirected to their appropriate pages on "https://firefox-source-docs.mozilla.org", like "https://firefox-source-docs.mozilla.org/testing/marionette/marionette/".

# References
* [bug 1477468](https://bugzilla.mozilla.org/show_bug.cgi?id=1477468) - Redirect request for /en-US/docs/Mozilla/QA/Marionette

# Acceptance criteria
* All requests for "docs/Mozilla/QA/Marionette", its existing children, and all of their translations, redirect to their appropriate page on "https://firefox-source-docs.mozilla.org".
* All of the documents and their translations above have been deleted (soft deleted).
* Tests exist that check for the proper redirections for all of the documents and their translations

# Tasks
* [x] List all of the documents and their translations that should be redirected or deleted
* [ ] Add redirects for all of the documents in the English locale
* [x] Delete all of the documents that should be deleted
* [ ] Add tests for all cases

**Comment by escattone** [comment]
I will add a comment to the Bugzilla bug tomorrow, but wanted to capture my research here as well:

# Marionette documents (including redirects and deleted)

## Slugs starting with `Mozilla/QA/Marionette`
- en-US Mozilla/QA/Marionette
    - fr Mozilla/QA/Marionette (REDIRECT)
    - ja Mozilla/QA/Marionette (REDIRECT)
    - pl Mozilla/QA/Marionette
    - pt-BR Mozilla/QA/Marionette (REDIRECT)
    - ru Marionette (REDIRECT)
    - zh-CN Mozilla/QA/Marionette (REDIRECT)
- en-US Mozilla/QA/Marionette/Builds
    - ja Mozilla/QA/Marionette/Builds (DELETED BY ME)
    - ru Marionette/Builds (DELETED BY ME)
-en-US Mozilla/QA/Marionette/Client
-en-US Mozilla/QA/Marionette/Connecting_to_B2G  (DELETED)
    - ja Mozilla/QA/Marionette/Connecting_to_B2G
    - pt-BR Mozilla/QA/Marionette/Conectando_ao_B2G
en-US Mozilla/QA/Marionette/Developer_setup
    - ja Mozilla/QA/Marionette/Developer_setup (REDIRECT)
- en-US Mozilla/QA/Marionette/Emulator  (DELETED)
- en-US Mozilla/QA/Marionette/EmulatorBattery  (DELETED)
- en-US Mozilla/QA/Marionette/Marionette  (DELETED)
- en-US Mozilla/QA/Marionette/MarionetteTestCase
- en-US Mozilla/QA/Marionette/Marionette_JavaScript_Tests  (DELETED)
    - ja Mozilla/QA/Marionette/Marionette_JavaScript_Tests
- en-US Mozilla/QA/Marionette/Marionette_JavaScript_Tools  (DELETED)
- en-US Mozilla/QA/Marionette/Marionette_Python_Tests
- en-US Mozilla/QA/Marionette/Marionette_Python_Tests/Emulator_Integrated_Tests  (DELETED)
- en-US Mozilla/QA/Marionette/Marionette_Test_Runner
- en-US Mozilla/QA/Marionette/Performance_tests  (DELETED)
- en-US Mozilla/QA/Marionette/Protocol
- en-US Mozilla/QA/Marionette/Python_Client (REDIRECT)
- en-US Mozilla/QA/Marionette/Python_Marionette  (DELETED)
- en-US Mozilla/QA/Marionette/Run_ImageMagick_Tool_with_Python_Marionette  (DELETED)
- en-US Mozilla/QA/Marionette/Running_Tests
    - ja Mozilla/QA/Marionette/Running_Tests (REDIRECT)
- en-US Mozilla/QA/Marionette/Setup  (DELETED)
- en-US Mozilla/QA/Marionette/Tests
- en-US Mozilla/QA/Marionette/WebDriver (REDIRECT)
    - fr Mozilla/QA/Marionette/WebDriver (REDIRECT)
    - ja Mozilla/QA/Marionette/WebDriver (REDIRECT)
    - pl Mozilla/QA/Marionette/WebDriver (REDIRECT)
    - zh-CN Mozilla/QA/Marionette/WebDriver (REDIRECT)
- en-US Mozilla/QA/Marionette/WebDriver/status
    - pl Mozilla/QA/Marionette/WebDriver/status

## Slugs starting with `Marionette`
- en-US Marionette (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette)
- ???? en-US Marionette/B2Gisms
- en-US Marionette/Builds (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Builds)
- en-US Marionette/Client (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Client)
- *** 404 *** en-US Marionette/Connecting_to_B2G (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Connecting_to_B2G)
- en-US Marionette/Debugging
- en-US Marionette/Developer_setup (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Developer_setup)
- *** 404 *** en-US Marionette/Emulator (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Emulator)
- *** 404 *** en-US Marionette/EmulatorBattery (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/EmulatorBattery)
- en-US Marionette/Marionette (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Marionette)
- en-US Marionette/MarionetteTestCase (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/MarionetteTestCase)
- *** 404 *** en-US Marionette/Marionette_JavaScript_Tests (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Marionette_JavaScript_Tests)
- *** 404 *** en-US Marionette/Marionette_JavaScript_Tools (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Marionette_JavaScript_Tools)
- en-US Marionette/Marionette_Python_Tests (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Marionette_Python_Tests)
- *** 404 *** en-US Marionette/Marionette_Python_Tests/Emulator_Integrated_Tests (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Marionette_Python_Tests/Emulator_Integrated_Tests)
- *** 404 *** en-US Marionette/Performance_tests (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Performance_tests)
- *** 404 *** en-US Marionette/Python_Marionette (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Python_Marionette)
- en-US Marionette/Running_Tests (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Running_Tests)
- *** 404 *** en-US Marionette/Setup (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Setup)
- en-US Marionette/Tests (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Tests)
- en-US Marionette_Test_Runner (REDIRECT --> /en-US/docs/Mozilla/QA/Marionette/Marionette_Test_Runner)
- ru Marionette (REDIRECT --> /en-US/docs/Marionette)

**Comment by escattone** [comment]
After digesting all of the above, here are my tasks:
### Here are the redirects that I need to create:
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/index.html
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Builds --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/Building.html
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Client --> https://marionette-client.readthedocs.io/en/latest/
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Python_Client --> https://marionette-client.readthedocs.io/en/latest/
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Developer_setup --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/Contributing.html
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/MarionetteTestCase --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Marionette_Python_Tests --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Marionette_Test_Runner --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Running_Tests --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Tests --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Protocol --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/Protocol.html
- [ ] https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status --> https://bugzilla.mozilla.org/showdependencytree.cgi?id=721859&hide_resolved=1
- [ ] https://developer.mozilla.org/en-US/docs/Marionette --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/index.html
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Builds --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/Building.html
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Client --> https://marionette-client.readthedocs.io/en/latest/
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Debugging --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/Debugging.html
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Developer_setup --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/Contributing.html
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/MarionetteTestCase --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Marionette_Python_Tests --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Running_Tests --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Tests --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html
- [ ] https://developer.mozilla.org/en-US/docs/Marionette_Test_Runner --> https://firefox-source-docs.mozilla.org/testing/marionette/marionette/PythonTests.html


### Here are the documents that I need to delete:
- [ ] https://developer.mozilla.org/fr/docs/Mozilla/QA/Marionette
- [ ] https://developer.mozilla.org/ja/docs/Mozilla/QA/Marionette
- [ ] https://developer.mozilla.org/pl/docs/Mozilla/QA/Marionette
- [ ] https://developer.mozilla.org/pt-BR/docs/Mozilla/QA/Marionette
- [ ] https://developer.mozilla.org/ru/docs/Marionette
- [ ] https://developer.mozilla.org/zh-CN/docs/Mozilla/QA/Marionette
- [ ] https://developer.mozilla.org/ja/docs/Mozilla/QA/Marionette/Builds
- [ ] https://developer.mozilla.org/ru/docs/Marionette/Builds
- [ ] https://developer.mozilla.org/ja/docs/Mozilla/QA/Marionette/Connecting_to_B2G
- [ ] https://developer.mozilla.org/pt-BR/docs/Mozilla/QA/Marionette/Conectando_ao_B2G
- [ ] https://developer.mozilla.org/ja/docs/Mozilla/QA/Marionette/Developer_setup
- [ ] https://developer.mozilla.org/ja/docs/Mozilla/QA/Marionette/Marionette_JavaScript_Tests
- [ ] https://developer.mozilla.org/ja/docs/Mozilla/QA/Marionette/Running_Tests
- [ ] https://developer.mozilla.org/fr/docs/Mozilla/QA/Marionette/WebDriver
- [ ] https://developer.mozilla.org/ja/docs/Mozilla/QA/Marionette/WebDriver
- [ ] https://developer.mozilla.org/pl/docs/Mozilla/QA/Marionette/WebDriver
- [ ] https://developer.mozilla.org/zh-CN/docs/Mozilla/QA/Marionette/WebDriver
- [ ] https://developer.mozilla.org/pl/docs/Mozilla/QA/Marionette/WebDriver/status
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Connecting_to_B2G (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Connecting_to_B2G which has been deleted)
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Emulator (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Emulator which has been deleted)
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/EmulatorBattery (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/EmulatorBattery which has been deleted)
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Marionette (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Marionette which doesn't exist)
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Marionette_JavaScript_Tests (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Marionette_JavaScript_Tests which has been deleted)
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Marionette_JavaScript_Tools (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Marionette_JavaScript_Tools which has been deleted)
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Marionette_Python_Tests/Emulator_Integrated_Tests (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Marionette_Python_Tests/Emulator_Integrated_Tests which has been deleted)
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Performance_tests (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Performance_tests which has been deleted)
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Python_Marionette (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Python_Marionette which has been deleted)
- [ ] https://developer.mozilla.org/en-US/docs/Marionette/Setup (currently a redirect to https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/Setup which has been deleted)


### I don't know what to do with this one:
- https://developer.mozilla.org/en-US/docs/Marionette/B2Gisms

**Comment by escattone** [comment]
This has been pushed to production, and passes the tests:
```
(mdntest) rjohnson-25186:kuma rjohnson$ pytest --base-url https://developer.mozilla.org tests/headless/test_redirects.py::test_marionette_redirects
=============================================== test session starts ===============================================
platform darwin -- Python 2.7.15, pytest-3.1.3, py-1.4.33, pluggy-0.4.0
metadata: {'Python': '2.7.15', 'Driver': None, 'Capabilities': {}, 'Base URL': 'https://developer.mozilla.org', 'Platform': 'Darwin-17.7.0-x86_64-i386-64bit', 'kuma': {u'services': {u'search': {u'available': True, u'count': 61210, u'populated': True}, u'kumascript': {u'available': True, u'revision': u'519b2fd2e829e9e9344d369dc16aab5e7a09c1d7'}, u'test_accounts': {u'available': False}, u'database': {u'available': True, u'document_count': 131306, u'populated': True}}, u'version': 1, u'request': {u'url': u'https://developer.mozilla.org/_kuma_status.json', u'is_secure': True, u'host': u'developer.mozilla.org', u'scheme': u'https'}, 'response': {'headers': {'X-Cache': 'Miss from cloudfront', 'strict-transport-security': 'max-age=63072000', 'x-content-type-options': 'nosniff', 'Content-Language': 'en-US', 'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Expires': 'Wed, 31 Oct 2018 22:32:12 GMT', 'Vary': 'Accept-Encoding', 'Server': 'meinheld/0.6.1', 'Connection': 'keep-alive', 'x-xss-protection': '1; mode=block', 'X-Amz-Cf-Id': '_REw-0BAwsizya_PiRTF23D7wrv08pQYIUKJzGXxIto9MWarzj600Q==', 'Cache-Control': 'no-cache, no-store, must-revalidate, max-age=0', 'Date': 'Wed, 31 Oct 2018 22:32:11 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Via': '1.1 97c5dcf9c391508cdebbbfdcf304912f.cloudfront.net (CloudFront)'}}, u'settings': {u'ATTACHMENT_HOST': u'mdn.mozillademos.org', u'PROTOCOL': u'https://', u'INTERACTIVE_EXAMPLES_BASE': u'https://interactive-examples.mdn.mozilla.net', u'MAINTENANCE_MODE': False, u'STATIC_URL': u'https://developer.mozilla.org/static/', u'SITE_URL': u'https://developer.mozilla.org', u'ATTACHMENT_ORIGIN': u'demos-origin.mdn.mozit.cloud', u'DEBUG': False, u'ALLOWED_HOSTS': [u'developer.mozilla.org', u'cdn.mdn.mozilla.net', u'mdn.mozillademos.org', u'demos.mdn.mozit.cloud', u'demos-origin.mdn.mozit.cloud', u'developer-prod.mdn.mozit.cloud', u'prod.mdn.mozit.cloud', u'developer.mozilla.com', u'mdn.mozilla.org', u'developer-new.mozilla.org', u'developers.mozilla.org'], u'REVISION_HASH': u'f5edc039881450fc0e7bc9f5a4c87056814afc80', u'LEGACY_HOSTS': [u'cdn.mdn.mozilla.net', u'developer.mozilla.com', u'mdn.mozilla.org', u'developer-new.mozilla.org', u'developers.mozilla.org']}}, 'Plugins': {'variables': '1.7.1', 'selenium': '1.14.0', 'rerunfailures': '2.1.0', 'html': '1.16.1', 'base-url': '1.4.1', 'metadata': '1.5.1'}, 'Packages': {'py': '1.4.33', 'pytest': '3.1.3', 'pluggy': '0.4.0'}}
baseurl: https://developer.mozilla.org
sensitiveurl: .* *** WARNING: sensitive url matches https://developer.mozilla.org ***
rootdir: /Users/rjohnson/repos/kuma, inifile: pytest.ini
plugins: metadata-1.5.1, base-url-1.4.1, variables-1.7.1, html-1.16.1, selenium-1.14.0, rerunfailures-2.1.0
collected 176 items

tests/headless/test_redirects.py ................................................................................................................................................................................

=========================================== 176 passed in 29.21 seconds ===========================================
```
