### ISSUE TITLE
add a page for CSS new min(), max() and clamp() functions

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#385]
##  User Story
https://bugzilla.mozilla.org/show_bug.cgi?id=1404579

## Tasks

- [x] - Create min page
- [x] - compat table
- [x] - examples

- [x] - Create max() page
-  [x] - compat table
- [x] - examples

- [] - Create clamp() page
-  [] - compat table
- [] - examples

- [] - close ticket

## Acceptance Criteria

Completion of above tasks
