### ISSUE TITLE
Make IE performance metrics more reliable

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#394]
# User story
As an MDN developer, I want the interactive example loading event to be reliably handled, so that I have confidence in the page load KPI measurements.

# References
* [bug 1468271](https://bugzilla.mozilla.org/show_bug.cgi?id=1468271). [Comment #8](https://bugzilla.mozilla.org/show_bug.cgi?id=1468271#c8) describes the issue.
* https://github.com/mozilla/kuma/pull/4875 - A PR that detects the problem and discards it.

# Acceptance criteria
* Significant reduction in "mark 'interactive-editor-loading' not available" events

# Tasks
* [x] Split message handler and required components from ``wiki.js``
* [x] Move message handler into ``<head>``
* [ ] (Maybe) Move MDN event helpers to ``<head>``

**Comment by schalkneethling** [comment]
@jwhitlock @atopal I can confirm that this happens on slower network connections. Below is a screenshot of some of the logging on a good network connection:

![Screen Shot 2018-08-15 at 13.28.26.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/afddb891-1936-44a6-adb8-94509cba54fa)

And here is what happens on a slower(Fast 3G in Chrome) connection:

![Screen Shot 2018-08-15 at 13.29.34.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/37f94707-23a4-4eac-be1a-53015089a9ab)

You can here clearly see the missing `KUMA` logs, which means the message handler is not catching those post events. There are a ton of script to download at the bottom of the page, and as a result it takes longer to download, parse and execute the `post-message-handler` and related scripts. Therefore the events fired from the inlined script in the `head` of the iframe happens sooner.

This poses a problem because there is a dependency tree with regards to the script. This is as follows:

`post-message-handler.js` depends on `perf.js`, which depends on `utils.js`
`post-message-handler.js` also depends on `analytics.js` which in turn depends on `jquery.js`

The last of these really throws in a spanner in the works, as you can see from the screenshot below:

![Screen Shot 2018-08-15 at 13.36.05.png](https://images.zenhubusercontent.com/59bd517eb0222d5de477f8fb/beb236f5-4aa8-49fe-8f9f-d396e7583204)

This is a long way to say, inlining is not going to be a simple exercise. All is not lost though ;) For the `interactive-editor-loading` metric we only set a performance mark. We do not do any measure at this point, nor do we send anything to analytics.

This happens for `ie-time-to-interactive` and `ie-time-to-complete`. I therefore propose that I write a small script, that we can inline in the `head` of Kuma with the sole purpose of handling the `interactive-editor-loading` event and setting a mark.

This will ensure that

1. This metric is set consistently
2. The two events, measures and posts to GA succeed as the `interactive-editor-loading` will always be set by the time the latter is received and executed.

But wait, no that I think about it, at slow speeds even `ie-time-to-interactive` and `ie-time-to-complete` are not being caught :-/ The way to get around all of this would then be

1. Inline perf.js in the head
2. Handle all three post messages `interactive-editor-loading`, `ie-time-to-interactive` and `ie-time-to-complete`. Setting marks and measures as appropriate.
3. We will also need to create an array of two objects as we post metrics to GA for both `ie-time-to-interactive` and `ie-time-to-complete`. However, at this point in execution `analytics.js` will not yet be available. We therefore need a new function, perhaps in `analytics.js`, that `onload` loops through the array, and sends the "cached" metrics to GA.

This brings up another questions though.

If Speedcurve provides data on the performance marks and measures we set, do we still need to send these to GA as well? Not having this dependency will make the above a much simpler task.

Let me know your thoughts. Thanks!

**Comment by schalkneethling** [comment]
I sent a report through GA with regards to the error which seemed to suggest the error rate has gone down significantly. However, @atopal also looked at GA and sees it differently. My GA foo is weak so, I will definitely trust his report more ;)

**Comment by schalkneethling** [comment]
Nope, nope. That was a broken report. The issue is still there.

**Comment by jwhitlock** [comment]
The latest fix went to production on Monday, August 20. The fix is looking good, but I'd like a full day of events before calling it done. Here's the data, with some older numbers from PR #4875:

|Date|ie-time-to-interactive Samples|ie-time-to-complete Samples|JS Errors|Sample to Error Ratio|
|---|---|---|---|---|
|Wednesday, July 4|1840|1839|62611|34.0|
|Thursday, July 5|1979|1978|73348|37.1|
|Friday, July 6|1730|1721|62908|36.4|
|Saturday, July 7|789|789|22694|28.8|
|Sunday, July 8|1558|1553|24034|15.5|
|Monday, July 9|3816|3814|52578|13.8|
| | | | |
|Tuesday, August 14|2858|2850|104537|36.7|
|Wednesday, August 15|1751|1752|91406|52.2|
|Thursday, August 16|2047|2042|103503|50.7|
|Friday, August 17|1853|1850|92716|50.1|
|Saturday, August 18|776|770|34221|44.4|
|Sunday, August 19|1572|1572|34844|22.2|
|**Monday, August 20**|3325|3310|88273|26.7|

**Comment by schalkneethling** [comment]
Thanks for gathering all the data @jwhitlock

**Comment by atopal** [comment]
Looks like this is done. I see less than 100 errors per day down from 100k per day.

**Comment by jwhitlock** [comment]
We've eliminated the source of the errors for performance marks (in GA, User Timings → RUM - Interactive Examples → ie-time-to-complete / ie-time-to-interactive). The small number of errors are associated with the old version of ``wiki.js``. Someone somewhere has a cached copy of pages.

There are other performance metrics that may be missed, but aren't causing errors (In GA, User timings → Interactive Examples → JS editor load time / CSS editor load time / Tabbed editor load time). If the ``<iframe>`` completes loading and sends a 'load complete' message before the message handler in ``wiki.js`` is registered, then the performance metric won't be measured. I think the effect would be to lose fast load times from repeat visitors when ``wiki.js`` changes (interactive sample is loaded from browser cache, but `wiki.js` requires a re-download). In this case, the IE sample would load faster than the MDN page, which may be an invalid result anyway.

It's hard, maybe impossible to get into this situation in local development. I think it is happening in production for some percentage of traffic. I'm not sure how to measure the number of affected visitors, or even prove it is more than zero, since we'd be trying to measure when an event should happen but didn't. We'd eliminate the chance by moving all message handlers into the ``<head>``, like we did for this one. Our asset pipeline makes this harder than it should be. 

There's other minor issues - JS errors in staging because ``ga`` is undefined. There's still 30k - 50k JavaScript errors a day. But I think we can close this for now, and move on to other things.

**Comment by atopal** [comment]
@jwhitlock hmm, yeah, that's not ideal. The one case you outlined seems rather unlikely to be significant though. Interactive example content is cached for only 30 minutes. So, from what I can tell, it would only apply in cases where wiki.js changes and people come back within 30 minutes of that change. Let me know if I'm misunderstanding, or if that was just one of many possible scenarios.

**Comment by jwhitlock** [comment]
It lowers my confidence in the metrics, especially the 90% KPI metrics, but I don't think that should be a blocker. I'd expect the metrics to be directionally correct - an increase or decrease in metrics should roughly follow an increase or decrease in page load times for real users. There is a possible exception in China, which we know has unexpected load times due to cache timeouts, and may behave the opposite of what you guessed

A co-worker thought the way to work around it would be two-way communication - the parent frame would send a message to the iframe message handler, which would then reply, and send any queued metrics. I think this doesn't help with performance marks, which must be registered at the time of the event. However, it could be used to measure this error rate. The iframe could keep track of when it would have sent a performance mark, but it hadn't gotten the "Hello" from the parent frame yet, and then send an error event when then parent wakes up. This would give us a real measurement of how often, if ever, this issue occurs. It's probably twice the work of the solution, but then we'd 1) know there is a problem and 2) measure that it was fixed.
