### ISSUE TITLE
MDN Account Maintenance, Q3S3

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#396]
# User story
As an MDN user, I want to merge or delete my account

# Acceptance criteria
Account help requests opened at the start of the sprint are closed

# Tasks

- [x] [bug 1479674](https://bugzilla.mozilla.org/show_bug.cgi?id=1479674) - requested more info
- [x] [bug 1481020](https://bugzilla.mozilla.org/show_bug.cgi?id=1481020) - closed INCOMPLETE, can not contact reporter
- [x] [bug 1480011](https://bugzilla.mozilla.org/show_bug.cgi?id=1480011) - requested more info. No response in 1 week, closed INVALID
- [x] [bug 1476960](https://bugzilla.mozilla.org/show_bug.cgi?id=1476960) - closed INCOMPLETE, no response from reporter in 3 weeks.
- [x] [bug 1476961](https://bugzilla.mozilla.org/show_bug.cgi?id=1476961) - closed FIXED
- [x] [bug 1481702](https://bugzilla.mozilla.org/show_bug.cgi?id=1481702) - closed INVALID
