### ISSUE TITLE
Firefox 63 Layout DDNs Part 2

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#436]
# User story
As a web developer, I want to learn about the new Layout features in Firefox 63, so I can use them in my own projects.

# Acceptance criteria

1. - [ ] All DDNs complete.
2. - [ ] Reviews request from engineers for all documentation work.

# Tasks

## Standalone larger items

1. [x]  [[css-logical] Flow-Relative Values for the "resize" Property](https://bugzilla.mozilla.org/show_bug.cgi?id=1464786) [1 day at most, needs a simple check?]
2. [x]  [Add initial support of scrollbar-width](https://bugzilla.mozilla.org/show_bug.cgi?id=1475033) [1 day]
3. [ ]  [Implement path() function for offset-path](https://bugzilla.mozilla.org/show_bug.cgi?id=1429298) [1 day, page exists but needs structure sorting out; BCD needs updating]
4. [ ] [-webkit pseudo selectors makes the CSS rules fail.](https://bugzilla.mozilla.org/show_bug.cgi?id=1424106) [1 day, not much content but need to investigate where to put it]
5. [ ]  [Add support for |clip-path: path()|](https://bugzilla.mozilla.org/show_bug.cgi?id=1246764) [1.5 days]

## Smaller items estimated together

1.  [ ] [Tracking -moz-scrollbars-none when creating webcompat issues.] (https://bugzilla.mozilla.org/show_bug.cgi?id=1481125)
2.  [x] [swap values of 2-value 'overflow' syntax so block is first and inline is second] (https://bugzilla.mozilla.org/show_bug.cgi?id=1481866)
