### ISSUE TITLE
MDN Account Maintenance, Q3S4

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#448]
# User story
As an MDN user, I want to merge or delete my account

# Acceptance criteria

Account help requests opened at the start of the sprint are closed

# Tasks

* [x] [bug 1484423](https://bugzilla.mozilla.org/show_bug.cgi?id=1484423) - No response in 11 days, closed INVALID
* [x] [bug 1484569](https://bugzilla.mozilla.org/show_bug.cgi?id=1484569) - Closed fixed
* [ ] [bug 1485489](https://bugzilla.mozilla.org/show_bug.cgi?id=1485489) - in process

**Comment by jwhitlock** [comment]
bug 1485489 moved to https://github.com/mdn/sprints/issues/500
