### ISSUE TITLE
bug 1469079 - Delete unpopular localizations

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#449]
# User story
As a MDN user or staff, I want to delete localizations with less than 10 page views per day, because they create overhead.

# References

* [bug 1469079](https://bugzilla.mozilla.org/show_bug.cgi?id=1469079) - Delete localizations with less than 10 page views per day
* [bug 1425357](https://bugzilla.mozilla.org/show_bug.cgi?id=1425357) - Please archive and remove Romanian localization from MDN UI
* [bug 1483763](https://bugzilla.mozilla.org/show_bug.cgi?id=1483763) - Remove Czech from MDN
* [bug 1476093](https://bugzilla.mozilla.org/show_bug.cgi?id=1476093) - Redirect https://developer.mozilla.org/son/docs/Tools to /docs/Tools

# Acceptance criteria
* [ ] Translated documents are removed from MDN (404)
* [ ] Translations are removed from Pontoon (archived)
* [ ] Locales are 404

# Tasks
* [ ] Delete and purge [14 Srpski (sr-Latn) docs](https://developer.mozilla.org/sr-Latn/docs/all)
* [ ] Delete and purge [32 Hrvatski (hr) docs](https://developer.mozilla.org/hr/docs/all)
* [ ] Delete and purge [23 Српски (sr) docs](https://developer.mozilla.org/sr/docs/all)
* [ ] Delete and purge [72 Afrikaans (af) docs](https://developer.mozilla.org/af/docs/all)
* [ ] Delete and purge [47 ქართული (ka) docs](https://developer.mozilla.org/ka/docs/all)
* [ ] Delete and purge [29 தமிழ் (ta) docs](https://developer.mozilla.org/ta/docs/all)
* [ ] Delete and purge [31 Shqip (sq) docs](https://developer.mozilla.org/sq/docs/all)
* [ ] Delete and purge [22 Azərbaycanca (az) docs](https://developer.mozilla.org/az/docs/all)
* [ ] Delete and purge [2 Pulaar-Fulfulde (ff) docs](https://developer.mozilla.org/ff/docs/all)
* [ ] Delete and purge [23 മലയാളം (ml) docs](https://developer.mozilla.org/ml/docs/all)
* [ ] Delete and purge [3 తెలుగు (te) docs](https://developer.mozilla.org/te/docs/all)
* [ ] Delete and purge [14 Tagalog (tl) docs](https://developer.mozilla.org/tl/docs/all)
* [ ] Delete and purge [4 Yorùbá (yo) docs](https://developer.mozilla.org/yo/docs/all)
* [ ] Delete and purge [4 Kiswahili (sw) docs](https://developer.mozilla.org/sw/docs/all)
* [ ] Delete and purge [4 isiZulu (zu) docs](https://developer.mozilla.org/zu/docs/all)
* [ ] Delete and purge [7 Gaeilge (ga-IE) docs](https://developer.mozilla.org/ga-IE/docs/all)
* [ ] Delete and purge [4 isiXhosa (xh) docs](https://developer.mozilla.org/xh/docs/all)
* [ ] Delete and purge [4 Hausa (ha) docs](https://developer.mozilla.org/ha/docs/all)
* [ ] Delete and purge [4 Igbo (ig) docs](https://developer.mozilla.org/ig/docs/all)
* [ ] Delete and purge [3 Setswana (tn) docs](https://developer.mozilla.org/tn/docs/all)
* [ ] Delete and purge [4 Eʋe (ee) docs](https://developer.mozilla.org/ee/docs/all)
* [ ] Delete and purge [6 Frysk (fy-NL) docs](https://developer.mozilla.org/fy-NL/docs/all)
* [ ] Delete and purge [4 Lingála (ln) docs](https://developer.mozilla.org/ln/docs/all)
* [ ] Delete and purge [3 Malagasy (mg) docs](https://developer.mozilla.org/mg/docs/all)
* [ ] Delete and purge [7 Wolof (wo) docs](https://developer.mozilla.org/wo/docs/all)
* [ ] Delete and purge [5 Soŋay (son) docs](https://developer.mozilla.org/son/docs/all)
* [ ] Delete and purge [252 Romanian (ro) docs](https://developer.mozilla.org/ro/docs/all)
* [ ] Delete and purge [265 Czech (cs) docs](https://developer.mozilla.org/cs/docs/all)
* [ ] Reset preferences for users choosing one of these locales
* [ ] Remove language from ``ACCEPTED_LOCALES``, migrate, deploy
* [ ] Archive locales in [Pontoon](https://pontoon.mozilla.org/projects/mdn/)
