### ISSUE TITLE
Create technical foundation for inlining interactive examples

### ISSUE THREAD

**Issue by hobinjk** [mdn/sprints#453]
# Tasks
- [ ] Improve the lintability of the interactive-example JSON and source format (#454)
- [ ] Implement a basic readability and security linter for JS examples
- [ ] Implement a basic readability and security linter for simple HTML examples
- [ ] Implement a basic readability and security linter for CSS examples (and their associated HTML)
- [ ] Implement a basic readability and security linter for complex HTML examples with inline JS/CSS
- [ ] Run linting as part of CI pipeline

# Acceptance criteria
- [ ] Linting pipeline works, catching potential security/readability issues in PRs
- [ ] All format changes/requirements are documented properly

# Linting
As a developer I want to automatically verify that simple JS examples are free of potential security vulnerabilities and readability issues

## Linting acceptance criteria
- [ ] Running the linter on interactive-examples comes up with no errors
- [ ] Attempting to introduce a readability or security issue causes linting to fail
