### ISSUE TITLE
Manually inline a subset of interactive examples

### ISSUE THREAD

**Issue by hobinjk** [mdn/sprints#467]
Allow us to evaluate the effect of inlining in terms of real user performance 

# Acceptance criteria
- [x] All specified interactive examples are inlined
- [x] Analytics are being recorded for the IEs

# Tasks
- [x] Resources for IEs are also inlined or are hosted within kuma without conflicts
- [x] Inlined on:
  - [x] [Array/forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)
  - [x] [Array/map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)
  - [x] [Array/filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)
  - [x] [Array/find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)
  - [x] [Array/Reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)
  - [x] [Array/splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)

# Resources
* [bug 1504246](https://bugzilla.mozilla.org/show_bug.cgi?id=1504246)
* [Test plan](https://docs.google.com/document/d/1KVXeCU31qPVHxJnxSjoPREv3rKiQEXDku5jJlQaJ47g/edit?usp=sharing)

**Comment by atopal** [comment]
Slight correction to the pages we'd have this on. The array overview page doesn't have an interactive example, I missed that earlier. These pages together have about 50k/page views per day, so we should see results within days.

**Comment by jwhitlock** [comment]
We're getting a similar number of events on the Array pages today as we did yesterday, so this code appears to be working.

I'd like to track the data review and next actions as an issue for the next sprint, so that we can count this as done for sprint 2.
