### ISSUE TITLE
Track Irene's Bugs

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#480]
I discovered some P1 (and otherwise) bugs that were assigned to me but not added to any sprint. I will add these bugs as children of this epic which is scheduled for Q4, Sprint 1.

# Acceptance Criteria
- [x] sprints#412 Firefox for Android only supports a saveAs value of false
- [x] sprints#476 Correct info about new debugger UI0.25
- [x] sprints#481 Fix small error in CSS List styling example0.25
- [ ] sprints#482 Document considerations for browser-style=true1
- [ ] sprints#486 webNavigation API: Document all transition types0.25
- [x] sprints#488 Iterator Example
- [x] sprints#491 Clarify/update description of how to examine event listeners

**Comment by jmswisher** [comment]
Is this epic continuing in Bessie Smith? I don't see it in the tracking spreadsheet.

**Comment by chrisdavidmills** [comment]
@irenesmith did the last couple of these get done? should we just close this and then retriage them?
