### ISSUE TITLE
Document considerations for browser-style=true

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#482]
[1479003](https://bugzilla.mozilla.org/show_bug.cgi?id=1479003) Document the consideration for using browser-style = true in a web extension

# Tasks
- [x] Research the use of browser-style = true in creating a browser extension
- [x] Add a section to the appropriate browser extension documentation page describing the concerns.

# Acceptance Criteria
- [x] Documentation has been updated to describe the potential concerns involved in using browser styling in a web extension.

**Comment by irenesmith** [comment]
Content reviewed and LGTM from Shane Caraveo on the Bugzilla Bug #[1404724](https://bugzilla.mozilla.org/show_bug.cgi?id=1404724)
