### ISSUE TITLE
MDN Account Maintenance, Q4S1

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#500]
# User story
As an MDN user, I want to merge or delete my account

# Acceptance criteria

Account help requests opened at the start of the sprint are closed

# Tasks

* [x] [bug 1485489](https://bugzilla.mozilla.org/show_bug.cgi?id=1485489) - user regained access
* [x] [bug 1491684](https://bugzilla.mozilla.org/show_bug.cgi?id=1491684) - user regained access
* [x] [bug 1493904](https://bugzilla.mozilla.org/show_bug.cgi?id=1493904) - deleted
* [X] [bug 1494265](https://bugzilla.mozilla.org/show_bug.cgi?id=1494265) - Firefox Accounts query, moved to Cloud Services
* [X] [bug 1495644](https://bugzilla.mozilla.org/show_bug.cgi?id=1495644) - closed INVALID, no response from user
