### ISSUE TITLE
MDN Payments Shipped

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#502]
# User story
As an MDN reader, I want to pay MDN, to show my appreciation and support future work

# Acceptance criteria
**TODO: @atopal**

* [x] A call-to-action to Give Back to MDN is shown to some visitors to MDN
* [x] A visitor can make a payment to MDN
* [x] Analytics are collected to validate the experiment

# Resources

* https://developer.mozilla.org/en-US/contribute - on production
* https://developer.allizom.org/en-US/contribute - on staging, test API credentials
* https://trello.com/b/Q1axkiB9 - Private task board, Potato
* (TODO: Blog post)
