### ISSUE TITLE
Document Theme Experiments

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#503]
As a theme author and reader of MDN web docs, I want to be able to access documentation on the subject of theme experiments as described in Bugzilla #[1347207](https://bugzilla.mozilla.org/show_bug.cgi?id=1347207).

This bug describes creating experimental theme features by adding a "theme_experiment" key to manifest.json.

# Tasks
- [ ] Determine what has been proposed and what has been implemented for this feature
- [ ] Get a list of the topics that need to be documented and estimate the scope of work needed
- [ ] Write new documentation for theme experiments
- [ ] Create a sample of a theme that includes a "theme_experiment" key

# Acceptance Criteria
- [ ] A description of the implemented work (by FF release) has been added to this issue
- [ ] A list of topics to be created has been added
- [ ] New documentation created

**Comment by rebloor** [comment]
Theme experiment details are published: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme_experiment
