### ISSUE TITLE
Reorganize the "Distribution Options" docs

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#546]
# User Stories
As a reader of the Browser Extensions documentation, I want clear and up-to-date information on distributing my extension through AMO

# Details
Reorganize the "Distribution Options" part of the docs.

**Note:** This topic is not in the right place in MDN - it is currently under the topic of "add-ons" when it should be under "web extensions." Talked to Irene about re-org.

##Related Issue
Add-ons Trello Board: [Launchpad: Distribution Options](https://trello.com/c/7acATX5S/88-launchpad-distribution-options)

## Tasks

- [x] [Alternative Distribution Options](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Alternative_distribution_options): Rename document as "Distribution Options"
- [x] Document revised to include description of AMO and why you should publish there (content on this available in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution).
- [x] Move topic in sidebar to the Browser Extensions section

# Acceptance Criteria

- [x] Document renamed
- [x] Appropriate information added about AMO from the document listed above.
- [x] Pull request created to update Sidebar menu

**Comment by irenesmith** [comment]
[Pull request](https://github.com/mdn/kumascript/pull/1009) for sidebar update created.
