### ISSUE TITLE
Sort out Fx 64 release notes/other materials

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#623]
# User story
As a developer, I want to read release notes on the new features available in Firefox 64, so I can find out what I can use in my work.

# Acceptance criteria
- [x] Firefox 64 release notes are updated per DDNs and DDCs.
- [x] Experimental Features page is updated per above.
- [x] platform-status is updated accordingly.
- [x] Fx 64 Tweets are drafted.

# Tasks
1. - [x] Run bugzilla query to bring up added Firefox 64 features marked with dev-doc-needed and dev-doc-complete keywords.
2. - [x] Make sure all these features are recorded on the Firefox 64 release notes.
3. - [x] Update Experimental Features page accordingly
4. - [x] Give Fx 64 rel notes a final copy edit
4. - [x] Update platform-status accordingly
5. - [x] Write Fx 64 tweets for Danielle

For the task list, see the relevant roadmap entry: https://trello.com/c/ZUxtUtV3/5-firefox-64-release-notes

**Comment by chrisdavidmills** [comment]
Tweets for Danielle:

* In Firefox 64 DevTools, Responsive Design Mode device selection is now saved between sessions (https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode)
* The CSS Scrollbars spec is supported in Firefox 64 (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars)
* Firefox 64 supports the new Interaction Media Features, such as pointer: coarse (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer)
* The prefers-reduced-motion media feature (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) is supported in Firefox for Android, version 64.
* In Firefox 64, CSS gradient values now support multi-position color stop syntax, e.g. yellow 25%, yellow 50% can now be written yellow 25% 50%.
* The text-transform full-size-kana value is supported in Firefox 64!
* Firefox 64 supports -webkit-appearance and all of its available values, to help alleviate web compatibility issues.
* The well-formed JSON.stringify proposal (https://github.com/tc39/proposal-well-formed-stringify) is supported in Firefox 64, to prevent JSON.stringify from returning ill-formed Unicode strings.
* In Firefox 64, proxied functions can now be be passed to Function.prototype.toString.call().
* The Fullscreen API (https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) is supported unprefixed and up-to-date with the latest spec, as of Firefox 64!
* Firefox 64 sees the WebVR 1.1 API (https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API) re-enabled on macOS.
* In Firefox 64, Window.screenLeft and Window.screenTop have been implemented, as aliases of Window.screenX and Window.screenY.
* The XMLHttpRequest.getAllResponseHeaders() method now returns header names all in lowercase in Firefox 64, as per spec.
* Firefox 64 sees Navigator.buildID returning a fixed timestamp, as a privacy measure (https://developer.mozilla.org/en-US/docs/Web/API/Navigator/buildID).
* The ServiceWorkerContainer.startMessages() method is implemented in Firefox 64.
* Referrer-Policy can be used to govern resources fetched via stylsheets in Firefox 64 onwards (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#Integration_with_CSS)
* In Firefox 64 a new API, browser.menus.overrideContext(), can be called from the contextmenu DOM event to set a custom context menu in add-on pages.
* In Firefox 64 you can now restrict where context menus can appear in an add-on using the new viewTypes property in menus.create() and menus.update()
* In add-ons in Firefox 64 onwards, menus.update() can be used to update the icon of an existing menu item.
* Firefox 64 add-ons can use the new userScripts API, which will allow add-ons to register userScripts to be injected into webpages that they match.
* The Firefox 64 Browser extensions implementation includes the devtools.panels.elements Sidebar.setPage() method.
* In Firefox 64 onwards, browser extensions can include a new pinned property in the page_action manifest key, which enables extensions to control whether their page actions should be pinned to the location bar on install or not.
