### ISSUE TITLE
Evaluate page variations experiments

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#628]
# User story
As a product owner, I want to know the next steps for performance improvements, so I can achieve the team performance goals.

# References

- [bug 1503923](https://bugzilla.mozilla.org/show_bug.cgi?id=1503923) - Experiment to measure the page load impact of assets
- [bug 1504246](https://bugzilla.mozilla.org/show_bug.cgi?id=1504246) - Experiment if inline interactive examples will have a sufficient impact on page load versus iframe

# Acceptance criteria
- [ ] experiment without interactive example is completed
- [ ] process to remove unused CSS is decided on
- [ ] work on process is documented (user stories) and started

*TODO: Add Acceptance Criteria*

# Tasks
* Add estimate and level of confidence
* Collect results from the page variant experiment (#527)
* Recommend next changes or experiments
* Rinse and repeat
