### ISSUE TITLE
Evaluate inlined JS interactive examples experiment

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#629]
# User story
As a product owner, I want to plan the next steps on optimizing interactive examples, so I can meet the team's performance goals.

# Acceptance criteria

* [x] Manual inline experiment is reverted
* [x] Results are documented
* [ ] Next steps documented

# Tasks
* [x] Collect page load metrics from manual inline experiment (#467)
* [x] Revert the manual inline experiment (https://github.com/mozilla/kuma/pull/5019)
* [ ] Report on results
* [ ] Decide on next steps / next experiment
* [ ] Repeat

**Comment by jwhitlock** [comment]
Reported on [bug 1504246](https://bugzilla.mozilla.org/show_bug.cgi?id=1504246#c3):

On the test page, the results, averaged over 5 runs, are:

* Interactive example as iframe:
  * Starts at 3.3 seconds
  * Interactive at 3.9 seconds
  * Complete at 4.5 seconds
  * 1.3 seconds to load (complete - start)
* Interactive example as inlined code:
  * Starts at 0.0 seconds
  * Interactive at 0.8 seconds
  * Complete at 3.1 seconds
  * 3.1 seconds to load (complete - start)

Source data, with loading videos, are available for Mozilla employees at: https://docs.google.com/spreadsheets/d/14-Vjq-gmZSB1Y7ZI8jexnowTTpVSJLvrTAS5nMCjbNU/edit?usp=sharing

Inlining examples would have a significant performance gain. However, we're focusing on frontend changes needed to support other 2019 goals at this time.
