### ISSUE TITLE
Storage API Tutorial

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#632]
# User story
As a web developer, I want to understand the uses for the storage API, so I can understand how to use it in my own applications.

Create a tutorial for using the storage API along with a sample application.

# Acceptance criteria
- [x] Sample application created and made available (GitHub) - An existing sample, Quick Note, has been selected.
- [ ] Step by step description of the steps to create the code
- [ ] Tutorial reviewed for clarity
- [ ] Pages published on MDN

# Tasks

1. - [x] Create application that stores an array of objects in local storage
2. - [ ] Describe the considerations for planning such a tutorial
3. - [ ] Guide the user through the coding process
4. - [x] Push the tutorial to the appropriate repo on GitHub
5. - [ ] Create appropriate screenshots to accompany article
6. - [ ] Show how the DevTools can be used to help in debugging the application?
5. - [ ] Publish the tutorial page on MDN in the appropriate location
