### ISSUE TITLE
Sort out Fx 65 rel notes/other activities

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/sprints#656]
# User story
As a developer, I want to read release notes on the new features available in Firefox 65, so I can find out what I can use in my work.

# Acceptance criteria
- [x] Firefox 65 release notes are updated per DDNs and DDCs.
- [x] Experimental Features page is updated per above.
- [x] platform-status is updated accordingly.
- [x] Fx 65 Tweets are drafted.

# Tasks
1. - [x] Run bugzilla query to bring up added Firefox 65 features marked with dev-doc-needed and dev-doc-complete keywords.
2. - [x] Make sure all these features are recorded on the Firefox 65 release notes.
3. - [x] Update Experimental Features page accordingly
4. - [x] Give Fx 65 rel notes a final copy edit
4. - [x] Update platform-status accordingly
5. - [x] Write Fx 65 tweets for Danielle

For the task list, see the relevant roadmap entry: https://trello.com/c/ddCDXNrW/162-firefox-65-release-notes

**Comment by chrisdavidmills** [comment]
Tweets for Danielle:

* New in Firefox 65 DevTools, the JavaScript Debugger now has the ability to set XHR/Fetch breakpoints (https://developer.mozilla.org/en-US/docs/Tools/Debugger/Set_an_XHR_breakpoint).

* As of Firefox 65, you can set the referrerpolicy attribute on script elements (https://developer.mozilla.org/en-US/docs/Web/API/HTMLScriptElement/referrerPolicy).

* break-before, break-after, and break-inside are implemented in Firefox 65, and the legacy page-break-* properties now alias to them (see for example https://developer.mozilla.org/en-US/docs/Web/CSS/break-before). 
* The overflow-wrap property's anywhere value is available in Firefox 65 (https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap).
* A number of -webkit-appearance values (https://developer.mozilla.org/en-US/docs/Web/CSS/appearance) have been implemented in Firefox 65, to improve cross-browser compatibility.
* The behavior of user-select (https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) in Firefox 65 has been changed for better alignment with other browsers.
* CSS environment variables (env()) have been implemented in Firefox 65 (https://developer.mozilla.org/en-US/docs/Web/CSS/env).

* Intl.RelativeTimeFormat has been implemented in Firefox 65 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat).
* In Firefox 65, Strings now have a maximum length of 2**30 - 2 (~1GB) instead of 2**28 - 1 (~256MB).
* The globalThis proposal has been implemented in Firefox 65.

* ReadableStreams have been enabled by default in Firefox 65 (https://developer.mozilla.org/en-US/docs/Web/API/Streams_API#Readable_streams).
* createImageBitmap() (https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap) now supports SVG images (SVGImageElement) as an image source
* In Firefox 65, the ServiceWorkerContainer.register() and WorkerGlobalScope.importScripts() (when used by a service worker) methods will now accept any files with a valid JavaScript MIME type.
* FetchEvent.replacesClientId and FetchEvent.resultingClientId are supported in Firefox 65 (https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent).
* Firefox 65 sees the ServiceWorkerGlobalScope.onmessageerror and ServiceWorkerContainer.onmessageerror handler properties implemented.
* The WebRTC RTCIceCandidateStats dictionary has been updated in Firefox 65 according to the latest spec changes (https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateStats).
* The MediaRecorder (https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) pause and resume events (and their corresponding event handler properties — MediaRecorder.onpause and MediaRecorder.onresume) have now been implemented in Firefox 65.

* WebSockets have been implemented over HTTP/2, in Firefox 65.
* Firefox 65 has support added for WebP images.

* The WebExtension tabs API has support for tab successors

**Comment by chrisdavidmills** [comment]
PR made to platform-status repo: https://github.com/mozilla/platform-status/pull/572
