### ISSUE TITLE
DDN 64: CSS Images Level 4 (Fx 64)

### ISSUE THREAD

**Issue by estelle** [mdn/sprints#662]
Spec URL: [https://drafts.csswg.org/css-images-4/](https://drafts.csswg.org/css-images-4/)
Meta bug: [https://bugzilla.mozilla.org/show_bug.cgi?id=1350068]()

Images, gradient value improvements, etc.

- [X] - https://bugzilla.mozilla.org/show_bug.cgi?id=1352643 - multiple positions
- [ ] - https://bugzilla.mozilla.org/show_bug.cgi?id=700926 - Unify CSS image-value rendering
- [X] - https://bugzilla.mozilla.org/show_bug.cgi?id=1175958" - DDN for Implement conic gradients from CSS Image Values Level 4
- [X] - https://bugzilla.mozilla.org/show_bug.cgi?id=703217 - Implement image() from CSS Image Values and Replaced Content Module Level 4
- [-] -https://bugzilla.mozilla.org/show_bug.cgi?id=711326 - -moz-element() for CSS content, list-style, cursor, border-image and etc.
- [X] -https://bugzilla.mozilla.org/show_bug.cgi?id=1503753 - remove image-rendering:-moz-crisp-edges
