### ISSUE TITLE
Bugs and issues related to one-off and recurring payments

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#678]
Until official hand over on Friday(30 November 2018) from Potato, it is not 100% clear which issues will remain for us to take over. I have gone over the current cards in the Backlog(https://trello.com/b/UdRlUfJg/mdn-recurring-payments-sprints), and seeing that we are already at Thursday(29 November 2018) it seems very likely that these will be the items to take over.

Below is the current list in no particular order. Once hand-over is complete, those that are relevant should be taken from here and:

1. A Bugzilla bug created for each item
2. A sprints issue created referencing the bug
3. Added to the epic and the sprint

@atopal @jwhitlock does this make sense? Thanks!

# Payments backlog

### Refactor: Optimise payment form event handlers and logic

An option for optimising this would be to just apply the click handler to the containing element and use event delegation to check which target has been clicked. This is slightly better for performance and also means we don't have to iterate over the elements.

Would also be good to optimise logic of the payment banner and popover by deprecating jQuery in these handlers.

# Refactor: We should add form variables in the context so we're not writing confusing logic on the form

see attached image.
We have allot of conditional statements in the form.
Maybe instead we can preform this logic in the context and just pass what we need.

![https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5be5725c88bcd06fb5a970f2/246fae833809616d516bfac98330e05c/Screenshot_2018-11-09_at_11.40.23.png](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5be5725c88bcd06fb5a970f2/246fae833809616d516bfac98330e05c/Screenshot_2018-11-09_at_11.40.23.png)

### As a MDN developer I should enforce a max charge to prevent malicious activity

* [ ] Validate in front-end
* [ ] Validate in back-end

### Feature: Payments API can be checked for validity

https://developer.mozilla.org/_kuma_status.json is used to verify real-time configuration of secrets. There should be a "payments" entry under "services":

```json
{
  "services": {
    "payments": {
      "available": true (enabled and valid)
      "public_key": the public key or empty string
      "one_time": true if one-time payments are working (valid keys)
      "recurring": true if recurring payments are working (valid keys, product)
    }
  }
}
```

This can be used as a debug aid, or to run / skip acceptance tests

### Feature: Payments views should be disabled if keys are unset

* If ``STRIPE_PUBLIC_KEY`` is empty, then Stripe will fail to load, and should be equivalent to ``MDN_CONTRIBUTION=False`` (hides forms, 404views)
* If ``STRIPE_SECRET_KEY`` is empty, then payments will fail on submission, and should be equivalent to ``MDN_CONTRIBUTION=False`` (hides forms, 404 views)
* If ``STRIPE_PRODUCT_ID`` is empty, then recurring subscriptions will fail on form submissions. This should disable recurring subscriptions and 404 the recurring views.

### As a developer, I'd like code to use "Payments" instead of "Contributions", so that I can focus on implementation instead of names.

Complete the transition from ``kuma/contributions`` to ``kuma/payments``. These items can be done with other work when it makes sense, and completed in the down time between efforts.

Most name updates have no user impact if done correctly. Changing the name of the waffle flag from ``contrib_beta`` will reset the cohorts. This could be desirable around a change, such as 1% to 5%.

#### Acceptance Criteria

* Flag constant is ``PAYMENTS_BETA_FLAG=contrib_beta`` (``constants.py``)
* Template context is ``payments_X`` (for example, ``payments_enabled``) (``context_processors.py``, ``jinja2/payments/*``)
* Doc strings use ``payments`` (``utils.py``, ``tests/test_views.py``, etc.)
* Form-handling view is ``payments`` or similar (``views.py``)
* Background task is ``payment_thank_you_email`` (``tasks.py``)
* Tooltip for email input says "...receipt of your payment."  (``form.py``)
* IDs and CSS classes are ``payments-X`` or similar (``jinja2/payments/payments.html``, CSS rules, etc.)
* Template block is ``payment_popup`` (``jinja2/base.html``, ``kuma/landing/jinja2/landing/homepage.html``, ``kuma/wiki/jinja2/wiki/document.html)
* Flag names are ``payments_X`` (``payments_beta``, etc.) (**resets cohorts**, be careful)
* Instances of "contrib", "contribution" in the code and templates are ones we want to keep.
* Context processor is ``global_payments_form`` (``context_processors.py``)

### As a MDN developer I want a payment solution to be scalable so that I can alter the interface in the future.

We should record the stripe ID of customers during one-time payments

### “Pay” button not visible after clicking it, when required fields are empty

Env:
Ubuntu 16.04, Firefox 63
Fedora 28, Firefox 63

STR: 
1. Navigate to mdn staging homepage, not logged in 
2. Click "Support MDN" button
3. Leave all the fields empty and click "Pay" button

Expected:
Error messages are displayed, Pay button is visible

Actual:
Error messages are displayed, Pay button is not visible, even after scrolling up/down. See video below.

### Bug: keyboard navigation: The buttons for amount are not selected using Tab key

[Affected versions]:
Firefox, Chrome 

[Affected Platforms]:
Windows 10
   
[Steps to reproduce]:   
1.Go to https://developer.allizom.org/en-US/
2.Press Tab key to navigate through buttons

[Expected result]:
The navigation through the amount selection buttons should work
          
[Actual result]:
The buttons for amount are not selected using Tab key 

Josh Jarvis comments: 

"Reason for this is that the button set is a group of radio inputs.  
On focusing these inputs the user can use the arrow keys to change the value [https://www.w3.org/wiki/RadioButton](https://www.w3.org/wiki/RadioButton)

Maybe we should instead use a collection of buttons that activate a hidden radio selection."

### Edge: The banner is displayed with delay when is expanded/compressed

![2018-11-20_15h05_03.gif](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bf40730e1f68713914d23ce/dcb61e902b7df225d6caad44b549add6/2018-11-20_15h05_03.gif)

### As a user, I want to be able to change the payment method and amount from my MDN profile page.

![Subscriptions_edit_stripe_overlay--inactive.png](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bf41a31f7e66275dbbe1212/963b710a5013633f3f3b4b70ab52f1af/Subscriptions_edit_stripe_overlay--inactive.png)

### As PO, I want to update the design of the MDN sign up page so that new users have a positive impression

Prototype: https://projects.invisionapp.com/d/#/projects/prototypes/16042252

![sign_up--email_active.png](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bd88142e81c4157b7e578e1/060b56f3271aea4973f27fbb88dfd0a5/sign_up--email_active.png)

**Comment by atopal** [comment]
Schalk, thanks for this, but the bugs are the ones in "ready for dev". The "backlog" contains a bunch of new features that we won't implement before next year, if at all. I'd add to "ready for dev" the "design QA" labeled cards in the backlog, if time permits.

**Comment by schalkneethling** [comment]
Revised list based on @atopal comment above:

### UI / a11y: Confirmation checkbox can't be selected by label (vs terms link can't be visited)

Before https://github.com/mozilla/kuma/pull/5101, the checkbox label could be clicked to select the checkbox, which is considered good practice for checkboxes. However, the [Payment Terms](https://developer.mozilla.org/en-US/payments/terms) link could not be clicked, and instead selected the checkbox.

As part of https://github.com/mozilla/kuma/pull/5101, the text was changed so the "visible" label doesn't select the checkbox. This allows [Payment Terms](https://developer.mozilla.org/en-US/payments/terms) to be clicked.

It is unknown if it is possible to implement the original design: a label that selects the checkbox, except for the link, which opens the link.

#### Acceptance Criteria

* [ ] A label that selects the checkbox, except for the link, which opens the link.

### Bug: Remove highlights around inputs on click.

We should remove the grey border/shadow highlight when clicking on elements and only show them when using keyboard interaction.

#### Acceptance Criteria

* [ ] Focus only shown when user starts using keyboard

### The email tooltip is wrongly displayed

Affected versions]:
Firefox, Chrome, Internet Explorer
 
[Affected Platforms]:
Windows 10, Ubuntu 16.04

[Steps to reproduce]:
1.Go to https://developer.allizom.org
2.Click to expand the Support MDN banner
3.Click the “?” icon located in the email field
4.Scroll the page up/down
 
[Actual result]:
Internet Explorer: the email tooltip is displayed at the top of the page. The tooltip is not moved while scrolling
Firefox/Chrome: The tooltip is moved with the page while scrolling

![2018-11-20_15h27_18.gif](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bf40dfd9286ef894f52ff80/617a709f4f1bad451d3a6a95adf0d93a/2018-11-20_15h27_18.gif)

### Bug: Selected state of One off payment doesn’t look good

![one-off-selected-state.png](https://trello-attachments.s3.amazonaws.com/5bc89af9c0ef1601b2316f4b/5bf3e3d2afcacf8a3a5a3b3c/11a17d06109b260440f6d9fd12136b4f/one-off-selected-state.png)

### Design QA: Thank you page

* Left margins should be consistent down the side of the page: payment section copy ('Thank you for supporting MDN...") and the sections below ('Useful things') should have the same margin.
* The secondary headings should align with the footer links (ask Charlie for more info)

### Design QA: Banner shown and Banner open form

* Banner shown: form placeholder text #9B9B9B
* Banner shown: one-off payment brackets should have 16px margin between them
* Banner shown: 'other amount' input should NOT be aligned right
* Banner open: If user is not logged in, after clicking pay button, the white container should keep the same height as the form when showing the sign in button + copy.
* Banner open: `class='control-indicator'` (payment terms checkbox) need 12px margin-right (currently 6px)
* Banner open: `class='control-indicator'` (payment terms checkbox) border should be 2px (currently 3px)
* Banner shown and open: Close banner 'x' should be #222222 (matching the shade of black used elsewhere in the form)
* Banner shown: 'Give back to MDN' is slightly off vertical center
* Banner open: all form inputs margin top should be 16px — as a rule, form spacing, be it padding or margins, should be 16px
* Banner open: pay button should be Arial Bold (700)
* Banner open: `p.legal-copy` — line height should be 20px, currently 1.35 which isn't right, my fault!)

### Design QA: FAQ page and form

* 'FAQ' h1/2 should share the left margin of the 'Give back to MDN' above.
* Anchor links should be blue with an underline
* "was this useful" font-weight 700 (bold)
* Pay button is not in the same place as on the banner: on banner its aligned left, on FAQ page form its kind of in the middle.
* 'FAQ' title should be fixed on scroll

**Comment by jwhitlock** [comment]
Moved remaining issue to #929. Nice work @schalkneethling!
