### ISSUE TITLE
Minimize and Modernize KumaScript, round 1

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#683]
# User story
As a developer, I want to remove unused functionality and modernize the KumaScript engine, so that the page rendering process can be improved.

# Acceptance criteria

* Quick changes, that can be completed in the sprint, are identified
* Updated KumaScript engine is shipped to production
* Longer changes are documented for Q1 sprint planning

# Tasks

Some sample changes:

* [x] Combine, reduce, or eliminate memcache usage
* [x] Simplify or eliminate HTTP caching
* [x] Drop unused ``api.js`` features
* [x] Simplify ``loaders.js`` to one-time load
* [x] Eliminate hirelings pool
* [x] Avoid ``arguments``
* [x] Update to ES6 classes ([issue 960](https://github.com/mdn/kumascript/issues/960))
* [x] Update documentation strings ([PR 959](https://github.com/mdn/kumascript/pull/959))
* [x] Eliminate ``fibers``
* [x] Eliminate ``future``
* [x] Update underscore idioms
* [x] Modernize ``Date`` usage
* [x] Remove ``statsd`` calls

Some research topics:
* [ ] EJS compiling in Kuma process
* [ ] Migrating KumaScript into Kuma codebase

# References

* [bug 1509430](https://bugzilla.mozilla.org/show_bug.cgi?id=1509430) - Modernize the KumaScript standard library codebase

**Comment by ExE-Boss** [comment]
See&nbsp;also [bug&nbsp;1509430](https://bugzilla.mozilla.org/show_bug.cgi?id=1509430), which deals with https://github.com/mdn/kumascript/issues/960, https://github.com/mdn/kumascript/pull/959 and replacing [`arguments`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Functions/arguments) with [rest&nbsp;parameters](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Functions/rest_parameters)

**Comment by davidflanagan** [comment]
I haven't kept up with this tracking issue... 

I ended up going with a maximal approach and basically rewrote KumaScript to use async/await instead of Fibers/hirelings.

KumaScirpt chnages: https://github.com/mdn/kumascript/pull/1035
And the corresponding Kuma changes: https://github.com/mozilla/kuma/pull/5182

Once reviewed and landed, this hits pretty much all the checkboxes in the list of tasks above.

**Comment by jwhitlock** [comment]
I believe the follow-on issues can be tracked in new stories:

* EJS compiling in Kuma process (seems like not yet)
* Migrating KumaScript into Kuma codebase (https://github.com/mdn/kumascript/issues/1034)
* Rebalance production clusters for new loads (https://github.com/mdn/infra/issues/180)
