### ISSUE TITLE
Rename RTCIceCandidateStats.ip to "address"

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#692]
https://bugzilla.mozilla.org/show_bug.cgi?id=1489040

## Acceptance criteria
- [x] Meets Definition of Done for content

## Tasks
- [x] Create page RTCIceCanddiateStats
- [x] Create subpage `address`; include note that the rename occurred in spec
- [x] Create redirect from `ip` to `address`
- [x] Create BCD file `RTCIceCandidateStats.json` with current data

**Verify names before creating pages**
