### ISSUE TITLE
RTCIceCandidateStats: Remove mozLocalTransport and add protocol and relayProtocol

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#693]
https://bugzilla.mozilla.org/show_bug.cgi?id=1435789

## Acceptance criteria
- [ ] Complete all standard criteria for content

## Tasks

- [x] Add page `RTCIceCandidateStats.protocol`
- [x] Add page `RTCIceCanddiateStats.relayProtocol`
- [x] Add page `RTCIceCandidateStats.mozLocalTransport` to simply briefly say to update code using it to use `relayProtocol || protocol` instead
- [x] Ensure BCD reflects these changes
