### ISSUE TITLE
WebRTC setParameters() - changes to scaleResolutionDownBy and maxBitrate are now live

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#694]
https://bugzilla.mozilla.org/show_bug.cgi?id=1253499

## Acceptance criteria
- [x] Meets Definition of Done for content

## Tasks
- [x] Add page for `RTCRtpSendParameters`
- [x] Add page for `RTCRtpSendParameters.encodings`
- [x] Add page for `RTCRtpEncodingParameters.scaleResolutionDownBy`
- [x] Add page for `RTCRtpEncodingParameters.maxBitrate`
- [x] Update BCD to include a new `version_added` section noting this change to `RTCRtpSender.setParameters()`
- [x] Add BCD for `RTCRtpSendParameters`
- [x] Add BCD for `RTCRtpEncodingParameters`

**Comment by a2sheppy** [comment]
This change is actually to how we handle values on the RTCRtpEncodingParameters property, which is used to specify values for one of the members of the RTCRtpSendParameters dictionary, which is what actually gets passed into setParameters(). We document none of those dictionaries yet.

I feel that completing this requires more than just a simple BCD update, and am updating the tasks list to reflect that.
