### ISSUE TITLE
WebXR: Explore and update doc plan

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#695]
The WebXR API is ready to begin documentation work. This sprint, I will explore the API, experimenting with it and building up an understanding of how it all works. Then I will write the initial doc plan and outline.

## Acceptance criteria
- [ ] Doc plan/outline for WebXR is updated and reviewed by WebXR and MDN Content team members.

# Tasks
- [x] Review the specification and/or explainer(s) to get an overall notion of how the API is designed
- [ ] Experiment with existing examples, both trying them out and altering them
- [x] Talk to the WebXR dev team for their insights on priorities
- [ ] Create my own basic example
- [x] Update doc plan/outline
- [x] Get review of plan from WebXR dev team
- [x] Integrate suggestions from dev team
- [x] Get review of plan from someone on the MDN team
- [x] Integrate suggestions from MDN team
