### ISSUE TITLE
Document MediaStreamAudioSourceNode

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#696]
https://bugzilla.mozilla.org/show_bug.cgi?id=1506482

## Acceptance criteria
- [ ] MediaStreamAudioSourceNode and MediaStreamAudioSourceOptions have pages.
- [ ] MediaStreamAudioSourceNode has a simple example.

## Tasks
- [x] Create main page
- [x] Document MediStreamAudioSourceOptions (one subpage)
- [x] Simple example
