### ISSUE TITLE
Developer Tools Documentation Updates

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#699]
# User story
As a user of the Firefox Developer Tools, the images I see in the documentation should match the current state of the UI.

# Acceptance criteria
- [ ] Images and videos have been updated on the pages listed below.

# Tasks
- [ ] Update images on the [Developer Tools Landing Page](https://developer.mozilla.org/en-US/docs/Tools)
- [ ] Update images on the [Page Inspector UI Tour Page](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/UI_Tour)
- [ ] Update images on [Open the Inspector](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Open_the_Inspector)
- [ ] Update images on [Examine and Edit HTML](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML)
