### ISSUE TITLE
Responsive Design Tutorial

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#702]
# User story
As a web designer, I want to understand the concepts related to Responsive Design, so I can create web pages that are responsive and viewable on any device.

## Related issues
[Documentation Roadmap Trello card](https://trello.com/c/heaK1XBZ/66-learning-area-write-responsive-design-module)

# Acceptance criteria
- [ ] A new tutorial has been added to the Learning Area the responsive design process
- [ ] Document has been reviewed by Estelle
- [ ] If changes are identified, changes have been made

# Tasks
- [ ] Create a single page web application that includes responsive design principles
- [ ] Describe the design process
- [ ] Show how to debug the application using Firefox Reponsive Design mode
