### ISSUE TITLE
Epic: Move MDN to new front-end framework (Kuma.Next)

### ISSUE THREAD

**Issue by davidflanagan** [mdn/sprints#766]
This is an epic for design, architecture and prototyping work toward a next-generation version of Kuma using a modern front-end framework. This is related to Epic #231 (Update front-end development workflow) but is more specifically focused on the adoption of a front-end framework and all the tools and infrastructure that goes with that.

### Acceptance criteria
- [ ] The decisions and prototyping work described in issues of this epic are complete (or we decided they were unneeded).
- [ ] The development team is comfortable with the decisions that were made
- [ ] At least two features using the new framework and tools have been deployed

**Comment by jwhitlock** [comment]
2018 work was assigned to Epic #231
