### ISSUE TITLE
SVG: Add example on top of high priority attributes pages [5/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#81]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/id
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/class
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/display
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/style
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/tabindex
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/cursor

**Comment by SebastianZ** [comment]
Additionally to the updates done to the pages (see #95), I've also added top examples to them. (Unfortunately, for some they are not shown due to [bug 1288148](https://bugzilla.mozilla.org/show_bug.cgi?id=1288148).)

Sebastian
