### ISSUE TITLE
Update SVG Documentation

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#82]
The goal of this epic is to track the work necessary to update the SVG documenation on MDN in order to make it both modern (Like CSS and JS doc) and up to date with the latest SVG2 changes.

A compact view of the [work in progress is available on a Google Spreadsheet](https://docs.google.com/spreadsheets/d/17azdgEZUsAqmYqaQDvhjH90Q_kv07mzxLD4Htkqf12c/edit?usp=sharing).

The expected work to do is the following:

**Migrate BCD data**
- SVG elements
  - [x] All high priority SVG elements
  - [x] All med. priority SVG elements
  - [x] All low priority SVG elements
- SVG attributes
  - [x] All high priority SVG attributes
  - [x] All med. priority SVG attributes
  - [x] All low priority SVG attributes
- SVG DOM APIs
  - [x] All high priority SVG DOM APIs
  - [x] All med. priority SVG DOM APIs
  - [ ] All low priority SVG DOM APIs

**Update structure & content**
- SVG elements
  - [x] All high priority SVG elements
  - [ ] All med. priority SVG elements
  - [ ] All low priority SVG elements
- SVG attributes
  - [ ] All high priority SVG attributes
  - [x] All med. priority SVG attributes
  - [ ] All low priority SVG attributes
- SVG DOM APIs
  - [ ] All high priority SVG DOM APIs
  - [ ] All med. priority SVG DOM APIs
  - [ ] All low priority SVG DOM APIs

**Set an example on top**
- SVG elements
  - [x] All high priority SVG elements
  - [ ] All med. priority SVG elements
  - [ ] All low priority SVG elements
- SVG attributes
  - [ ] All high priority SVG attributes
  - [ ] All med. priority SVG attributes
  - [ ] All low priority SVG attributes
- SVG DOM APIs
  - [ ] All high priority SVG DOM APIs
  - [ ] All med. priority SVG DOM APIs
  - [ ] All low priority SVG DOM APIs

**Make the example on top interactive**
- SVG elements
  - [ ] All high priority SVG elements
  - [ ] All med. priority SVG elements
  - [ ] All low priority SVG elements
- SVG attributes
  - [ ] All high priority SVG attributes
  - [ ] All med. priority SVG attributes
  - [ ] All low priority SVG attributes
- SVG DOM APIs
  - [ ] All high priority SVG DOM APIs
  - [ ] All med. priority SVG DOM APIs
  - [ ] All low priority SVG DOM APIs

**Comment by jmswisher** [comment]
Thanks to @SebastianZ for updating all of the medium priority SVG attribute pages. Feel free to work on high priority things too ;-)
