### ISSUE TITLE
SVG: Update high priority element pages [1/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#83]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, adding a better attributes overview)

**Pages**
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/ellipse
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polygon
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg
