### ISSUE TITLE
SVG: Add example on top of high priority element pages [1/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#84]
**Task**
Add an example on top of each pages

**Pages**
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/line
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/ellipse
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polygon
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/rect
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg
