### ISSUE TITLE
WebIDE documentation pages needing removal

### ISSUE THREAD

**Issue by irenesmith** [mdn/sprints#847]
This bug tracks pages from the WebIDE documentation that are no longer valid/need to be removed. This is work that is needed in preparation for FF #68.

# Acceptance Criteria
- [x] The page: [Running and debugging apps](https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Running_and_debugging_apps) has been removed.
- [x] The page: [Creating and editing apps](https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Creating_and_editing_apps) has been removed.
- [x] [Debugging Firefox OS over USB](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_OS_over_USB) has been removed.
- [x] [Debugging Firefox OS over Wifi](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_OS_over_Wifi) has been removed.

**Comment by juliandescottes** [comment]
Two other pages describe Firefox OS workflows and outdated WebIDE UIs:
- https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_OS_over_USB
- https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_OS_over_Wifi

**Comment by irenesmith** [comment]
Now that I have deleted these pages and their translations, please don't add new pages to this issue. Start a new issue instead and assign it to me, @irenesmith
