### ISSUE TITLE
SVG: Update high priority element pages [2/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#85]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, adding a better attributes overview)

**Pages**
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/pattern
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath
