### ISSUE TITLE
SVG: Add example on top of high priority element pages [2/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#86]
**Task**
Add an example on top of each pages

**Pages**
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/pattern
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text
- [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Element/textPath
