### ISSUE TITLE
SVG: Update high priority attributes pages [1/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#87]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/cx
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/cy
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dx
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dy
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/height
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pathLength
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/points
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/rx
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/ry
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x1
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/x2
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y1
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/y2
