### ISSUE TITLE
SVG: Add example on top of high priority attributes pages [2/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#89]
**Task**
Add an example on top of each pages

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dashoffset
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linecap
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-opacity
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width
