### ISSUE TITLE
SVG: Update high priority attributes pages [3/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#91]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clipPathUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-path
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/mask
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/maskContentUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/maskUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternContentUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternTransform
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-end
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-mid
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-start
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerHeight
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerWidth

**Comment by SebastianZ** [comment]
Those attributes are now all updated.

Sebastian

**Comment by Chucky122** [comment]
How can I find my app it's avaible but for adult only.

**Comment by jmswisher** [comment]
Thanks @SebastianZ !
