### ISSUE TITLE
Enable MySQL strict mode

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#917]
# User story
As a developer, I want to enable MySQL strict mode, to detect data issues early and enable an update to MySQL 5.7.

# Acceptance criteria
* Strict mode is enable in production
* No P1 bugs remain from switch to strict

# Tasks
* [x] Enable in development
* [x] Enable in staging
* [x] Enable in production

# References
* [bug 1401272](https://bugzilla.mozilla.org/show_bug.cgi?id=1401272) - Use MySQL Strict Mode (django_mysql.W001)
* http://django-mysql.readthedocs.org/en/latest/checks.html#django-mysql-w001-strict-mode
* Default in MySQL 5.7: https://dev.mysql.com/doc/refman/5.7/en/upgrading-from-previous-series.html

**Comment by jwhitlock** [comment]
Deployed to stage, with no detected issues. Deployed last night to production, still no issues. If it goes a week without issues, then the estimate was too conservative. Which is rare for Kuma work.
