### ISSUE TITLE
SVG: Add example on top of high priority attributes pages [3/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#92]
**Task**
Add an example on top of each pages

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clipPathUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-path
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/mask
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/maskContentUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/maskUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternContentUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternTransform
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/patternUnits
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pointer-events
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-end
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-mid
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/marker-start
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerHeight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerUnits
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerWidth

**Comment by SebastianZ** [comment]
`marker-end`, `marker-mid`, and `marker-start` now have top examples.

Sebastian
