### ISSUE TITLE
Don't show interactive examples on mobile version

### ISSUE THREAD

**Issue by schalkneethling** [mdn/sprints#921]
# User story

Reported by @atopal - "Interactive examples are currently shown to mobile and desktop users. On mobile the ability to edit an example is less useful, but the cost is generally higher due to slower networks and slower hardware. We should never show interactive examples on mobile. We should only show the non-interactive examples to mobile users where it makes sense (eg JS) and no example where that wouldn't make sense otherwise."

There is a further discussion in the related Bugzilla bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1522937

# Acceptance criteria

- [ ] We know what the performance impact of the 2 proposed options are.
- [ ] On mobile the interactive examples are not shown to users.
- [ ] On desktop, interactive examples still work as it does currently

# Tasks

1. - [x] Define what a solution looks like (for example, do we have a fallback, or do we just display nothing?)
2. - [x] Implement the [agreed upon testing scenarios](https://github.com/mdn/sprints/issues/921#issuecomment-460967275)
4. - [x] Open PR
5. - [x] Pushed to production

**Comment by schalkneethling** [comment]
After meeting with @atopal and @wbamberg last evening, we have decided to take the following approach this sprint:

We will create three variations of the same page:

1. Set the iframe to `display: none;`
2. No interactive example at all
3. Set the iframe to `display: none;` and set the `src` attribute of the iframe to an empty string.

**Comment by schalkneethling** [comment]
> Set the iframe to `display: none;` and set the `src` attribute of the iframe to an empty string.

Setting it to `about:blank` seems to be a better practice.

**Comment by schalkneethling** [comment]
@atopal @wbamberg I have opened the PR for this:
https://github.com/mozilla/kuma/pull/5252

I also created three pages for testing purposes:

* https://developer.mozilla.org/en-US/docs/User:schalkneethling/mobile/box-shadow-no-iex
* https://developer.mozilla.org/en-US/docs/User:schalkneethling/mobile/box-shadow-display-none
* https://developer.mozilla.org/en-US/docs/User:schalkneethling/mobile/box-shadow-display-none-empty-src

Once we have enough data from this round, I would like to do the tests again, but this time add the script to the `head` of the document.

**Comment by schalkneethling** [comment]
@atopal This has been merged into master. Once deployed, you can test the three pages above to see the change in performance.

**Comment by atopal** [comment]
I set the testing up here: https://github.com/mozilla/kuma/pull/5252#event-2138760922

**Comment by atopal** [comment]
Looking at our performance metrics, these hiding options seem to have no impact on performance.

**Comment by schalkneethling** [comment]
> I set the testing up here: [speedcurve.com/mozilla-add-ons/mdn/favorite/?d=7&db=47831&dc=2&de=1&ds=1](https://speedcurve.com/mozilla-add-ons/mdn/favorite/?d=7&db=47831&dc=2&de=1&ds=1) and I could swear I had already left this comment here 😕

@atopal Looks like `display:none` with an empty `src` is slightly faster. Should we try a round of tests with this same script added to the `head` of the document?

**Comment by atopal** [comment]
Sorry, didn't see this before. From what I can tell, doing nothing is just as good as empty src. while display none is slight slower. Let's try adding to the head.

**Comment by schalkneethling** [comment]
> Sorry, didn't see this before. From what I can tell, doing nothing is just as good as empty src. while display none is slight slower. Let's try adding to the head.

Hey @atopal,

Did some testing locally with the script added to the `head`. It simply executes to soon and never finds the `iframe` so, it has no effect.

It feels to me like the only way we will get a benefit here is if we re-architect the code to only load the Kuma side code if on desktop viewports. This also means we need to change the macro so that

1. It does not set the src of the iframe, but instead
2. The iframe is initially hidden (`display: none`)
3. sets the source into a `data` attribute on the `iframe`.

We then only set the `src` of the `iframe` if we are on desktop. Seems like there is not going to be an easy win here.

Thoughts?

**Comment by atopal** [comment]
@schalkneethling That makes sense. What would a test of that look like? Would you mind sketching that out? I'm a bit concerned that that would have a negative impact on our main performance KPI, but maybe not. Performance can be very counterintuitive as I have learned last year ;)

**Comment by schalkneethling** [comment]
User story that will replace this if accepted:
https://github.com/mdn/sprints/issues/1089

**Comment by jwhitlock** [comment]
For the purpose of sprint accounting, I think it makes sense to close this and track the next iteration in the new story.
