### ISSUE TITLE
SVG: Update high priority attributes pages [4/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#93]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/direction
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-family
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-size
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-stretch
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-style
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-variant
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-weight
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-decoration
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/textLength
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/word-spacing
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/writing-mode

**Comment by SebastianZ** [comment]
The pages for `direction`, `font-family`, `font-size`, `font-style`, `font-variant`, `font-weight`, `letter-spacing`, and `word-spacing` are updated (including top examples). More to come. :smiley:

Sebastian

**Comment by SebastianZ** [comment]
All done now.

**Comment by jmswisher** [comment]
Thanks @SebastianZ
