### ISSUE TITLE
SVG: Add example on top of high priority attributes pages [4/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#94]
**Task**
Add an example on top of each pages

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/direction
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-family
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-size
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-stretch
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-style
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-variant
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-weight
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-decoration
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/textLength
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/word-spacing
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/writing-mode

**Comment by SebastianZ** [comment]
I've added examples to `direction`, `font-family`, `font-size`, `font-style`, `font-variant`, `font-weight`, `letter-spacing`, and `word-spacing`.

Sebastian
