### ISSUE TITLE
Increase KumaScript macro test coverage, Q1 S2

### ISSUE THREAD

**Issue by jwhitlock** [mdn/sprints#940]
# User story
As MDN staff, I want more KumaScript macro tests, so I can be unblocked from making changes and reviewing PRs.

# Acceptance criteria
* Time-boxed effort to add macro tests. Some areas of emphasis:
  - Tests that can be applied to many macros, perhaps automatically, like a valid HTML test
  - Tests that cover untested macros, like https://github.com/mdn/kumascript/pull/1037, until they can get targeted unit tests
  - Tests for macros that change often
  - Tests for JSON blobs

# Tasks
- [x] Create a test utility function that validates its HTML input (and could be used as part of many of the subsequent test suites)
- [x] Test for `APIRef.ejs`
- [x] Test for `AddonSidebar.ejs`
- [ ] Test for `InterfaceData.json`

**Comment by jwhitlock** [comment]
@escattone Do you plan to add ``InterfaceData.json`` tests this sprint, or put it back on the backlog?

**Comment by escattone** [comment]
@jwhitlock I've used up my 3-point time box for this sprint, so I think it should go on the backlog.

**Comment by jwhitlock** [comment]
I've moved the remaining task to #1062, feel free to edit if it doesn't match the remaining work.
