### ISSUE TITLE
SVG: Update high priority attribute pages [5/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#95]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/id
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/class
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/display
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/style
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/tabindex
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/cursor

**Comment by SebastianZ** [comment]
I've updated all except `style` and `tabindex`. (Unfortunately, for some the newest version is not shown due to [bug 1288148](https://bugzilla.mozilla.org/show_bug.cgi?id=1288148).)

Sebastian

**Comment by SebastianZ** [comment]
`style` and `tabindex` are now also updated. So this issue can be closed.

Sebastian

**Comment by jmswisher** [comment]
Thanks @SebastianZ !
