### ISSUE TITLE
Refactor touch events

### ISSUE THREAD

**Issue by Elchi3** [mdn/sprints#950]
This is a work item for #685.

Pages:
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/touchcancel
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/touchend
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/touchenter (delete)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/touchleave (delete)
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/touchmove
- [x] https://developer.mozilla.org/en-US/docs/Web/Events/touchstart

The target interfaces here are document and element, so this is a case where there is not one redirect, but a split. We could decide to redirect to either document or element, though.

# Tasks
- [x] [Document events interface page](https://developer.mozilla.org/en-US/docs/Web/API/Document)
- [x] [Element events interface page](https://developer.mozilla.org/en-US/docs/Web/API/Element)

- [x] Document:touchcancel
- [x] Translated pages moved
- [x] Element:touchcancel

- [x] Document:touchend
- [x] Translated pages moved
- [x] Element:touchend

- [x]  Document:touchenter -- removed as it is not part of the spec
- [x] Document:touchleave -- removed as it is not part of the spec

- [x] Document:touchmove
- [x] Translated pages moved
- [x] Element:touchmove

- [x] Document:touchstart
- [x] Translated pages moved
- [x] Element:touchmove

- [x] BCD PR

**Comment by irenesmith** [comment]
Reviewer Estelle

**Comment by irenesmith** [comment]
@estelle Everything has been done but the BCD PR. You can start reviewing.

**Comment by estelle** [comment]
https://www.quirksmode.org/mobile/tableTouch.html - not sure if you already wrote the bcd and haven't submitted for PR, but that URL can help

**Comment by irenesmith** [comment]
Here is the pull request: BCD Pull Request #[3534](https://github.com/mdn/browser-compat-data/pull/3534)

**Comment by wbamberg** [comment]
@irenesmith , I hope you don't mind me adding a few nit-picking comments, but I think it's worth trying to be consistent as much as we can.

* titles should have a space between interface name and event name: `Document: touchend event` not `Document:touchend event`
* the blue boxes should use `<th>` not `<td>` for the first column (sorry this wasn't in the post)
* "Event handler" in the blue box should be "Event handler property"

**Comment by irenesmith** [comment]
Moving this back to in progress because i have some fixes to make.

@wbamberg, Thank you for your comments. Actually, I noticed the Event handler property myself late yesterday and, since I have to move the Element-related ones anyway, I will fix the other things as well.

@estelle, if you haven't already had a look, hold off until I get a chance to fix the things Will pointed out and to also move the events from Element to HTMLElement. Thanks!

**Comment by irenesmith** [comment]
BCD data is now showing up properly on the pages.

**Comment by wbamberg** [comment]
@irenesmith , can you comment on the status of this story? Is it waiting for review, or finished?

**Comment by irenesmith** [comment]
This one has been reviewed, updated, and the BCD information is appearing as it should.

**Comment by wbamberg** [comment]
Thanks for the update @irenesmith ! I just noticed that these pages are missing specification sections, can you add these?

**Comment by irenesmith** [comment]
Spec links have been added
