### ISSUE TITLE
Document console.debug()

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#958]
Document the `Console.debug()` method.

https://bugzilla.mozilla.org/show_bug.cgi?id=1456490

## Tasks

- [x] Write the page [Console.debug()](https://developer.mozilla.org/en-US/docs/Web/API/Console/debug)
- [x] Ensure that the main `Console` page links to it (which it almost certainly does already)
- [x] Verify that BCD includes the `debug()` method and that data is up to date

## Acceptance criteria

- [ ] Content has been added
- [ ] BCD updated if necessary
- [ ] Submitted for review

**Comment by a2sheppy** [comment]
[PR 3448](https://github.com/mdn/browser-compat-data/pull/3448) submitted to add `debug()` to BCD.
