### ISSUE TITLE
SVG: Update high priority attribute pages [6/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#96]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern layout (especially, breakdown page by element)

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filter
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/radius
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/refX
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/refY
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/opacity
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/visibility
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overflow
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/paint-order

**Comment by SebastianZ** [comment]
They are all updated now except `xml:space`, which is actually marked as medium priority in the spreadsheet.

Sebastian

**Comment by jmswisher** [comment]
Move xml:space to[ Update medium priority attribute pages](https://github.com/mdn/sprints/issues/110)
