### ISSUE TITLE
Write guide to finding compatibility information for each of the major browsers

### ISSUE THREAD

**Issue by a2sheppy** [mdn/sprints#963]
The meta docs need a guide to locating and verifying compatibility and version information for each of Firefox, Chrome, and Edge. Ideally also Safari but Safari is extra tricky.

***NOTE —— For Hadda Brooks, this is timeboxed to 1 point for continued work on the Chrome material.***

https://bugzilla.mozilla.org/show_bug.cgi?id=1512620

## Tasks

- [x] Research and document how to determine to which Firefox release a given feature (element, attribute, interface, property, method, etc) was added
- [ ] Research and document how to determine to which Chrome release a given feature (element, attribute, interface, property, method, etc) was added
- [ ] Research and document how to determine to which Edge release a given feature (element, attribute, interface, property, method, etc) was added
- [ ] Attempt to do likewise for Safari
- [x] Integrate the guide into the MDN menus
- [ ] Reference the guide from appropriate pages on MDN

## Acceptance criteria

- [ ] Article has been written and integrated into the meta doc menu structure
- [ ] Article has been reviewed by another member of the writing staff

**Comment by Elchi3** [comment]
See also https://github.com/mdn/browser-compat-data/issues/3226

Joe Medley started this work for Chrome. Might want to contact him. I'm happy to review a PR against the BCD docs for this if we decide there should be material in the repo.
