### ISSUE TITLE
SVG: Add example on top of high priority attributes pages [6/6]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#97]
**Task**
Add an example on top of each pages

**Pages**
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filter
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/radius
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xml:space
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/refX
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/refY
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/opacity
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/visibility
* [x] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overflow
* [ ] https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/paint-order

**Comment by SebastianZ** [comment]
I've added an example to `filter` and `opacity`.

Sebastian

**Comment by SebastianZ** [comment]
`href`, `xlink:href`, `opacity`, `visibility`, and `overflow` now also have top examples.

Sebastian
