### ISSUE TITLE
SVG: Update high priority API pages [1/2]

### ISSUE THREAD

**Issue by JeremiePat** [mdn/sprints#98]
**Task**
Update content to reflect SVG2 changes
Update page structure to fit modern MDN API layout pages.

**Pages**
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGCircleElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGEllipseElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGGeometryElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGLineElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGPolygonElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGPolylineElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGRect
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGRectElement
* [ ] https://developer.mozilla.org/en-US/docs/Web/API/SVGImageElement
